import { StyleSheet } from 'react-native';
import { Theme } from '../../../theme/tokens';
import { HEADER_CONSTANTS } from '../../../constants/headerConstants';

export const attendanceStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.colors.background,
  },
  headerStandard: {
    backgroundColor: Theme.colors.primary,
    borderBottomLeftRadius: HEADER_CONSTANTS.BORDER_RADIUS,
    borderBottomRightRadius: HEADER_CONSTANTS.BORDER_RADIUS,
    paddingBottom: HEADER_CONSTANTS.PADDING_BOTTOM,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: HEADER_CONSTANTS.PADDING_HORIZONTAL,
    paddingBottom: Theme.spacing.md,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.md,
    backgroundColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: Theme.typography.h3.fontSize,
    fontWeight: '700',
    color: Theme.colors.card,
  },
  notificationBtn: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.md,
    backgroundColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tabSwitcher: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.xs,
    marginHorizontal: Theme.spacing.xl,
    marginTop: Theme.spacing.md,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: Theme.radius.md,
  },
  activeTab: {
    backgroundColor: Theme.colors.card,
  },
  tabText: {
    color: 'rgba(255,255,255,0.6)',
    ...Theme.typography.body,
    fontWeight: '600',
  },
  activeTabText: {
    color: Theme.colors.primary,
    fontWeight: '700',
  },
  heroContent: {
    paddingHorizontal: Theme.spacing.xl,
    marginTop: Theme.spacing.lg,
  },
  heroGreeting: {
    color: Theme.colors.card,
    fontSize: Theme.typography.h2.fontSize,
    fontWeight: '800',
  },
  heroSubtext: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: Theme.typography.caption.fontSize,
    marginTop: Theme.spacing.xs,
  },
  scrollContent: {},
  stepperWrapper: {
    marginTop: -20,
    marginBottom: Theme.spacing.lg,
    paddingHorizontal: Theme.spacing.md,
    alignItems: 'center',
  },
  stepperContainer: {
    flexDirection: 'row',
    backgroundColor: Theme.colors.card,
    paddingVertical: 14,
    paddingHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.xxl,
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    alignItems: 'center',
    width: '100%',
    justifyContent: 'center',
  },
  stepItem: {
    alignItems: 'center',
    width: 65,
  },
  stepCircle: {
    width: 32,
    height: 32,
    borderRadius: Theme.radius.lg,
    backgroundColor: Theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
    borderWidth: 2,
    borderColor: Theme.colors.border,
  },
  stepActive: {
    backgroundColor: Theme.colors.primary,
    borderColor: Theme.colors.primary,
    elevation: 3,
    shadowOpacity: 0.2,
  },
  stepDone: {
    backgroundColor: Theme.colors.success,
    borderColor: Theme.colors.success,
  },
  stepNumber: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '600',
    color: Theme.colors.textSec,
  },
  stepNumberActive: {
    color: Theme.colors.card,
  },
  stepLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: Theme.colors.textMuted,
    fontWeight: '600',
  },
  stepLabelActive: {
    color: Theme.colors.primary,
    fontWeight: '700',
  },
  stepConnector: {
    width: 18,
    height: 2.5,
    backgroundColor: Theme.colors.border,
    marginTop: -16,
    marginHorizontal: Theme.spacing.xs,
  },
  stepConnectorDone: {
    backgroundColor: Theme.colors.success,
  },
  mainCard: {
    marginHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.xxxl,
    backgroundColor: Theme.colors.card,
    borderWidth: 0,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    marginBottom: Theme.spacing.md,
    overflow: 'hidden',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    padding: 18,
    backgroundColor: Theme.colors.background,
    borderBottomWidth: 1,
    borderBottomColor: '#ECEFF1',
  },
  cardTitle: {
    fontSize: Theme.typography.h4.fontSize,
    fontWeight: '700',
    color: Theme.colors.text,
    flex: 1,
  },
  cardBody: {
    padding: 18,
  },
  field: {
    marginBottom: 18,
  },
  label: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '600',
    color: Theme.colors.textSec,
    marginBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  pickerTrigger: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F7F9FB',
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    padding: 13,
  },
  pickerTriggerText: {
    ...Theme.typography.body,
    color: Theme.colors.text,
    fontWeight: '500',
  },
  input: {
    backgroundColor: '#F7F9FB',
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    padding: 13,
    ...Theme.typography.body,
    color: Theme.colors.text,
    fontWeight: '500',
  },
  buttonGrid: {
    flexDirection: 'row',
    gap: 14,
    marginBottom: Theme.spacing.md,
  },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Theme.spacing.sm,
    paddingVertical: 14,
    borderRadius: Theme.radius.md,
    elevation: 2,
    shadowOpacity: 0.1,
  },
  actionBtnText: {
    color: Theme.colors.card,
    ...Theme.typography.body,
    fontWeight: '600',
  },
  previewContainer: {
    borderRadius: Theme.radius.lg,
    overflow: 'hidden',
    marginBottom: Theme.spacing.md,
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    elevation: 2,
    shadowOpacity: 0.08,
  },
  previewImage: {
    width: '100%',
    height: 200,
    resizeMode: 'cover',
  },
  previewBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: Theme.colors.success,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: Theme.radius.md,
    elevation: 3,
    shadowOpacity: 0.3,
  },
  previewBadgeText: {
    color: Theme.colors.card,
    ...Theme.typography.caption,
    fontWeight: '600',
  },
  primaryButton: {
    backgroundColor: Theme.colors.primary,
    borderRadius: Theme.radius.md,
    height: 52,
    elevation: 3,
    shadowOpacity: 0.2,
  },
  manualFallbackBtn: {
    marginTop: Theme.spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.background,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.xl,
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    shadowColor: Theme.colors.textSec,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  manualFallbackIconContainer: {
    width: 44,
    height: 44,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
    shadowColor: Theme.colors.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  manualFallbackTextContainer: {
    flex: 1,
  },
  manualFallbackBtnText: {
    color: Theme.colors.text,
    ...Theme.typography.bodyMd,
    marginBottom: 2,
  },
  manualFallbackSubText: {
    color: Theme.colors.textSec,
    ...Theme.typography.caption,
    fontWeight: '500',
  },
  teacherInfo: {
    backgroundColor: '#EFF6FF',
    padding: 18,
    borderRadius: Theme.radius.lg,
    marginBottom: Theme.spacing.md,
    borderWidth: 1.5,
    borderColor: '#BAE6FD',
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Theme.spacing.sm,
  },
  infoLabel: {
    ...Theme.typography.caption,
    fontWeight: '600',
    color: '#0369A1',
  },
  infoValue: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '700',
    color: '#0C4A6E',
  },
  chipContainer: {
    flexDirection: 'row',
    gap: 10,
    paddingVertical: Theme.spacing.xs,
  },
  chip: {
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
    backgroundColor: '#F7F9FB',
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
  },
  chipActive: {
    backgroundColor: Theme.colors.primary,
    borderColor: Theme.colors.primary,
    elevation: 2,
    shadowOpacity: 0.15,
  },
  chipText: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '600',
    color: Theme.colors.textSec,
  },
  chipTextActive: {
    color: Theme.colors.card,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    marginTop: Theme.spacing.md,
  },
  buttonRowInline: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
  },
  dateSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    backgroundColor: '#F7F9FB',
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  dateSelectorText: {
    ...Theme.typography.body,
    fontWeight: '600',
    color: Theme.colors.text,
  },
  imageGridHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
  },
  imageCount: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '700',
    color: Theme.colors.textSec,
    backgroundColor: Theme.colors.background,
    paddingHorizontal: 10,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.sm,
  },
  thumbScroll: {
    marginBottom: 18,
    paddingVertical: Theme.spacing.xs,
  },
  thumbWrapper: {
    width: 90,
    height: 90,
    borderRadius: Theme.radius.md,
    marginRight: Theme.spacing.md,
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    elevation: 2,
    shadowOpacity: 0.06,
    overflow: 'hidden',
  },
  thumbImg: {
    width: '100%',
    height: '100%',
    borderRadius: 13,
    resizeMode: 'cover',
  },
  thumbRemove: {
    position: 'absolute',
    top: -6,
    right: -6,
    elevation: 3,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Theme.spacing.xl,
    paddingHorizontal: Theme.spacing.md,
  },
  miniStatCard: {
    backgroundColor: Theme.colors.card,
    flex: 1,
    marginHorizontal: 6,
    padding: 14,
    borderRadius: Theme.radius.xl,
    borderLeftWidth: 5,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  miniStatVal: {
    fontSize: Theme.typography.h3.fontSize,
    fontWeight: '800',
    color: Theme.colors.text,
  },
  miniStatLabel: {
    ...Theme.typography.label,
    fontWeight: '600',
    color: Theme.colors.textMuted,
    marginTop: Theme.spacing.xs,
  },
  filterScroll: {
    marginBottom: Theme.spacing.md,
    paddingVertical: Theme.spacing.xs,
  },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.radius.xl,
    backgroundColor: Theme.colors.background,
    marginRight: 10,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  filterChipActive: {
    backgroundColor: Theme.colors.primary,
    borderColor: Theme.colors.primary,
  },
  filterChipText: {
    ...Theme.typography.caption,
    fontWeight: '600',
    color: Theme.colors.textSec,
  },
  filterChipTextActive: {
    color: Theme.colors.card,
  },
  tableWrapper: {
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.lg,
    overflow: 'hidden',
    marginBottom: Theme.spacing.md,
    elevation: 2,
    shadowOpacity: 0.06,
  },
  tHeader: {
    flexDirection: 'row',
    backgroundColor: Theme.colors.background,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderBottomWidth: 2,
    borderBottomColor: '#ECEFF1',
  },
  tHead: {
    ...Theme.typography.label,
    fontWeight: '700',
    color: Theme.colors.textSec,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  tRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.background,
    backgroundColor: Theme.colors.card,
  },
  rowPresent: {
    backgroundColor: Theme.colors.successBg,
  },
  rowAbsent: {
    backgroundColor: Theme.colors.errorBg,
  },
  rowChanged: {
    borderWidth: 2,
    borderColor: Theme.colors.amberLight,
    margin: -1,
  },
  tCell: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '600',
    color: Theme.colors.textSec,
  },
  tCellName: {
    ...Theme.typography.body,
    fontWeight: '700',
    color: Theme.colors.text,
  },
  changedText: {
    ...Theme.typography.label,
    fontWeight: '600',
    color: Theme.colors.warning,
    marginTop: 2,
  },
  statusToggle: {
    flexDirection: 'row',
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.md,
    padding: 3,
    width: 90,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  toggleBtn: {
    flex: 1,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Theme.radius.sm,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  toggleBtnP: {
    backgroundColor: Theme.colors.greenLight,
    borderColor: Theme.colors.success,
  },
  toggleBtnA: {
    backgroundColor: Theme.colors.redLight,
    borderColor: Theme.colors.error,
  },
  toggleText: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '700',
    color: Theme.colors.textMuted,
  },
  toggleTextActive: {
    color: Theme.colors.text,
  },
  retryBtn: {
    width: 54,
    height: 54,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    elevation: 2,
    shadowOpacity: 0.06,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: Theme.radius.md,
  },
  badgeText: {
    ...Theme.typography.label,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  toast: {
    position: 'absolute',
    top: 60,
    left: 16,
    right: 16,
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 10,
    zIndex: 9999,
    borderLeftWidth: 5,
    borderLeftColor: Theme.colors.violet,
  },
  toastIcon: { fontSize: Theme.typography.h2.fontSize, marginRight: 14 },
  toastContent: { flex: 1 },
  toastTitle: { ...Theme.typography.body, fontWeight: '700', color: Theme.colors.text },
  toastMessage: { ...Theme.typography.caption, color: Theme.colors.textSec, marginTop: 3 },
  toastClose: { color: '#CBD5E1', fontSize: Theme.typography.h3.fontSize, padding: Theme.spacing.xs, fontWeight: '600' },
  cameraContainer: {
    position: 'absolute' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#000',
    zIndex: 9999,
  },
  camera: { flex: 1 },
  cameraOverlay: {
    position: 'absolute',
    bottom: 50,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  cameraStep: {
    backgroundColor: 'rgba(0,31,80,0.9)',
    color: Theme.colors.card,
    paddingHorizontal: 18,
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.radius.xl,
    ...Theme.typography.caption,
    fontWeight: '600',
    marginBottom: Theme.spacing.lg,
  },
  cameraControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.lg,
  },
  cameraCaptureBtn: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: Theme.colors.background,
    borderWidth: 6,
    borderColor: 'rgba(255,255,255,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
  },
  cameraDoneBtn: {
    backgroundColor: Theme.colors.success,
    paddingHorizontal: 18,
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.xl,
    elevation: 3,
  },
  cameraDoneText: { color: Theme.colors.card, fontSize: Theme.typography.caption.fontSize, fontWeight: '600' },
  cameraToggleBtn: {
    width: 60,
    height: 60,
    borderRadius: Theme.radius.xxxl,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: Theme.colors.card,
  },
  closeCameraBtn: {
    position: 'absolute',
    top: 50,
    right: 20,
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderRadius: Theme.radius.xl,
    padding: 6,
    elevation: 5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    justifyContent: 'center',
    padding: Theme.spacing.xl,
  },
  modalContent: {
    backgroundColor: Theme.colors.card,
    borderRadius: 28,
    padding: Theme.spacing.lg,
    alignItems: 'center',
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: Theme.spacing.xl,
    alignItems: 'center',
  },
  modalTitle: { ...Theme.typography.h3, color: Theme.colors.text },
  modalImage: { width: '100%', height: 320, borderRadius: Theme.radius.lg, marginBottom: Theme.spacing.lg, resizeMode: 'cover' },
  modalButtons: { flexDirection: 'row', gap: 14, width: '100%' },
  modalBtn: { flex: 1, height: 52, borderRadius: Theme.radius.md, alignItems: 'center', justifyContent: 'center', elevation: 2 },
  modalBtnPrimary: { backgroundColor: Theme.colors.primary },
  modalBtnSecondary: { backgroundColor: Theme.colors.background, borderWidth: 1.5, borderColor: Theme.colors.border },
  modalBtnTextPrimary: { ...Theme.typography.body, color: Theme.colors.card, fontWeight: '600' },
  modalBtnTextSecondary: { ...Theme.typography.body, color: Theme.colors.textSec, fontWeight: '600' },
  warningBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    backgroundColor: Theme.colors.amberLight,
    padding: 14,
    borderRadius: Theme.radius.md,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: Theme.colors.amberLight,
  },
  warningText: {
    flex: 1,
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '600',
    color: Theme.colors.warning,
  },
  resetBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.background,
    marginRight: 10,
  },
  resetBtnDisabled: {
    opacity: 0.6,
  },
  resetBtnText: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '600',
    color: Theme.colors.primary,
  },
  manualStrip: {
    marginBottom: Theme.spacing.md,
    padding: 14,
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  manualStripText: {
    ...Theme.typography.caption,
    color: Theme.colors.textSec,
    fontWeight: '600',
    marginBottom: 10,
  },
  miniChipContainer: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  miniChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: Theme.radius.xl,
  },
  miniChipSuccess: {
    backgroundColor: Theme.colors.greenLight,
  },
  miniChipDanger: {
    backgroundColor: Theme.colors.redLight,
  },
  miniChipWarning: {
    backgroundColor: Theme.colors.amberLight,
  },
  miniChipText: {
    ...Theme.typography.label,
    fontWeight: '800',
  },
  resultNote: {
    marginBottom: Theme.spacing.md,
    padding: Theme.spacing.md,
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  resultNoteText: {
    ...Theme.typography.caption,
    color: Theme.colors.textSec,
    fontWeight: '500',
  },
  resultSub: {
    ...Theme.typography.caption,
    color: Theme.colors.textSec,
    marginTop: 2,
  },
  errorModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Theme.spacing.lg,
  },
  errorModalContent: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.xxl,
    padding: Theme.spacing.lg,
    alignItems: 'center',
    width: '100%',
    maxWidth: 340,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
  },
  errorModalIconContainer: {
    width: 72,
    height: 72,
    borderRadius: Theme.radius.xxxl,
    backgroundColor: Theme.colors.redLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Theme.spacing.xl,
  },
  errorModalTitle: {
    ...Theme.typography.h3,
    color: Theme.colors.error,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: Theme.spacing.md,
  },
  errorModalMessage: {
    ...Theme.typography.body,
    color: Theme.colors.textSec,
    textAlign: 'center',
    marginBottom: Theme.spacing.lg,
    lineHeight: 20,
  },
  errorModalButton: {
    backgroundColor: Theme.colors.error,
    height: 48,
    borderRadius: Theme.radius.md,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
    shadowColor: Theme.colors.error,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  errorModalButtonText: {
    ...Theme.typography.body,
    color: Theme.colors.card,
    fontWeight: '600',
  },
});
