import { StyleSheet } from 'react-native';
import {Theme, C, colors} from '../../../theme/tokens';

export const teacherMyAttendanceStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.colors.background,
  },
  scrollView: {
    flex: 1,
  },
  pageBody: {},
  errorCard: {
    padding: Theme.spacing.lg,
    alignItems: 'center',
    gap: Theme.spacing.sm,
    marginTop: Theme.spacing.xs,
  },
  errorTitle: { color: Theme.colors.text, fontSize: Theme.typography.h4.fontSize, marginTop: Theme.spacing.xs },
  errorText: { color: Theme.colors.textMuted, textAlign: 'center', ...Theme.typography.body },
  retryBtn: {
    marginTop: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.xl,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.primary,
  },
  retryBtnText: { color: Theme.colors.card },
  monthNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: C.colors.card,
    borderRadius: Theme.radius.lg,
    paddingVertical: 10,
    paddingHorizontal: Theme.spacing.sm,
    marginBottom: Theme.spacing.md,
    ...C.shadow.sm,
  },
  monthNavBtn: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.xl,
    backgroundColor: C.colors.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  monthNavLabel: {
    fontSize: Theme.typography.h4.fontSize,
    color: C.colors.text,
  },
  statsOverview: {
    flexDirection: 'row',
    backgroundColor: C.colors.card,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.xl,
    alignItems: 'center',
    ...C.shadow.sm,
    marginBottom: Theme.spacing.xl,
  },
  percentageCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 6,
    borderColor: C.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  percentageValue: {
    ...Theme.typography.h3,
    color: C.colors.text,
  },
  percentageLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: C.colors.textMuted,
  },
  statsDivider: {
    width: 1,
    height: 60,
    backgroundColor: C.colors.border,
    marginHorizontal: 25,
  },
  statsRight: {
    flex: 1,
    gap: Theme.spacing.sm,
  },
  statRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: Theme.spacing.sm,
  },
  statLabel: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.colors.textMuted,
    flex: 1,
  },
  statValue: {
    ...Theme.typography.body,
    fontWeight: '700',
    color: C.colors.text,
  },
  calendarCard: {
    backgroundColor: C.colors.card,
    borderRadius: Theme.radius.xl,
    padding: 10,
    marginBottom: Theme.spacing.xl,
    ...C.shadow.sm,
    overflow: 'hidden',
  },
  calendar: {
    borderRadius: Theme.radius.xl,
    backgroundColor: C.colors.card,
  },
  detailsCard: {
    backgroundColor: C.colors.card,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.xl,
    marginBottom: Theme.spacing.xl,
    ...C.shadow.sm,
  },
  detailsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: C.colors.border,
    paddingBottom: 10,
  },
  detailsTitle: {
    ...Theme.typography.h4,
    color: C.colors.text,
  },
  detailsDate: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.colors.textMuted,
  },
  statusBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: C.colors.background,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
  },
  statusInfo: {
    flex: 1,
  },
  statusLabel: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.colors.textMuted,
    marginBottom: Theme.spacing.xs,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  statusValue: {
    fontSize: Theme.typography.h3.fontSize,
    fontWeight: '700',
  },
  statusIndicator: {
    width: 12,
    height: 12,
    borderRadius: Theme.radius.sm,
  },
  sessionRow: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    marginTop: Theme.spacing.md,
  },
  sessionChip: {
    flex: 1,
    backgroundColor: C.colors.background,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
  },
  sessionLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: C.colors.textMuted,
    marginBottom: Theme.spacing.xs,
    textTransform: 'uppercase',
  },
  sessionValue: {
    fontSize: Theme.typography.body.fontSize,
    fontWeight: '600',
    color: C.colors.text,
  },
  recentCard: {
    padding: Theme.spacing.xl,
    marginBottom: Theme.spacing.xl,
  },
  recentTitle: {
    fontSize: Theme.typography.h4.fontSize,
    color: C.colors.text,
    marginBottom: Theme.spacing.md,
  },
  recentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: C.colors.border,
    gap: Theme.spacing.md,
  },
  recentDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  recentDate: {
    flex: 1,
    ...Theme.typography.body,
    color: C.colors.textSec,
  },
  recentStatus: {
    fontSize: Theme.typography.body.fontSize,
    color: C.colors.text,
  },
  legendCard: {
    backgroundColor: C.colors.card,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.xl,
    marginBottom: Theme.spacing.xl,
    ...C.shadow.sm,
  },
  legendTitle: {
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '700',
    color: C.colors.textMuted,
    letterSpacing: 1,
    marginBottom: Theme.spacing.md,
  },
  legendGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Theme.spacing.md,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    width: '30%',
  },
  legendDot: {
    width: 14,
    height: 14,
    borderRadius: 4,
  },
  legendText: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.colors.textSec,
  },
  loaderOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
