import { StyleSheet, Platform } from 'react-native';
import { Theme, C } from '../../../theme/tokens';

export const PAGE_PAD = 16;

export const studentManagementStyles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: Theme.spacing.md,
    paddingBottom: Theme.spacing.md,
  },
  headerCopy: { flex: 1, gap: Theme.spacing.xs },
  kicker: {
    ...Theme.typography.label,
    color: C.primary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  title: { fontSize: Theme.typography.h2.fontSize, color: C.t1, lineHeight: 28 },
  titleSub: { ...Theme.typography.caption, color: C.t3, lineHeight: 18, maxWidth: 320 },
  headerActions: { flexDirection: 'row', gap: Theme.spacing.sm, flexWrap: 'wrap', justifyContent: 'flex-end' },
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: C.primary,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
  },
  primaryBtnText: { color: Theme.colors.card, fontSize: Theme.typography.caption.fontSize },
  secondaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: C.white,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: C.border,
  },
  secondaryBtnText: { color: C.t1, fontSize: Theme.typography.caption.fontSize },
  summaryRow: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
    marginBottom: Theme.spacing.md,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: C.white,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
    borderRadius: Theme.radius.md,
    paddingVertical: 10,
    paddingHorizontal: Theme.spacing.sm,
    alignItems: 'center',
  },
  summaryValue: { fontSize: Theme.typography.h3.fontSize, color: C.t1 },
  summaryLabel: { fontSize: Theme.typography.label.fontSize, color: C.t3, marginTop: 2, fontWeight: '500', textAlign: 'center' },
  welcomeSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.lg,
    backgroundColor: C.white,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: C.border,
  },
  welcomeTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: C.t1,
  },
  welcomeSub: {
    ...Theme.typography.caption,
    color: C.t3,
    marginTop: 2,
  },
  dateBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: C.bg,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: Theme.radius.sm,
    borderWidth: 1,
    borderColor: C.border,
  },
  dateText: {
    ...Theme.typography.label,
    color: C.t2,
  },
  refreshBtn: {
    width: 38,
    height: 38,
    borderRadius: 9,
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tableFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Theme.spacing.md,
    borderTopWidth: 1,
    borderTopColor: C.border,
    backgroundColor: C.bg,
  },
  footerText: { ...Theme.typography.caption, color: C.t3 },
  pagination: { flexDirection: 'row', gap: 6 },
  pageBtn: {
    width: 34,
    height: 34,
    borderRadius: Theme.radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.white,
  },
  pageBtnActive: { backgroundColor: C.primary, borderColor: C.primary },
  pageBtnDisabled: { opacity: 0.5 },
  pageBtnText: { ...Theme.typography.caption, color: C.t3 },
  pageBtnTextActive: { color: Theme.colors.card },
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },
  contentOverlap: {
    flex: 1,
    backgroundColor: C.bg,
    zIndex: 10,
  },
  tabSwitcher: {
    marginBottom: Theme.spacing.sm,
  },
  enrollmentContainer: {
    flex: 1,
  },
  stepperWrapper: {
    backgroundColor: C.white,
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: 10,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: C.border,
    marginBottom: Theme.spacing.xl,
  },
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepItem: {
    alignItems: 'center',
    width: 60,
  },
  stepCircle: {
    width: 28,
    height: 28,
    borderRadius: Theme.radius.md,
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  stepActive: {
    backgroundColor: C.navy,
    borderColor: C.navy,
  },
  stepDone: {
    backgroundColor: C.success,
    borderColor: C.success,
  },
  stepNumber: {
    ...Theme.typography.caption,
    color: C.t3,
  },
  stepNumberActive: {
    color: Theme.colors.card,
  },
  stepLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: C.t4,
    textAlign: 'center',
  },
  stepLabelActive: {
    color: C.t1,
  },
  stepConnector: {
    flex: 1,
    height: 2,
    backgroundColor: C.border,
        marginHorizontal: -10,
    zIndex: -1,
  },
  stepConnectorDone: {
    backgroundColor: C.success,
  },
  stepForm: {
    backgroundColor: C.white,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: C.border,
    padding: Theme.spacing.xl,
  },
  stepTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: C.t1,
    marginBottom: Theme.spacing.xs,
  },
  stepSubtitle: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.t3,
    marginBottom: Theme.spacing.xl,
  },
  formGrid: {
    gap: Theme.spacing.md,
  },
  row: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
  },
  inputError: {
    borderColor: C.danger,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 9,
    backgroundColor: C.bg,
    overflow: 'hidden',
    height: 48,
    justifyContent: 'center',
  },
  picker: {
    height: 48,
    width: '100%',
  },
  dateInput: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 48,
  },
  inputText: {
    ...Theme.typography.body,
    color: C.t1,
  },
  divider: {
    height: 1,
    backgroundColor: C.borderLight,
    marginVertical: Theme.spacing.sm,
  },
  photoUploadContainer: {
    alignItems: 'center',
  },
  photoFrame: {
    width: 200,
    height: 200,
    borderRadius: 100,
    borderWidth: 2,
    borderColor: C.border,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Theme.spacing.lg,
    overflow: 'hidden',
    backgroundColor: C.bg,
  },
  photoPreview: {
    width: '100%',
    height: '100%',
  },
  photoPlaceholder: {
    alignItems: 'center',
    gap: Theme.spacing.sm,
  },
  previewContainer: {
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  removePhotoBtn: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 15,
    padding: Theme.spacing.xs,
  },
  photoActions: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    marginTop: Theme.spacing.md,
  },
  photoActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
  },
  photoActionText: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.t1,
  },
  reviewContainer: {
    gap: Theme.spacing.md,
  },
  reviewCard: {
    backgroundColor: C.bg,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    borderWidth: 1,
    borderColor: C.border,
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    marginBottom: Theme.spacing.xl,
    paddingBottom: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: C.borderLight,
  },
  reviewAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
  },
  reviewName: {
    fontSize: Theme.typography.h4.fontSize,
    color: C.t1,
  },
  reviewSub: {
    ...Theme.typography.caption,
    color: C.t3,
  },
  reviewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
  },
  reviewItem: {
    width: '45%',
  },
  reviewLabel: {
    ...Theme.typography.label,
    color: C.t4,
    textTransform: 'uppercase',
    marginBottom: Theme.spacing.xs,
  },
  reviewValue: {
    ...Theme.typography.body,
    color: C.t1,
  },
  reviewAddress: {
    borderTopWidth: 1,
    borderTopColor: C.borderLight,
    paddingTop: Theme.spacing.md,
  },
  stepActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: Theme.spacing.xl,
    gap: Theme.spacing.md,
  },
  stepBackBtn: {
    flex: 1,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.white,
  },
  stepBackText: {
    ...Theme.typography.bodyMd,
    color: C.t2,
  },
  stepNextBtn: {
    flex: 2,
    height: 52,
    backgroundColor: C.navy,
    borderRadius: Theme.radius.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Theme.spacing.sm,
  },
  stepNextText: {
    ...Theme.typography.bodyMd,
    color: Theme.colors.card,
  },
  stepSubmitBtn: {
    backgroundColor: C.success,
  },
  serverErrorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    backgroundColor: C.dangerSoft,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: C.dangerBorder,
  },
  serverErrorText: {
    color: C.danger,
    fontSize: Theme.typography.caption.fontSize,
    flex: 1,
  },
  serverSuccessBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    backgroundColor: C.successSoft,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: C.successBorder,
  },
  serverSuccessText: {
    color: C.success,
    fontSize: Theme.typography.caption.fontSize,
    flex: 1,
  },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(15, 23, 42, 0.6)', justifyContent: 'center', alignItems: 'center', padding: Theme.spacing.md },
  pickerOverlay: { flex: 1, backgroundColor: 'rgba(15, 23, 42, 0.6)', justifyContent: 'center', alignItems: 'center', padding: Theme.spacing.md },
  modalContent: {
    backgroundColor: C.white,
    borderRadius: Theme.radius.xxl,
    width: '90%',
    maxHeight: '90%',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.15)',
    shadowColor: Theme.colors.text,
    shadowOpacity: 0.15,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Theme.spacing.xl,
    paddingTop: Theme.spacing.xl,
    paddingBottom: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  modalTitle: { fontSize: Theme.typography.h3.fontSize, color: C.t1, fontWeight: '700' },
  closeBtn: { width: 36, height: 36, borderRadius: Theme.radius.lg, backgroundColor: Theme.colors.background, alignItems: 'center', justifyContent: 'center' },
  modalBody: { paddingHorizontal: Theme.spacing.xl, paddingBottom: Theme.spacing.lg },
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  sheetCard: {
    backgroundColor: C.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    width: '100%',
    overflow: 'hidden',
    ...Platform.select({
      android: { elevation: 16 },
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.18,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: -4 },
      },
    }),
  },
  sheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: C.border,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 6,
  },
  sheetFooter: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: Theme.spacing.xl,
    paddingTop: Theme.spacing.md,
    borderTopWidth: 1,
    borderTopColor: C.border,
    backgroundColor: C.white,
  },
  sheetFooterBtn: {
    flex: 1,
    minHeight: 46,
    borderRadius: Theme.radius.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: Theme.spacing.md,
    marginBottom: Theme.spacing.xs,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.border,
  },
  sheetTitle: { fontSize: Theme.typography.h4.fontSize, color: C.t1 },
  sheetCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: Theme.radius.lg,
    backgroundColor: C.bg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  studentSheetScroll: { flexShrink: 1 },
  studentSheetContent: { paddingHorizontal: Theme.spacing.xl, paddingBottom: Theme.spacing.lg },
  tableViewBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: Theme.radius.sm,
    backgroundColor: C.primarySoft,
  },
  tableViewBtnText: { ...Theme.typography.caption, color: C.primary },
  selectRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 10,
  },
  selectField: { flex: 1 },
  selectLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: C.t3,
    marginBottom: 6,
    fontWeight: '500',
  },
  selectTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: C.bg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.md,
    height: 44,
    gap: Theme.spacing.sm,
  },
  selectTriggerDisabled: { opacity: 0.5 },
  selectValue: {
    flex: 1,
    fontSize: Theme.typography.body.fontSize,
    color: C.t1,
    fontWeight: '600',
  },
  selectPlaceholder: {
    color: C.t3,
    fontWeight: '400',
  },
  profileSheet: { gap: Theme.spacing.md },
  profileHeaderCardGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    padding: Theme.spacing.xl,
    borderRadius: Theme.radius.xl,
    marginBottom: Theme.spacing.sm,
    backgroundColor: Theme.colors.primary,
  },
  profileAvatarContainer: {
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    borderRadius: 26,
    padding: 2,
  },
  profileAvatarLarge: {
    width: 68,
    height: 68,
    borderRadius: 22,
    backgroundColor: Theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileAvatarText: { color: C.primary, fontSize: Theme.typography.h2.fontSize },
  profileHeaderMeta: { flex: 1, minWidth: 0, gap: Theme.spacing.xs },
  profileName: { fontSize: Theme.typography.h3.fontSize, color: Theme.colors.card, fontWeight: '700' },
  profileSubText: { ...Theme.typography.caption, color: Theme.colors.textSec },
  statusActiveCard: { backgroundColor: 'rgba(16, 185, 129, 0.18)', borderColor: 'rgba(16, 185, 129, 0.3)' },
  statusInactiveCard: { backgroundColor: 'rgba(239, 68, 68, 0.18)', borderColor: 'rgba(239, 68, 68, 0.3)' },
  statusActiveCardText: { color: Theme.colors.success },
  statusInactiveCardText: { color: Theme.colors.error },
  tableContainer: {
    backgroundColor: C.white,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
    borderRadius: Theme.radius.md,
    overflow: 'hidden',
  },
  filterBar: {
    paddingHorizontal: PAGE_PAD,
    paddingVertical: Theme.spacing.md,
    gap: 10,
  },
  filterHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  filterTitle: { fontSize: Theme.typography.h4.fontSize, color: C.t1 },
  filterSubtitle: { ...Theme.typography.caption, color: C.t3 },
  filterBadge: { backgroundColor: C.primarySoft, paddingHorizontal: 10, paddingVertical: Theme.spacing.xs, borderRadius: Theme.radius.xl },
  filterBadgeText: { ...Theme.typography.label, color: C.primary },
  searchInput: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.md,
    height: 44,
    marginBottom: Theme.spacing.xs,
  },
  searchField: { flex: 1, ...Theme.typography.body, color: C.t1, padding: 0 },
  filterGroup: { flexDirection: 'row', gap: Theme.spacing.sm },
  filterGroupStack: { flexDirection: 'column' },
  filterBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: C.bg, borderWidth: 1, borderColor: C.border, paddingHorizontal: Theme.spacing.md, paddingVertical: Theme.spacing.sm, borderRadius: Theme.radius.md },
  filterBtnFullWidth: { width: '100%' },
  filterBtnText: { ...Theme.typography.caption, color: C.t2 },
  exportBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: C.primary, paddingHorizontal: Theme.spacing.md, paddingVertical: Theme.spacing.sm, borderRadius: Theme.radius.md },
  exportBtnText: { ...Theme.typography.caption, color: Theme.colors.card },
  errorBox: { padding: Theme.spacing.md, backgroundColor: C.dangerSoft },
  errorBoxText: { color: C.danger, ...Theme.typography.caption },
  mobileList: { paddingHorizontal: PAGE_PAD, paddingBottom: Theme.spacing.md, gap: 10 },
  loadingContainer: { padding: 40, alignItems: 'center', gap: Theme.spacing.md },
  loadingText: { fontSize: Theme.typography.caption.fontSize, color: C.t3 },
  studentCard: {
    backgroundColor: C.white,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    gap: 10,
  },
  studentCardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  studentCellName: { flexDirection: 'row', alignItems: 'center', gap: Theme.spacing.sm, flex: 1 },
  studentIdentity: { flex: 1 },
  studentIdText: { ...Theme.typography.label, color: C.t4, marginTop: 1 },
  studentMetaGrid: { flexDirection: 'row', gap: Theme.spacing.sm, padding: Theme.spacing.sm, backgroundColor: C.bg, borderRadius: Theme.radius.sm, marginTop: Theme.spacing.xs },
  studentMetaItem: { flex: 1, gap: 1 },
  studentMetaLabel: { fontSize: Theme.typography.label.fontSize, color: C.t4, textTransform: 'uppercase' },
  studentMetaValue: { ...Theme.typography.caption, color: C.t1 },
  studentCardFooter: { flexDirection: 'row', gap: Theme.spacing.sm, marginTop: Theme.spacing.xs },
  cardActionBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Theme.spacing.sm, paddingVertical: 10, borderRadius: Theme.radius.md },
  cardActionPrimary: { backgroundColor: C.primary },
  cardActionPrimaryText: { color: Theme.colors.card, ...Theme.typography.caption },
  cardActionSecondary: { backgroundColor: C.white, borderWidth: 1, borderColor: C.border },
  cardActionSecondaryText: { color: C.primary, ...Theme.typography.caption },
  profileRole: { fontSize: Theme.typography.caption.fontSize, color: Theme.colors.border, fontWeight: '500' },
  profileStatusText: { fontSize: Theme.typography.label.fontSize },
  detailSection: { gap: 10, marginTop: Theme.spacing.xs },
  detailSectionTitle: { fontSize: Theme.typography.caption.fontSize, color: C.t3, fontWeight: '600' },
  detailGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, justifyContent: 'space-between' },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    backgroundColor: Theme.colors.background,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    marginBottom: Theme.spacing.sm,
  },
  detailIconContainer: {
    width: 36,
    height: 36,
    borderRadius: Theme.radius.md,
    backgroundColor: C.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailInfoContainer: {
    flex: 1,
    minWidth: 0,
  },
  detailLabel: { fontSize: Theme.typography.label.fontSize, color: C.t3, fontWeight: '500' },
  detailValue: { fontSize: Theme.typography.body.fontSize, color: C.t1, marginTop: 2, fontWeight: '500' },
  selectorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.sm,
  },
  addBtnSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.xs,
    backgroundColor: C.primarySoft,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: Theme.radius.sm,
  },
  addBtnSmallText: {
    ...Theme.typography.caption,
    color: C.primary,
  },
  selectedClassInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    flex: 1,
  },
  selectedClassIcon: {
    width: 36,
    height: 36,
    borderRadius: Theme.radius.md,
    backgroundColor: C.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectedClassLabel: {
    ...Theme.typography.bodyMd,
    color: C.t1,
  },
  selectedClassSub: {
    ...Theme.typography.caption,
    color: C.t3,
    marginTop: 2,
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.sm,
    alignSelf: 'flex-start',
    marginTop: Theme.spacing.xs,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  statusDotPresent: { backgroundColor: Theme.colors.success },
  statusDotAbsent: { backgroundColor: Theme.colors.error },
  statusActive: {
    backgroundColor: C.successSoft,
    borderColor: C.success,
  },
  statusInactive: {
    backgroundColor: C.errorSoft,
    borderColor: C.error,
  },
  statusText: {
    fontSize: Theme.typography.label.fontSize,
  },
  statusActiveText: {
    color: C.success,
  },
  statusInactiveText: {
    color: C.error,
  },
  emptyState: {
    alignItems: 'center',
    padding: Theme.spacing.xxl,
    backgroundColor: C.white,
  },
  emptyTitle: {
    fontSize: Theme.typography.h4.fontSize,
    color: C.t1,
    marginTop: Theme.spacing.md,
  },
  emptyText: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.t3,
    marginTop: Theme.spacing.xs,
  },
  pickerContent: {
    backgroundColor: C.white,
    borderRadius: Theme.radius.xl,
    width: '90%',
    maxHeight: '80%',
    padding: Theme.spacing.xl,
    gap: Theme.spacing.md,
  },
  pickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    paddingBottom: Theme.spacing.md,
  },
  pickerTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: C.t1,
  },
  pickerList: {
    maxHeight: 400,
  },
  pickerItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.sm,
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: C.bg,
  },
  pickerItemActive: {
    backgroundColor: C.primarySoft,
    borderColor: C.primary,
  },
  pickerItemInfo: {
    flex: 1,
    gap: Theme.spacing.xs,
  },
  pickerItemLabel: {
    ...Theme.typography.body,
    color: C.t1,
  },
  pickerItemLabelActive: {
    color: C.primary,
  },
  pickerItemStats: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
  },
  pickerItemStatText: {
    ...Theme.typography.label,
    color: C.t3,
  },
  grid: {
    gap: Theme.spacing.md,
  },
  formGroup: {
    marginBottom: Theme.spacing.md,
  },
  flexOne: {
    flex: 1,
  },
  selectorContainer: {
    backgroundColor: C.white,
    borderRadius: Theme.radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
  },
  panelTitle: {
    fontSize: Theme.typography.h4.fontSize,
    color: C.t1,
  },
  dropdownTrigger: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.md,
    height: 48,
    marginTop: Theme.spacing.sm,
  },
  placeholderText: {
    ...Theme.typography.body,
    color: C.t3,
  },
  table: {
    minWidth: 600,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: C.bg,
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  headerCell: {
    ...Theme.typography.label,
    color: C.t3,
    textTransform: 'uppercase',
  },
  cellStudent: {
    width: '55%',
  },
  cellRoll: {
    width: '15%',
  },
  cellAdmission: {
    width: '20%',
  },
  cellStatus: {
    width: '20%',
  },
  cellActions: {
    width: '25%',
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    backgroundColor: C.dangerSoft,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: C.dangerBorder,
    marginBottom: Theme.spacing.md,
  },
  errorBannerText: {
    color: C.danger,
    fontSize: Theme.typography.caption.fontSize,
    flex: 1,
  },
  label: {
    ...Theme.typography.body,
    color: C.t1,
    fontWeight: '600',
    marginBottom: Theme.spacing.sm,
  },
  requiredStar: {
    color: C.error,
  },
  input: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.md,
    height: 48,
    backgroundColor: C.white,
    color: C.t1,
    ...Theme.typography.body,
  },
  errorText: {
    color: C.error,
    ...Theme.typography.caption,
    marginTop: Theme.spacing.xs,
  },
  studentName: {
    ...Theme.typography.body,
    color: C.t1,
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    backgroundColor: C.white,
  },
  tableCell: {
    justifyContent: 'center',
  },
  monoText: {
    fontFamily: Platform.select({ ios: 'CourierNewPSMT', android: 'monospace' }),
    fontSize: Theme.typography.caption.fontSize,
    color: C.t1,
  },
  iconBtn: {
    padding: Theme.spacing.sm,
    borderRadius: Theme.radius.sm,
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalSubtitle: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.t3,
    marginTop: 2,
  },
  sectionsRow: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    alignItems: 'center',
  },
  addSectionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Theme.spacing.xs,
    backgroundColor: C.primarySoft,
    paddingHorizontal: Theme.spacing.md,
    height: 48,
    borderRadius: Theme.radius.md,
  },
  addSectionBtnText: {
    ...Theme.typography.body,
    color: C.primary,
  },
  sectionsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Theme.spacing.sm,
    marginTop: 10,
  },
  sectionPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.border,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: Theme.radius.sm,
  },
  sectionPillText: {
    ...Theme.typography.caption,
    color: C.t1,
  },
  hintText: {
    ...Theme.typography.label,
    color: C.t4,
    marginTop: Theme.spacing.sm,
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.xl,
    paddingBottom: Theme.spacing.lg,
  },
  cancelBtn: {
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelBtnText: {
    ...Theme.typography.body,
    color: C.t2,
  },
  saveBtn: {
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
    backgroundColor: C.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveBtnText: {
    ...Theme.typography.body,
    color: Theme.colors.card,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: PAGE_PAD,
    paddingBottom: 100,
  },
  headerBleed: {
    marginHorizontal: -PAGE_PAD,
    marginBottom: Theme.spacing.md,
  },
  sectionBleed: {
    marginHorizontal: -PAGE_PAD,
    borderRadius: 0,
    borderLeftWidth: 0,
    borderRightWidth: 0,
  },
  pagePad: {
    paddingHorizontal: PAGE_PAD,
  },
  content: {
    paddingTop: Theme.spacing.xs,
  },
});