import { StyleSheet , Platform} from 'react-native';
import {Theme, colors} from '../../../theme/tokens';

export const visitorDashboardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.colors.background,
  },
  contentContainer: {
    padding: Theme.spacing.md,
    paddingBottom: 40,
  },
  contentContainerInner: {
    paddingTop: Theme.spacing.md,
  },
  welcomeSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: Theme.spacing.lg,
    marginTop: Theme.spacing.xl,
    backgroundColor: colors.surface,
    padding: Theme.spacing.xl,
    borderRadius: Theme.radius.xl,
    // Shadow
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  welcomeTitle: {
    fontSize: Theme.typography.h3.fontSize,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  welcomeSub: {
    fontSize: Theme.typography.caption.fontSize,
    color: colors.textMuted,
    marginTop: 2,
  },
  dateBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.surface,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  dateText: {
    ...Theme.typography.caption,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.xl,
  },
  title: {
    fontSize: Theme.typography.h2.fontSize,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 10,
  },
  qrBtn: {
    backgroundColor: colors.accentSoft,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.radius.sm,
  },
  qrBtnText: {
    ...Theme.typography.caption,
    color: Theme.colors.card,
    fontWeight: '600',
  },
  refreshBtn: {
    backgroundColor: colors.surface,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  refreshBtnLabel: {
    fontSize: Theme.typography.h4.fontSize,
  },
  errorContainer: {
    backgroundColor: colors.errorSoft,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.md,
  },
  errorText: {
    color: colors.error,
    fontSize: Theme.typography.caption.fontSize,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Theme.spacing.md,
    marginBottom: Theme.spacing.xl,
  },
  statCard: {
    flex: 1,
    minWidth: '45%',
    padding: 14,
    alignItems: 'center',
  },
  statTitle: {
    ...Theme.typography.label,
    fontWeight: '700',
    textTransform: 'uppercase',
    color: colors.textMuted,
    marginBottom: Theme.spacing.sm,
  },
  statValue: {
    ...Theme.typography.h1,
    color: colors.textPrimary,
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: colors.surface,
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.md,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
  },
  tab: {
    flex: 1,
    paddingVertical: Theme.spacing.md,
    alignItems: 'center',
  },
  tabActive: {
    backgroundColor: 'rgba(99, 102, 241, 0.1)',
  },
  tabText: {
    ...Theme.typography.caption,
    fontWeight: '600',
    color: colors.textMuted,
  },
  tabTextActive: {
    color: colors.accent,
  },
  activeFilters: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    marginBottom: Theme.spacing.md,
    padding: 10,
    backgroundColor: colors.surface,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  activeFiltersLabel: {
    ...Theme.typography.caption,
    fontWeight: '600',
    color: colors.textMuted,
  },
  filterTag: {
    backgroundColor: Theme.colors.background,
    paddingHorizontal: 10,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterTagText: {
    ...Theme.typography.label,
    color: colors.textPrimary,
  },
  clearFiltersText: {
    ...Theme.typography.label,
    color: colors.error,
    fontWeight: '600',
  },
  filterBtn: {
    backgroundColor: colors.surface,
    paddingVertical: 10,
    paddingHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    alignSelf: 'flex-start',
    marginBottom: Theme.spacing.md,
  },
  filterBtnText: {
    fontSize: Theme.typography.caption.fontSize,
    color: colors.textMuted,
    fontWeight: '600',
  },
  visitorRow: {
    marginBottom: Theme.spacing.md,
  },
  visitorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
  },
  visitorNo: {
    ...Theme.typography.label,
    fontFamily: Platform.OS === 'ios' ? 'Courier New' : 'monospace',
    backgroundColor: Theme.colors.background,
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: 2,
    borderRadius: Theme.radius.sm,
    color: colors.textMuted,
    borderWidth: 1,
    borderColor: colors.border,
  },
  visitorInfo: {
    flexDirection: 'row',
    marginBottom: Theme.spacing.md,
    gap: Theme.spacing.md,
  },
  visitorName: {
    flex: 1,
  },
  visitorNameText: {
    ...Theme.typography.bodyMd,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 2,
  },
  visitorPhone: {
    ...Theme.typography.caption,
    color: colors.textMuted,
  },
  visitorStudent: {
    flex: 1,
  },
  visitorStudentName: {
    ...Theme.typography.body,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 2,
  },
  visitorClass: {
    ...Theme.typography.caption,
    color: colors.textMuted,
  },
  visitorDetails: {
    marginBottom: Theme.spacing.md,
  },
  visitorPurpose: {
    fontSize: Theme.typography.caption.fontSize,
    color: colors.textPrimary,
    marginBottom: Theme.spacing.xs,
    opacity: 0.8,
  },
  visitorTime: {
    ...Theme.typography.caption,
    color: colors.textMuted,
  },
  visitorActions: {
    marginTop: Theme.spacing.sm,
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  actionBtn: {
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.sm,
    alignItems: 'center',
    flex: 1,
  },
  approveBtn: {
    backgroundColor: 'rgba(21, 128, 61, 0.2)',
  },
  rejectBtn: {
    backgroundColor: 'rgba(185, 28, 28, 0.2)',
  },
  checkoutBtn: {
    backgroundColor: 'rgba(37, 99, 235, 0.2)',
    width: '100%',
  },
  actionBtnText: {
    ...Theme.typography.caption,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.xl,
  },
  badgeText: {
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '700',
  },
  emptyCard: {
    padding: 40,
    alignItems: 'center',
  },
  emptyIcon: {
    fontSize: 48,
    marginBottom: Theme.spacing.md,
    opacity: 0.5,
  },
  emptyTitle: {
    ...Theme.typography.h4,
    color: colors.textPrimary,
    marginBottom: Theme.spacing.xs,
  },
  emptyText: {
    fontSize: Theme.typography.caption.fontSize,
    color: colors.textMuted,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Theme.spacing.xl,
  },
  modalContent: {
    backgroundColor: colors.surface,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.lg,
    width: '100%',
    maxWidth: 400,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterModalContent: {
    backgroundColor: colors.surface,
    borderRadius: Theme.radius.xl,
    width: '100%',
    maxWidth: 400,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalTitle: {
    ...Theme.typography.h3,
    color: colors.textPrimary,
  },
  modalClose: {
    width: 32,
    height: 32,
    borderRadius: Theme.radius.lg,
    backgroundColor: Theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCloseText: {
    fontSize: Theme.typography.h4.fontSize,
    color: colors.textPrimary,
  },
  headerStandard: {
    backgroundColor: Theme.colors.violet,
    paddingHorizontal: Theme.spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    ...Theme.typography.h3,
    color: Theme.colors.card,
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
  },
  refreshIconBtn: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: Theme.radius.lg,
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.xl,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  modalMessage: {
    fontSize: Theme.typography.caption.fontSize,
    color: colors.textMuted,
    textAlign: 'center',
    marginTop: Theme.spacing.md,
  },
  filterBody: {
    padding: Theme.spacing.md,
  },
  filterField: {
    marginBottom: Theme.spacing.md,
  },
  filterLabel: {
    ...Theme.typography.caption,
    fontWeight: '600',
    color: colors.textMuted,
    marginBottom: 6,
  },
  dateBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    backgroundColor: Theme.colors.background,
  },
  filterDateText: {
    ...Theme.typography.body,
    color: colors.textPrimary,
  },
  filterFooter: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    padding: Theme.spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  qrImage: {
    width: 200,
    height: 200,
    resizeMode: 'contain',
    marginVertical: Theme.spacing.md,
  },
  qrCodeContainer: {
    alignItems: 'center',
    marginVertical: Theme.spacing.md,
    backgroundColor: Theme.colors.background,
    padding: 10,
    borderRadius: Theme.radius.md,
  },
  qrUrlContainer: {
    backgroundColor: Theme.colors.background,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    width: '100%',
    marginTop: Theme.spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  qrUrlLabel: {
    ...Theme.typography.label,
    color: colors.textMuted,
    marginBottom: Theme.spacing.xs,
  },
  qrUrlText: {
    ...Theme.typography.caption,
    color: colors.textPrimary,
    fontFamily: Platform.OS === 'ios' ? 'Courier New' : 'monospace',
  },
});
