import { StyleSheet, Platform } from 'react-native';
import {Theme, C, colors} from '../../../theme/tokens';

export const teacherAssignmentsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },
  navHeader: {
    backgroundColor: C.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Theme.spacing.xl,
    paddingBottom: 40,


    ...Platform.select({
      android: { elevation: 12 },
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.2,
        shadowRadius: 12,
      },
    }),
    zIndex: 10,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  navTitle: {
    color: Theme.colors.card,
    fontSize: Theme.typography.h3.fontSize,
    flex: 1,
    textAlign: 'center',
    marginHorizontal: Theme.spacing.md,
  },
  notificationBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  page: { flex: 1, backgroundColor: C.bg },
  pageContent: {},
  header: {
    paddingTop: Theme.spacing.lg,
    paddingBottom: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.xs,
  },
  title: { fontSize: Theme.typography.h1.fontSize, color: C.text, lineHeight: 36, letterSpacing: -0.5 },
  subtitle: { ...Theme.typography.bodyMd, color: C.text2, marginTop: 6, lineHeight: 22 },

  infoBar: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    backgroundColor: C.bgAlt,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: C.border,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.lg,
    gap: Theme.spacing.xl,
  },
  infoItem: { flexDirection: 'row', alignItems: 'center', gap: Theme.spacing.md },
  infoIconBox: {
    width: 36,
    height: 36,
    borderRadius: Theme.radius.md,
    backgroundColor: C.primarySoft,
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoLabel: { ...Theme.typography.label, color: C.text3, textTransform: 'uppercase', letterSpacing: 0.5 },
  infoValue: { ...Theme.typography.body, color: C.text },

  messageBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.xl,
    marginBottom: Theme.spacing.lg,
    borderWidth: 1,
    gap: Theme.spacing.md,
  },

  panel: {
    backgroundColor: C.white,
    borderRadius: Theme.radius.xxl,
    marginBottom: Theme.spacing.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 16,
    elevation: 3,
    overflow: 'hidden',
    borderWidth: Platform.OS === 'ios' ? 1 : 0,
    borderColor: C.borderSoft,
  },
  panelHead: {
    padding: Theme.spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: C.borderSoft,
    backgroundColor: C.white,
  },
  panelTitle: { fontSize: Theme.typography.h3.fontSize, color: C.text, letterSpacing: -0.3 },
  panelSub: { ...Theme.typography.body, color: C.text2, marginTop: Theme.spacing.xs },
  panelBody: { padding: Theme.spacing.xl },

  classGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  classCard: {
    width: '48%',
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.md,
    backgroundColor: C.white,
    marginBottom: Theme.spacing.md,
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
  classCardActive: {
    borderColor: C.primary,
    backgroundColor: '#eff6ff',
    elevation: 0,
    shadowOpacity: 0,
  },
  className: { fontSize: Theme.typography.h4.fontSize, color: C.text },
  classMeta: { fontSize: Theme.typography.caption.fontSize, color: C.text3, marginTop: Theme.spacing.xs },

  sectionWrap: { marginTop: Theme.spacing.md, paddingTop: Theme.spacing.xl, borderTopWidth: 1, borderTopColor: C.borderSoft },
  sectionTitleSmall: {
    fontSize: Theme.typography.h4.fontSize,
    color: C.text,
    marginBottom: Theme.spacing.md,
  },
  sectionList: { flexDirection: 'row', flexWrap: 'wrap', gap: Theme.spacing.md },
  sectionBtn: {
    minWidth: 50,
    height: 50,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.white,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: Theme.spacing.md,
  },
  sectionBtnActive: { borderColor: C.primary, backgroundColor: C.primary },
  sectionBtnText: { color: C.text, fontSize: Theme.typography.bodyMd.fontSize },

  card: {
    borderRadius: Theme.radius.xxl,
    overflow: 'hidden',
    marginBottom: Theme.spacing.xl,
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.borderSoft,
  },
  cardHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Theme.spacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: C.borderSoft,
  },
  cardTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  cardTitle: { fontSize: Theme.typography.h4.fontSize, color: C.text },
  cardSub: { fontSize: Theme.typography.caption.fontSize, color: C.text2, marginTop: Theme.spacing.xs },
  cardBody: { padding: Theme.spacing.xl },

  label: { ...Theme.typography.body, color: C.text, marginBottom: 10, marginLeft: Theme.spacing.xs, opacity: 0.8 },
  picker: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 50,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.md,
    backgroundColor: C.bgAlt,
    marginBottom: Theme.spacing.md,
  },
  input: {
    height: 50,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.md,
    fontSize: Theme.typography.h4.fontSize,
    color: C.text,
    backgroundColor: C.bgAlt,
  },

  currentBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
    backgroundColor: C.successSoft,
    alignSelf: 'flex-start',
    marginBottom: Theme.spacing.xl,
  },
  currentBadgeText: { fontSize: Theme.typography.caption.fontSize, color: C.success },

  noteBox: {
    backgroundColor: '#FFFBEB',
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.xl,
    borderWidth: 1,
    borderColor: '#FEF3C7',
  },
  noteText: { fontSize: Theme.typography.caption.fontSize, color: '#92400E', lineHeight: 20 },

  subjectRow: { marginBottom: Theme.spacing.xl },
  subjectName: { ...Theme.typography.bodyMd, color: C.text, marginBottom: 10, marginLeft: Theme.spacing.xs },

  emptyState: { alignItems: 'center', justifyContent: 'center', paddingVertical: 80, gap: Theme.spacing.md },
  emptyTitle: { color: C.text, fontSize: Theme.typography.h3.fontSize },

  btnPrimary: {
    backgroundColor: C.primary,
    borderRadius: Theme.radius.lg,
    height: 58,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: Theme.spacing.lg,
    flexDirection: 'row',
    gap: Theme.spacing.md,
    shadowColor: C.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 6,
  },
  btnPrimaryText: { color: Theme.colors.card, fontSize: Theme.typography.h4.fontSize, letterSpacing: 0.2 },
  btnOutline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    height: 48,
    paddingHorizontal: Theme.spacing.xl,
    borderRadius: Theme.radius.md,
    borderWidth: 1.5,
    borderColor: C.borderSoft,
    backgroundColor: C.white,
  },
  btnOutlineText: { color: C.text, ...Theme.typography.body },
  btnDisabled: { opacity: 0.5 },

  overlay: { flex: 1, backgroundColor: 'rgba(15, 23, 42, 0.5)', justifyContent: 'flex-end' },
  modal: {
    width: '100%',
    backgroundColor: C.white,
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
    overflow: 'hidden',
    paddingBottom: Platform.OS === 'ios' ? 40 : 20,
  },
  modalHead: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Theme.spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: C.borderSoft,
  },
  modalTitle: { fontSize: Theme.typography.h3.fontSize, color: C.text, flex: 1 },
  modalBody: { padding: Theme.spacing.lg },
  modalFoot: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: Theme.spacing.md,
    padding: Theme.spacing.lg,
    borderTopWidth: 1,
    borderTopColor: C.borderSoft,
  },

  pickerModal: { maxHeight: '85%' },
  pickerScrollView: { maxHeight: 450 },
  pickerOption: {
    padding: Theme.spacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: C.borderSoft,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
  },
  pickerOptionText: { fontSize: Theme.typography.h4.fontSize, color: C.text },
  pickerIcon: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.xl,
    backgroundColor: C.primarySoft,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pickerOptionSub: { fontSize: Theme.typography.caption.fontSize, color: C.text3, marginTop: 2 },
  emptyPickerList: { padding: 60, justifyContent: 'center', alignItems: 'center' },
  emptyPickerText: { fontSize: Theme.typography.h4.fontSize, color: C.text2 },
});
