import { StyleSheet } from 'react-native';
import {Theme, colors} from '../../../theme/tokens';

export const directorBillingStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Theme.colors.background },
  heroCard: {
    shadowColor: Theme.colors.primaryLight,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 8,
    marginBottom: Theme.spacing.xl,
  },
  heroGradient: {
    borderRadius: Theme.radius.xxl,
    padding: Theme.spacing.lg,
    backgroundColor: Theme.colors.primary,
  },
  heroHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 30 },
  heroLabel: { ...Theme.typography.caption, fontWeight: '800', color: 'rgba(255,255,255,0.8)', letterSpacing: 1.5, marginBottom: Theme.spacing.xs, opacity: 0.8 },
  heroPlan: { fontSize: 32, fontWeight: '900', color: Theme.colors.card, letterSpacing: -1 },
  statusBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingVertical: 6, borderRadius: Theme.radius.md, gap: 6 },
  statusText: { ...Theme.typography.caption, fontWeight: '800', letterSpacing: 0.5 },
  heroFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.2)', paddingTop: Theme.spacing.xl },
  validLabel: { fontSize: Theme.typography.caption.fontSize, marginBottom: Theme.spacing.xs, opacity: 0.9 },
  validDate: { fontSize: Theme.typography.h3.fontSize, fontWeight: '800' },
  upgradeBtn: { backgroundColor: Theme.colors.background, flexDirection: 'row', alignItems: 'center', paddingHorizontal: Theme.spacing.md, paddingVertical: 10, borderRadius: Theme.radius.md, gap: Theme.spacing.sm },
  upgradeText: { color: Theme.colors.primaryLight, ...Theme.typography.body, fontWeight: '800' },
  content: { flex: 1, paddingHorizontal: Theme.spacing.xl },
  sectionTitle: { fontSize: Theme.typography.h3.fontSize, fontWeight: '800', color: Theme.colors.text, marginBottom: Theme.spacing.md, marginTop: Theme.spacing.lg, letterSpacing: -0.5 },
  card: { backgroundColor: Theme.colors.card, borderRadius: Theme.radius.xl, padding: Theme.spacing.md, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.03, shadowRadius: 10, elevation: 2, borderWidth: 1, borderColor: Theme.colors.background },
  methodRow: { flexDirection: 'row', alignItems: 'center' },
  methodIcon: { width: 48, height: 48, borderRadius: Theme.radius.lg, backgroundColor: '#eff6ff', justifyContent: 'center', alignItems: 'center', marginRight: Theme.spacing.md },
  methodDetails: { flex: 1 },
  methodName: { fontSize: Theme.typography.h4.fontSize, fontWeight: '800', color: Theme.colors.text, marginBottom: 2 },
  methodSub: { fontSize: Theme.typography.caption.fontSize, color: Theme.colors.textSec, fontWeight: '500' },
  invoiceRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 14 },
  invoiceMain: { flex: 1, flexDirection: 'row', alignItems: 'center' },
  borderTop: { borderTopWidth: 1, borderTopColor: Theme.colors.background },
  invoiceIcon: { width: 40, height: 40, borderRadius: Theme.radius.md, backgroundColor: '#eff6ff', justifyContent: 'center', alignItems: 'center', marginRight: Theme.spacing.md },
  invoiceName: { ...Theme.typography.bodyMd, fontWeight: '700', color: Theme.colors.text, marginBottom: 2 },
  invoiceDate: { fontSize: Theme.typography.caption.fontSize, color: Theme.colors.textSec, fontWeight: '500' },
  invoiceAmt: { fontSize: Theme.typography.h4.fontSize, fontWeight: '800', color: Theme.colors.primary, marginRight: Theme.spacing.sm },
  viewBtn: { width: 36, height: 36, borderRadius: Theme.radius.md, backgroundColor: '#eff6ff', justifyContent: 'center', alignItems: 'center', marginRight: Theme.spacing.sm },
  downloadBtn: { width: 36, height: 36, borderRadius: Theme.radius.md, backgroundColor: Theme.colors.background, justifyContent: 'center', alignItems: 'center' },
  emptyState: { paddingVertical: Theme.spacing.xl, alignItems: 'center' },
  emptyStateText: { ...Theme.typography.body, color: Theme.colors.textMuted, fontWeight: '500' },
  rowStatusBadge: {
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: 2,
    borderRadius: Theme.radius.sm,
    alignSelf: 'flex-start',
  },
  rowStatusText: {
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  alertBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#fffbeb',
    borderColor: Theme.colors.amberLight,
    borderWidth: 1,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.xl,
    gap: Theme.spacing.md,
  },
  alertTitle: {
    ...Theme.typography.body,
    fontWeight: '800',
    color: '#92400e',
    marginBottom: 2,
  },
  alertMessage: {
    ...Theme.typography.caption,
    color: '#b45309',
    fontWeight: '500',
    lineHeight: 16,
  },
  autoRenewCard: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.xl,
    borderWidth: 1,
    borderColor: Theme.colors.successBg,
  },
  autoRenewHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Theme.spacing.md,
    marginBottom: 14,
  },
  autoRenewIcon: {
    width: 36,
    height: 36,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.successBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  autoRenewTitle: {
    fontSize: Theme.typography.bodyMd.fontSize,
    color: Theme.colors.text,
    marginBottom: Theme.spacing.xs,
  },
  autoRenewSub: {
    ...Theme.typography.caption,
    color: Theme.colors.textSec,
    lineHeight: 18,
  },
  disableAutoRenewBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Theme.spacing.sm,
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.errorBg,
    backgroundColor: '#fff5f5',
  },
  disableAutoRenewText: {
    color: Theme.colors.error,
    fontSize: Theme.typography.body.fontSize,
  },
  receiptModal: {
    flex: 1,
    backgroundColor: Theme.colors.background,
  },
  receiptModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Theme.spacing.xl,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.background,
    backgroundColor: Theme.colors.card,
  },
  receiptModalTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: Theme.colors.text,
  },
  receiptModalSub: {
    ...Theme.typography.caption,
    color: Theme.colors.textSec,
    marginTop: 2,
  },
  receiptCloseBtn: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiptWebView: {
    flex: 1,
    backgroundColor: Theme.colors.card,
  },
  receiptModalFooter: {
    padding: Theme.spacing.md,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.background,
    backgroundColor: Theme.colors.card,
  },
  receiptDownloadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Theme.spacing.sm,
    backgroundColor: Theme.colors.primary,
    borderRadius: Theme.radius.md,
    paddingVertical: 14,
  },
  receiptDownloadText: {
    color: Theme.colors.card,
    fontSize: Theme.typography.bodyMd.fontSize,
  },
});
