import { StyleSheet } from 'react-native';
import {Theme, colors} from '../../../theme/tokens';

export const student360Styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: Theme.colors.background },
  scrollContent: { flexGrow: 1 },
  pageBody: { paddingTop: 14 },
  searchCard: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    padding: Theme.spacing.md,
  },
  searchTitle: { fontSize: Theme.typography.h3.fontSize, color: Theme.colors.text },
  searchSub: {
    ...Theme.typography.body,
    color: Theme.colors.textMuted,
    marginTop: Theme.spacing.xs,
    marginBottom: Theme.spacing.md,
  },
  searchInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.background,
    paddingHorizontal: Theme.spacing.md,
    height: 48,
  },
  searchInput: {
    flex: 1,
    ...Theme.typography.bodyMd,
    color: Theme.colors.text,
    paddingVertical: 0,
  },
  searchLoading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    marginTop: Theme.spacing.md,
  },
  searchLoadingText: { color: Theme.colors.textMuted },
  searchError: { color: Theme.colors.error, marginTop: Theme.spacing.sm },
  emptySearchText: { color: Theme.colors.textMuted, marginTop: Theme.spacing.md, textAlign: 'center' },
  resultRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    paddingVertical: Theme.spacing.md,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.border,
    marginTop: Theme.spacing.xs,
  },
  resultCopy: { flex: 1 },
  resultName: { color: Theme.colors.text, fontSize: Theme.typography.bodyMd.fontSize },
  resultMeta: { ...Theme.typography.caption, color: Theme.colors.textMuted, marginTop: 2 },
  profileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
  },
  profileInfo: { flex: 1, marginLeft: Theme.spacing.md, marginRight: Theme.spacing.sm },
  profileName: { fontSize: Theme.typography.h3.fontSize, color: Theme.colors.text },
  profileMeta: { ...Theme.typography.caption, color: Theme.colors.textMuted, marginTop: 2 },
  changeBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.background,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  changeBtnText: { ...Theme.typography.caption, color: Theme.colors.primary, marginTop: 2 },
  tabsContainer: { gap: Theme.spacing.sm, paddingBottom: Theme.spacing.md },
  tabPill: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.radius.full,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    backgroundColor: Theme.colors.card,
    marginRight: Theme.spacing.sm,
  },
  tabPillActive: { backgroundColor: Theme.colors.primary, borderColor: Theme.colors.primary },
  tabPillText: { ...Theme.typography.caption, color: Theme.colors.textMuted, marginLeft: Theme.spacing.xs },
  tabPillTextActive: { color: Theme.colors.card },
  contentCard: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.lg,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: Theme.spacing.md,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
  },
  infoLabel: { ...Theme.typography.caption, color: Theme.colors.textMuted, flex: 1 },
  infoValue: { ...Theme.typography.body, color: Theme.colors.text, flex: 1.2, textAlign: 'right' },
  historyRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
  },
  historyDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Theme.colors.primary,
    marginTop: 6,
    marginRight: 10,
  },
  historyTitle: { color: Theme.colors.text },
  historySub: { ...Theme.typography.caption, color: Theme.colors.textMuted, marginTop: 2 },
  historyRemarks: { ...Theme.typography.caption, color: Theme.colors.text, marginTop: Theme.spacing.xs },
  contactActions: { flexDirection: 'row', gap: 10, marginTop: Theme.spacing.md },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.md,
  },
  actionBtnText: { color: Theme.colors.card, fontSize: Theme.typography.caption.fontSize },
  loadingPanel: { alignItems: 'center', paddingVertical: 28, gap: 10 },
  loadingText: { color: Theme.colors.textMuted },
  emptyPanel: { alignItems: 'center', paddingVertical: 28, gap: Theme.spacing.sm },
  emptyPanelTitle: { color: Theme.colors.text, fontSize: Theme.typography.h4.fontSize },
  emptyPanelText: { ...Theme.typography.body, color: Theme.colors.textMuted, textAlign: 'center' },
});
