import { StyleSheet, Platform } from 'react-native';
import {Theme, colors} from '../../../theme/tokens';

export const vitalScanStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.colors.background,
  },
  scrollView: {
    flex: 1,
  },
  contentContainer: {
    paddingBottom: 40,
  },
  topActionsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: Theme.spacing.sm,
    marginBottom: Theme.spacing.xl,
    marginTop: Theme.spacing.md,
  },
  toast: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 60 : 40,
    right: 16,
    left: 16,
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.md,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    borderLeftWidth: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
    zIndex: 1000,
  },
  toastIcon: {
    fontSize: Theme.typography.h3.fontSize,
  },
  toastContent: {
    flex: 1,
  },
  toastTitle: {
    fontWeight: '700',
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.text,
  },
  toastMessage: {
    ...Theme.typography.caption,
    color: Theme.colors.textSec,
    marginTop: 2,
  },
  newBtn: {
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.sm,
    backgroundColor: Theme.colors.primary,
    borderRadius: Theme.radius.md,
  },
  newBtnText: {
    ...Theme.typography.caption,
    color: Theme.colors.card,
    fontWeight: '700',
  },
  feverBtn: {
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.sm,
    backgroundColor: Theme.colors.error,
    borderRadius: Theme.radius.md,
  },
  feverBtnText: {
    ...Theme.typography.caption,
    color: Theme.colors.card,
    fontWeight: '700',
  },
  skinBtn: {
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.sm,
    backgroundColor: Theme.colors.violet,
    borderRadius: Theme.radius.md,
  },
  skinBtnText: {
    ...Theme.typography.caption,
    color: Theme.colors.card,
    fontWeight: '700',
  },
  card: {
    marginBottom: Theme.spacing.xl,
    marginHorizontal: 0,
    borderRadius: Theme.radius.xxl,
    overflow: 'hidden',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    padding: 14,
    backgroundColor: '#f7f9fc',
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
  },
  cardHeaderIcon: {
    ...Theme.typography.body,
  },
  cardHeaderTitle: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '700',
    color: Theme.colors.text,
  },
  cardHeaderBadge: {
    marginLeft: 'auto',
    ...Theme.typography.label,
    color: Theme.colors.textMuted,
    fontWeight: '500',
  },
  cardBody: {
    padding: Theme.spacing.md,
  },
  label: {
    ...Theme.typography.caption,
    fontWeight: '600',
    color: Theme.colors.textSec,
    marginBottom: 6,
  },
  input: {
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    ...Theme.typography.body,
    color: Theme.colors.text,
    backgroundColor: Theme.colors.background,
  },
  textArea: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  pillContainer: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
  },
  pill: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    backgroundColor: Theme.colors.background,
    alignItems: 'center',
  },
  pillActive: {
    borderColor: Theme.colors.primary,
    backgroundColor: Theme.colors.primary + '10',
  },
  pillText: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '700',
    color: Theme.colors.textSec,
  },
  pillTextActive: {
    color: Theme.colors.primary,
  },
  camFrame: {
    width: '100%',
    aspectRatio: 4 / 3,
    backgroundColor: Theme.colors.text,
    borderRadius: Theme.radius.md,
    overflow: 'hidden',
    marginBottom: Theme.spacing.md,
  },
  previewImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  placeholderFrame: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeholderIcon: {
    fontSize: 32,
    opacity: 0.4,
    marginBottom: Theme.spacing.sm,
  },
  placeholderText: {
    ...Theme.typography.caption,
    fontWeight: '600',
    color: Theme.colors.textMuted,
  },
  thumbContainer: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
    marginBottom: Theme.spacing.md,
  },
  thumb: {
    width: 60,
    height: 60,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: Theme.colors.primary,
    overflow: 'hidden',
    position: 'relative',
  },
  thumbImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  thumbRemove: {
    position: 'absolute',
    top: -5,
    right: -5,
    width: 17,
    height: 17,
    backgroundColor: Theme.colors.error,
    borderRadius: Theme.radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  thumbRemoveText: {
    color: Theme.colors.card,
    fontSize: 8,
    fontWeight: '700',
  },
  thumbSlot: {
    width: 60,
    height: 60,
    borderRadius: 9,
    borderWidth: 1.5,
    borderColor: Theme.colors.textSec,
    borderStyle: 'dashed',
    backgroundColor: '#f0f2f7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  thumbSlotNum: {
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '700',
    color: Theme.colors.textMuted,
  },
  sourceRow: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
    marginBottom: Theme.spacing.md,
  },
  sourceBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: Theme.radius.sm,
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    backgroundColor: Theme.colors.background,
    alignItems: 'center',
  },
  sourceBtnText: {
    ...Theme.typography.caption,
    fontWeight: '600',
    color: Theme.colors.textSec,
  },
  runBtn: {
    backgroundColor: Theme.colors.primary,
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: Theme.spacing.sm,
  },
  runBtnText: {
    ...Theme.typography.body,
    color: Theme.colors.card,
    fontWeight: '700',
  },
  resultsCard: {
    marginBottom: Theme.spacing.xl,
    marginHorizontal: 0,
    borderRadius: Theme.radius.xxl,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  resultBadge: {
    marginLeft: 'auto',
    paddingHorizontal: 10,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.xl,
  },
  resultBadgeGood: {
    backgroundColor: '#dcfce7',
  },
  resultBadgeBad: {
    backgroundColor: Theme.colors.redLight,
  },
  resultBadgeText: {
    ...Theme.typography.label,
    fontWeight: '700',
  },
  resultBadgeTextGood: {
    color: '#166534',
  },
  resultBadgeTextBad: {
    color: '#991b1b',
  },
  scanningContainer: {
    alignItems: 'center',
    padding: Theme.spacing.xl,
    gap: Theme.spacing.md,
  },
  scanBox: {
    width: '100%',
    aspectRatio: 4 / 3,
    borderRadius: Theme.radius.lg,
    overflow: 'hidden',
    borderWidth: 3,
    borderColor: Theme.colors.primary,
    position: 'relative',
  },
  scanLine: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: Theme.colors.primary,
    zIndex: 10,
    shadowColor: Theme.colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
  },
  scanImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
    opacity: 0.5,
  },
  scanningText: {
    ...Theme.typography.caption,
    fontWeight: '700',
    color: Theme.colors.primary,
    letterSpacing: 2,
  },
  tagRow: {
    flexDirection: 'row',
    gap: 6,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  tag: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.sm,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  tagText: {
    fontSize: Theme.typography.label.fontSize,
    color: Theme.colors.textMuted,
  },
  resultContainer: {
    overflow: 'hidden',
  },
  resultTopBar: {
    height: 5,
  },
  resultTopBarGood: {
    backgroundColor: '#22C55E',
  },
  resultTopBarBad: {
    backgroundColor: Theme.colors.error,
  },
  resultBody: {
    padding: Theme.spacing.xl,
  },
  patientCard: {
    backgroundColor: '#f0f2f7',
    borderWidth: 1,
    borderColor: Theme.colors.blueLight,
    borderRadius: Theme.radius.md,
    padding: 14,
    marginBottom: 14,
  },
  patientLabel: {
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '800',
    color: Theme.colors.textMuted,
    letterSpacing: 1,
    marginBottom: Theme.spacing.xs,
  },
  patientName: {
    fontSize: Theme.typography.h3.fontSize,
    fontWeight: '800',
    color: Theme.colors.text,
  },
  patientNote: {
    ...Theme.typography.caption,
    color: Theme.colors.textSec,
    marginTop: Theme.spacing.xs,
  },
  metaRow: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
    marginBottom: 14,
  },
  metaItem: {
    flex: 1,
    backgroundColor: '#f0f2f7',
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    padding: 10,
  },
  metaKey: {
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '700',
    color: Theme.colors.textMuted,
    letterSpacing: 1,
    marginBottom: 3,
  },
  metaVal: {
    ...Theme.typography.caption,
    fontWeight: '700',
    color: Theme.colors.text,
  },
  findingsLabel: {
    ...Theme.typography.label,
    fontWeight: '800',
    color: Theme.colors.textSec,
    letterSpacing: 0.8,
    marginBottom: Theme.spacing.sm,
  },
  findingsText: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.cardAlt,
    lineHeight: 20,
    marginBottom: 14,
  },
  recCard: {
    padding: 14,
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.md,
  },
  recCardGood: {
    backgroundColor: '#f0fdf4',
    borderLeftWidth: 5,
    borderLeftColor: '#22C55E',
  },
  recCardBad: {
    backgroundColor: '#fff1f2',
    borderLeftWidth: 5,
    borderLeftColor: Theme.colors.error,
  },
  recLabel: {
    ...Theme.typography.label,
    fontWeight: '800',
    letterSpacing: 0.8,
    marginBottom: Theme.spacing.sm,
  },
  recLabelGood: {
    color: '#166534',
  },
  recLabelBad: {
    color: '#991b1b',
  },
  recText: {
    fontSize: Theme.typography.caption.fontSize,
    fontStyle: 'italic',
    fontWeight: '500',
    color: Theme.colors.text,
    lineHeight: 20,
  },
  clearBtn: {
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    borderWidth: 1.5,
    borderColor: Theme.colors.textSec,
    borderStyle: 'dashed',
    backgroundColor: Theme.colors.background,
    alignItems: 'center',
  },
  clearBtnText: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '700',
    color: Theme.colors.textSec,
  },
  emptyContainer: {
    alignItems: 'center',
    padding: 60,
    gap: 10,
  },
  emptyIcon: {
    fontSize: 44,
    opacity: 0.35,
  },
  emptyTitle: {
    ...Theme.typography.body,
    fontWeight: '700',
    color: Theme.colors.textSec,
  },
  emptyText: {
    ...Theme.typography.caption,
    color: Theme.colors.textMuted,
    textAlign: 'center',
  },
  cameraContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#000',
    zIndex: 1000,
  },
  camera: {
    flex: 1,
  },
  cameraOverlay: {
    position: 'absolute',
    bottom: 30,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  cameraStep: {
    position: 'absolute',
    top: -80,
    backgroundColor: Theme.colors.primary,
    color: Theme.colors.card,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 6,
    borderRadius: Theme.radius.sm,
    ...Theme.typography.caption,
    fontWeight: '700',
  },
  cameraControls: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    alignItems: 'center',
  },
  cameraDoneBtn: {
    backgroundColor: 'rgba(34,197,94,0.9)',
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 10,
    borderRadius: Theme.radius.xxl,
  },
  cameraDoneText: {
    ...Theme.typography.caption,
    color: Theme.colors.card,
    fontWeight: '700',
  },
  cameraCaptureBtn: {
    width: 60,
    height: 60,
    borderRadius: Theme.radius.xxxl,
    backgroundColor: Theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraCaptureText: {
    fontSize: Theme.typography.h2.fontSize,
  },
  cameraCloseBtn: {
    position: 'absolute',
    top: 50,
    right: 20,
    width: 40,
    height: 40,
    borderRadius: Theme.radius.xl,
    backgroundColor: 'rgba(0,0,0,0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraCloseText: {
    color: Theme.colors.card,
    ...Theme.typography.h3,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Theme.spacing.md,
  },
  modalContent: {
    backgroundColor: Theme.colors.background,
    borderRadius: 22,
    padding: Theme.spacing.lg,
    width: '100%',
    maxWidth: 400,
  },
  modalClose: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 30,
    height: 30,
    borderRadius: Theme.radius.sm,
    backgroundColor: '#f0f2f7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCloseText: {
    ...Theme.typography.body,
    color: Theme.colors.textSec,
  },
  modalIcon: {
    fontSize: Theme.typography.h1.fontSize,
    marginBottom: Theme.spacing.sm,
  },
  modalTitle: {
    fontSize: Theme.typography.h3.fontSize,
    fontWeight: '800',
    color: Theme.colors.text,
    marginBottom: Theme.spacing.xs,
  },
  modalSubtitle: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textSec,
    marginBottom: Theme.spacing.xl,
  },
  tempRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: Theme.spacing.md,
  },
  tempInput: {
    flex: 1,
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    ...Theme.typography.body,
    backgroundColor: Theme.colors.background,
  },
  checkBtn: {
    paddingHorizontal: Theme.spacing.xl,
    paddingVertical: Theme.spacing.md,
    backgroundColor: Theme.colors.primary,
    borderRadius: Theme.radius.md,
  },
  checkBtnText: {
    ...Theme.typography.body,
    color: Theme.colors.card,
    fontWeight: '600',
  },
  feverResult: {
    padding: 14,
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.md,
    position: 'relative',
  },
  feverResultBorder: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 5,
    borderTopLeftRadius: 12,
  },
  feverStatus: {
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '700',
    letterSpacing: 1.5,
    marginBottom: Theme.spacing.xs,
  },
  feverTemp: {
    ...Theme.typography.h1,
    color: Theme.colors.text,
    marginBottom: Theme.spacing.sm,
  },
  feverRec: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textSec,
    fontWeight: '500',
  },
  legend: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: Theme.spacing.sm,
  },
  legendItem: {
    flex: 1,
    alignItems: 'center',
    gap: 3,
  },
  legendDot: {
    width: '100%',
    height: 5,
    borderRadius: 3,
  },
  legendLabel: {
    fontSize: 8,
    color: Theme.colors.textMuted,
    textAlign: 'center',
  },
});
