import { StyleSheet, Platform } from 'react-native';
import {Theme, colors} from '../../../theme/tokens';

export const registrationStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.colors.background,
  },
  headerStandard: {
    backgroundColor: Theme.colors.primary,
    paddingHorizontal: Theme.spacing.xl,
    paddingBottom: 30,
    ...Platform.select({
      android: { elevation: 10 },
      ios: {},
    }),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: Theme.spacing.md,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.xl,
    backgroundColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: 'center',
  },
  heroTitle: {
    color: Theme.colors.card,
    ...Theme.typography.h3,
  },
  heroContent: {
    marginTop: Theme.spacing.lg,
  },
  heroGreeting: {
    color: Theme.colors.card,
    ...Theme.typography.h1,
    letterSpacing: -0.5,
  },
  heroSubtext: {
    color: 'rgba(255,255,255,0.7)',
    ...Theme.typography.body,
    marginTop: Theme.spacing.xs,
  },
  contentContainer: {
    paddingBottom: 40,
  },
  errorBox: {
    backgroundColor: Theme.colors.redLight,
    padding: Theme.spacing.md,
    marginHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.md,
    marginTop: Theme.spacing.md,
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  errorText: {
    color: '#b91c1c',
    fontSize: Theme.typography.caption.fontSize,
  },
  successBox: {
    backgroundColor: Theme.colors.greenLight,
    padding: Theme.spacing.md,
    marginHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.md,
    marginTop: Theme.spacing.md,
    borderWidth: 1,
    borderColor: '#a7f3d0',
  },
  successText: {
    color: '#065f46',
    fontSize: Theme.typography.caption.fontSize,
  },
  stepperContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
        marginBottom: Theme.spacing.xl,
    marginHorizontal: Theme.spacing.xl,
    padding: Theme.spacing.xl,
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.xxl,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
  },
  stepItem: {
    alignItems: 'center',
    flex: 1,
  },
  stepCircle: {
    width: 28,
    height: 28,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepCompleted: {
    backgroundColor: Theme.colors.success,
  },
  stepActive: {
    backgroundColor: Theme.colors.primary,
  },
  stepNumber: {
    color: Theme.colors.textSec,
    ...Theme.typography.label,
  },
  stepNumberActive: {
    color: Theme.colors.card,
  },
  stepLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: Theme.colors.textSec,
    marginTop: 6,
    textAlign: 'center',
  },
  stepLabelActive: {
    color: Theme.colors.primary,
  },
  stepLabelCompleted: {
    color: Theme.colors.success,
  },
  formCard: {
    padding: Theme.spacing.lg,
    marginBottom: Theme.spacing.xl,
    marginHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.xxl,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: Theme.spacing.md,
    paddingBottom: Theme.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.background,
  },
  sectionTitle: {
    fontSize: Theme.typography.h4.fontSize,
    color: Theme.colors.primary,
  },
  formGroup: {
    marginBottom: Theme.spacing.xl,
  },
  formLabel: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textSec,
    marginBottom: Theme.spacing.sm,
  },
  requiredStar: {
    color: Theme.colors.error,
  },
  fieldHint: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textSec,
    marginBottom: Theme.spacing.sm,
  },
  input: {
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    ...Theme.typography.body,
    backgroundColor: Theme.colors.background,
    color: Theme.colors.text,
  },
  inputError: {
    borderColor: Theme.colors.error,
  },
  disabledInput: {
    backgroundColor: Theme.colors.background,
    color: Theme.colors.textMuted,
  },
  sectionInput: {
    textTransform: 'uppercase',
  },
  genderContainer: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
  },
  genderBtn: {
    flex: 1,
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    alignItems: 'center',
    backgroundColor: Theme.colors.background,
  },
  genderBtnActive: {
    backgroundColor: Theme.colors.primary,
    borderColor: Theme.colors.primary,
  },
  genderText: {
    color: Theme.colors.textSec,
    ...Theme.typography.body,
  },
  genderTextActive: {
    color: Theme.colors.card,
  },
  dateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    backgroundColor: Theme.colors.background,
  },
  dateText: {
    ...Theme.typography.body,
    color: Theme.colors.text,
  },
  chipContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  chip: {
    paddingVertical: 10,
    paddingHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.xl,
    backgroundColor: Theme.colors.background,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  chipActive: {
    backgroundColor: Theme.colors.primary,
    borderColor: Theme.colors.primary,
  },
  chipText: {
    ...Theme.typography.body,
    color: Theme.colors.textSec,
  },
  chipTextActive: {
    color: Theme.colors.card,
  },
  fieldError: {
    ...Theme.typography.label,
    color: Theme.colors.error,
    marginTop: Theme.spacing.xs,
  },
  // NEW: Request Badge styles
  requestBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: Theme.colors.error,
    borderRadius: Theme.radius.md,
    minWidth: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Theme.spacing.xs,
  },
  requestBadgeText: {
    color: Theme.colors.card,
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '800',
  },
  passwordStrength: {
    marginTop: 10,
    padding: Theme.spacing.md,
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  passwordRule: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    marginBottom: Theme.spacing.xs,
  },
  passwordRuleDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#CBD5E1',
  },
  passwordRuleText: {
    ...Theme.typography.label,
    color: Theme.colors.textSec,
  },
  passwordRuleTextValid: {
    color: Theme.colors.success,
  },
  passwordContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'relative',
  },
  passwordInput: {
    flex: 1,
    paddingRight: 45,
  },
  eyeButton: {
    position: 'absolute',
    right: 12,
    padding: Theme.spacing.sm,
  },
  photoZone: {
    borderWidth: 2,
    borderColor: Theme.colors.border,
    borderStyle: 'dashed',
    borderRadius: Theme.radius.xxl,
    padding: 30,
    alignItems: 'center',
    backgroundColor: Theme.colors.background,
  },
  photoPreview: {
    width: 160,
    height: 160,
    borderRadius: 80,
    resizeMode: 'cover',
  },
  photoPlaceholder: {
    alignItems: 'center',
  },
  photoText: {
    ...Theme.typography.bodyMd,
    color: Theme.colors.primary,
    marginTop: Theme.spacing.md,
  },
  photoSubtext: {
    ...Theme.typography.caption,
    color: Theme.colors.textMuted,
    marginTop: Theme.spacing.xs,
  },
  previewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    marginBottom: Theme.spacing.xl,
    padding: Theme.spacing.md,
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.xxl,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  previewPhoto: {
    width: 70,
    height: 70,
    borderRadius: 35,
    resizeMode: 'cover',
  },
  previewPhotoPlaceholder: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: Theme.colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewPhotoText: {
    fontSize: Theme.typography.label.fontSize,
    color: Theme.colors.textSec,
  },
  previewName: {
    fontSize: Theme.typography.h3.fontSize,
    color: Theme.colors.primary,
  },
  previewMeta: {
    ...Theme.typography.caption,
    color: Theme.colors.textSec,
    marginTop: 2,
  },
  previewBadge: {
    marginTop: 6,
    backgroundColor: '#DCFCE7',
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: Theme.radius.md,
    alignSelf: 'flex-start',
  },
  previewBadgeText: {
    fontSize: Theme.typography.label.fontSize,
    color: '#166534',
    textTransform: 'uppercase',
  },
  previewCard: {
    marginBottom: Theme.spacing.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.xxl,
    overflow: 'hidden',
    backgroundColor: Theme.colors.card,
  },
  previewCardHeader: {
    padding: Theme.spacing.md,
    backgroundColor: Theme.colors.background,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
  },
  previewCardTitle: {
    ...Theme.typography.caption,
    color: Theme.colors.primary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  previewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  previewField: {
    width: '50%',
    padding: Theme.spacing.md,
    borderBottomWidth: 0.5,
    borderBottomColor: Theme.colors.background,
  },
  previewFieldLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: Theme.colors.textMuted,
    textTransform: 'uppercase',
    marginBottom: Theme.spacing.xs,
  },
  previewFieldValue: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.text,
  },
  previewFooter: {
    marginTop: 10,
    padding: Theme.spacing.md,
    backgroundColor: '#F0FDF4',
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: '#DCFCE7',
  },
  previewFooterText: {
    ...Theme.typography.caption,
    color: '#166534',
    textAlign: 'center',
  },
  navButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: Theme.spacing.lg,
    gap: Theme.spacing.md,
  },
  navBtn: {
    flex: 1,
    height: 50,
    backgroundColor: Theme.colors.primary,
  },
  footer: {
    marginTop: Theme.spacing.md,
    padding: Theme.spacing.md,
    marginHorizontal: Theme.spacing.md,
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.xxl,
    flexDirection: 'row',
    justifyContent: 'space-between',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  footerText: {
    ...Theme.typography.label,
    color: Theme.colors.textMuted,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Theme.spacing.lg,
  },
  modalContent: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.xxl,
    padding: 30,
    width: '100%',
    maxWidth: 400,
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: Theme.colors.primary,
    marginBottom: Theme.spacing.md,
  },
  modalMessage: {
    ...Theme.typography.body,
    color: Theme.colors.textSec,
    textAlign: 'center',
    marginBottom: Theme.spacing.xl,
    lineHeight: 20,
  },
  rollNumberDisplay: {
    backgroundColor: '#F0F9FF',
    padding: Theme.spacing.lg,
    borderRadius: Theme.radius.xxl,
    alignItems: 'center',
    marginBottom: Theme.spacing.xl,
    width: '100%',
    borderWidth: 1,
    borderColor: '#BAE6FD',
  },
  rollNumberLabel: {
    ...Theme.typography.caption,
    color: '#0369A1',
    marginBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  rollNumberValue: {
    fontSize: 36,
    color: '#0284C7',
    letterSpacing: 2,
  },
  modalNote: {
    ...Theme.typography.caption,
    color: Theme.colors.textMuted,
    textAlign: 'center',
    marginBottom: Theme.spacing.lg,
  },
});
