import { StyleSheet } from 'react-native';
import {Theme, C, colors} from '../../../theme/tokens';

export const questionPapersStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.colors.background,
  },
  pageBody: {},
  toolbarCard: {
    backgroundColor: C.colors.card,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.colors.border,
  },
  listContainer: {
    flex: 1,
  },
  searchSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.colors.card,
    borderRadius: Theme.radius.md,
    height: 50,
    paddingHorizontal: Theme.spacing.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    ...C.shadow.sm,
  },
  searchInput: {
    flex: 1,
    ...Theme.typography.bodyMd,
    color: C.colors.primary,
    marginLeft: Theme.spacing.sm,
    paddingVertical: 0,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    backgroundColor: C.colors.card,
    height: 50,
    paddingHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    ...C.shadow.sm,
  },
  filterButtonActive: {
    backgroundColor: C.colors.primary,
    borderColor: C.colors.primary,
  },
  filterButtonText: {
    ...Theme.typography.bodyMd,
    fontWeight: '600',
    color: C.colors.textSec,
  },
  filterButtonTextActive: {
    color: C.colors.card,
  },
  filterDot: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: C.colors.error,
    borderWidth: 2,
    borderColor: C.colors.card,
  },
  examTypeRow: {
    marginTop: 14,
  },
  examTypeChip: {
    paddingHorizontal: 14,
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.radius.xl,
    backgroundColor: C.colors.background,
    marginRight: Theme.spacing.sm,
    borderWidth: 1,
    borderColor: C.colors.border,
  },
  examTypeChipActive: {
    backgroundColor: C.colors.blueLight,
    borderColor: C.colors.blue,
  },
  examTypeChipText: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '600',
    color: C.colors.textSec,
  },
  examTypeChipTextActive: {
    color: C.colors.blue,
  },
  activeFilters: {
    marginTop: Theme.spacing.md,
    marginBottom: Theme.spacing.xs,
  },
  activeFiltersContainer: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
    paddingRight: Theme.spacing.md,
    alignItems: 'center',
  },
  activeFilterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: C.colors.blueLight,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.radius.xl,
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  activeFilterText: {
    ...Theme.typography.caption,
    color: C.colors.primary,
    fontWeight: '600',
  },
  clearAllText: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.colors.error,
    fontWeight: '600',
    marginLeft: Theme.spacing.sm,
  },
  statsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.colors.card,
    marginTop: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.lg,
    ...C.shadow.sm,
  },
  statCard: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statNumber: {
    ...Theme.typography.h1,
    color: C.colors.primary,
    marginBottom: 2,
  },
  statLabel: {
    ...Theme.typography.caption,
    color: C.colors.textMuted,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  statDivider: {
    width: 1,
    height: 40,
    backgroundColor: C.colors.border,
  },
  subjectSection: {
    backgroundColor: C.colors.card,
    borderRadius: Theme.radius.lg,
    marginBottom: Theme.spacing.md,
    overflow: 'hidden',
    ...C.shadow.sm,
  },
  subjectHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: Theme.spacing.md,
    gap: Theme.spacing.md,
  },
  subjectIcon: {
    width: 44,
    height: 44,
    borderRadius: Theme.radius.md,
    backgroundColor: C.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  subjectIconText: {
    fontSize: Theme.typography.h3.fontSize,
    fontWeight: '800',
    color: Theme.colors.card,
  },
  subjectInfo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingRight: Theme.spacing.sm,
  },
  subjectTitle: {
    fontSize: Theme.typography.h4.fontSize,
    fontWeight: '700',
    color: C.colors.primary,
  },
  paperCountBadge: {
    backgroundColor: C.colors.blueLight,
    width: 24,
    height: 24,
    borderRadius: Theme.radius.md,
    justifyContent: 'center',
    alignItems: 'center',
  },
  paperCountBadgeText: {
    ...Theme.typography.caption,
    fontWeight: '700',
    color: C.colors.blue,
  },
  papersList: {
    padding: Theme.spacing.md,
    paddingTop: 0,
  },
  paperCard: {
    backgroundColor: '#F8FAFF',
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  paperCardHeader: {
    marginBottom: Theme.spacing.md,
  },
  paperTypeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 6,
    backgroundColor: C.colors.blueLight,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: Theme.radius.sm,
  },
  paperTypeText: {
    ...Theme.typography.label,
    fontWeight: '800',
    color: C.colors.blue,
    textTransform: 'uppercase',
  },
  paperTitle: {
    ...Theme.typography.h3,
    color: C.colors.primary,
    marginBottom: Theme.spacing.md,
  },
  paperMeta: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 16,
    rowGap: 8,
    marginBottom: Theme.spacing.md,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  metaText: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.colors.textMuted,
  },
  paperActions: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
  },
  actionBtn: {
    flex: 1,
    borderRadius: Theme.radius.md,
    backgroundColor: C.colors.blue,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 44,
  },
  viewBtnContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
  },
  actionBtnOutline: {
    flex: 1,
    borderRadius: Theme.radius.md,
    borderWidth: 1.5,
    borderColor: C.colors.blue,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Theme.spacing.sm,
    height: 44,
    backgroundColor: Theme.colors.card,
  },
  actionBtnText: {
    ...Theme.typography.bodyMd,
    fontWeight: '700',
    color: Theme.colors.card,
  },
  actionBtnOutlineText: {
    ...Theme.typography.bodyMd,
    fontWeight: '700',
    color: C.colors.blue,
  },
  processingContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Theme.spacing.sm,
    paddingVertical: Theme.spacing.sm,
    backgroundColor: C.colors.backgroundAlt,
    borderRadius: Theme.radius.sm,
  },
  processingText: {
    ...Theme.typography.caption,
    color: C.colors.textSec,
    fontWeight: '500',
  },
  noPapersContainer: {
    alignItems: 'center',
    paddingVertical: 30,
    gap: Theme.spacing.sm,
  },
  noPapersText: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.colors.textMuted,
  },
  loadingContainer: {
    minHeight: 220,
    paddingVertical: Theme.spacing.xxl,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    marginTop: Theme.spacing.md,
    fontSize: Theme.typography.caption.fontSize,
    color: C.colors.textSec,
  },
  errorContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 220,
    paddingVertical: 36,
    paddingHorizontal: Theme.spacing.lg,
    backgroundColor: C.colors.card,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: C.colors.border,
    ...C.shadow.sm,
    width: '100%',
    marginBottom: Theme.spacing.md,
  },
  errorTitle: {
    marginTop: Theme.spacing.md,
    fontSize: Theme.typography.h4.fontSize,
    fontWeight: '600',
    color: C.colors.text,
  },
  errorText: {
    marginTop: Theme.spacing.sm,
    fontSize: Theme.typography.body.fontSize,
    color: C.colors.textMuted,
    textAlign: 'center',
    lineHeight: 20,
  },
  retryBtn: {
    marginTop: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.xl,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
    backgroundColor: C.colors.primary,
  },
  retryBtnText: {
    color: C.colors.card,
    fontWeight: '600',
    fontSize: Theme.typography.body.fontSize,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 300,
    paddingVertical: 36,
    paddingHorizontal: Theme.spacing.lg,
    backgroundColor: C.colors.card,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: C.colors.border,
    ...C.shadow.sm,
    width: '100%',
    maxWidth: 420,
    alignSelf: 'center',
  },
  emptyIconContainer: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: C.colors.blueLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 18,
  },
  emptyTitle: {
    fontSize: Theme.typography.h4.fontSize,
    fontWeight: '700',
    color: C.colors.primary,
    marginBottom: 10,
    textAlign: 'center',
  },
  emptyText: {
    ...Theme.typography.body,
    color: C.colors.textSec,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: Theme.spacing.xl,
    maxWidth: 280,
  },
  resetEmptyBtn: {
    paddingVertical: 10,
    paddingHorizontal: Theme.spacing.xl,
    borderRadius: Theme.radius.md,
    backgroundColor: C.colors.background,
  },
  resetEmptyBtnText: {
    ...Theme.typography.body,
    fontWeight: '600',
    color: C.colors.blue,
  },
  filterModal: {
    backgroundColor: C.colors.card,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: '85%',
    shadowColor: C.colors.primary,
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 25,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Theme.spacing.lg,
    paddingTop: Theme.spacing.lg,
    paddingBottom: Theme.spacing.xl,
  },
  modalTitle: {
    fontSize: Theme.typography.h3.fontSize,
    fontWeight: '800',
    color: C.colors.primary,
    letterSpacing: -0.5,
  },
  modalBody: {
    paddingHorizontal: Theme.spacing.lg,
  },
  filterSectionTitle: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '700',
    color: C.colors.textMuted,
    marginBottom: Theme.spacing.md,
    marginTop: Theme.spacing.sm,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  filterOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 28,
  },
  filterOption: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.background,
    borderWidth: 1.5,
    borderColor: Theme.colors.background,
  },
  filterOptionActive: {
    backgroundColor: C.colors.blueLight,
    borderColor: C.colors.blue,
  },
  filterOptionText: {
    ...Theme.typography.body,
    fontWeight: '600',
    color: C.colors.textSec,
  },
  filterOptionTextActive: {
    color: C.colors.blue,
  },
  modalFooter: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    padding: Theme.spacing.lg,
    backgroundColor: C.colors.card,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.background,
  },
  resetModalBtn: {
    flex: 1,
    height: 54,
    borderRadius: Theme.radius.lg,
    backgroundColor: Theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resetModalBtnText: {
    fontSize: Theme.typography.h4.fontSize,
    fontWeight: '700',
    color: C.colors.textSec,
  },
  applyModalBtn: {
    flex: 2,
    height: 54,
    borderRadius: Theme.radius.lg,
    overflow: 'hidden',
  },
  applyModalGradient: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.colors.blue,
  },
  applyModalBtnText: {
    fontSize: Theme.typography.h4.fontSize,
    fontWeight: '800',
    color: C.colors.card,
  },
});
