import { StyleSheet, Platform } from 'react-native';
import {Theme, C, colors} from '../../../theme/tokens';

export const studentListStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.colors.background,
  },
  headerStandard: {
    backgroundColor: Theme.colors.primary,
    paddingBottom: 30,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Theme.spacing.xl,
    paddingBottom: Theme.spacing.md,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.md,
    backgroundColor: 'rgba(255,255,255,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: Theme.colors.card,
  },
  notificationBtn: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.md,
    backgroundColor: 'rgba(255,255,255,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchContainer: {
    paddingHorizontal: Theme.spacing.xl,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.card,
    borderRadius: 15,
    paddingHorizontal: 15,
    height: 54,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    ...Theme.typography.bodyMd,
    color: '#1E293B',
  },
  filterBtn: {
    padding: 5,
    borderLeftWidth: 1,
    borderLeftColor: Theme.colors.background,
    marginLeft: 5,
  },
  contentContainer: {
    paddingBottom: 100,
  },
  filterCard: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.xxl,
    padding: Theme.spacing.xl,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 3,
    marginBottom: Theme.spacing.lg,
  },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 15,
  },
  filterTitle: {
    fontSize: Theme.typography.h4.fontSize,
    color: Theme.colors.primary,
  },
  chipScroll: {
    marginBottom: 15,
  },
  chip: {
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.background,
    marginRight: 10,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  chipActive: {
    backgroundColor: Theme.colors.primary,
    borderColor: Theme.colors.primary,
  },
  chipText: {
    ...Theme.typography.body,
    color: Theme.colors.textSec,
  },
  chipTextActive: {
    color: Theme.colors.card,
  },
  sectionPicker: {
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: Theme.colors.background,
    paddingTop: 15,
  },
  sectionLabel: {
    ...Theme.typography.body,
    color: Theme.colors.textSec,
    marginRight: Theme.spacing.md,
  },
  sectionChips: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
  },
  lockedScopeCard: {
    padding: 14,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.background,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  lockedScopeText: {
    ...Theme.typography.body,
    color: Theme.colors.primary,
  },
  lockedScopeHint: {
    marginTop: Theme.spacing.xs,
    ...Theme.typography.caption,
    color: Theme.colors.textSec,
  },
  secChip: {
    width: 36,
    height: 36,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  secChipActive: {
    backgroundColor: Theme.colors.primary,
    borderColor: Theme.colors.primary,
  },
  secChipText: {
    ...Theme.typography.body,
    color: Theme.colors.textSec,
  },
  secChipTextActive: {
    color: Theme.colors.card,
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.xs,
  },
  listTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: '#1E293B',
    letterSpacing: -0.5,
  },
  listCount: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textSec,
    backgroundColor: Theme.colors.background,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 6,
    borderRadius: Theme.radius.md,
  },
  listContainer: {
    gap: Theme.spacing.md,
  },
  modalActionRow: {
    paddingHorizontal: Theme.spacing.xl,
    marginBottom: 10,
  },
  modalActionBtn: {
    alignSelf: 'flex-start',
  },
  editInput: {
    minHeight: 42,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.sm,
    marginTop: 6,
    color: '#1E293B',
    ...Theme.typography.body,
  },
  studentCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Theme.colors.card,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.xxl,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: Theme.colors.background,
  },
  studentInfo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  studentAvatarContainer: {
    marginRight: 15,
  },
  avatarWrapper: {
    width: 48,
    height: 48,
    borderRadius: Theme.radius.xxl,
    backgroundColor: Theme.colors.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  studentAvatar: {
    width: '100%',
    height: '100%',
  },
  avatarPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: Theme.typography.h3.fontSize,
    color: Theme.colors.card,
  },
  studentDetails: {
    flex: 1,
    gap: 2,
  },
  studentName: {
    ...Theme.typography.bodyMd,
    color: '#1E293B',
  },
  studentClass: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textMuted,
  },
  cardRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: Theme.radius.sm,
  },
  statusBadgeText: {
    fontSize: Theme.typography.label.fontSize,
    letterSpacing: 0.5,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  emptyTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: '#1E293B',
    marginTop: Theme.spacing.md,
  },
  emptySub: {
    ...Theme.typography.body,
    color: Theme.colors.textSec,
    marginTop: Theme.spacing.sm,
    textAlign: 'center',
    paddingHorizontal: 40,
  },
  fab: {
    position: 'absolute',
    bottom: 30,
    right: 30,
    width: 60,
    height: 60,
    borderRadius: Theme.radius.xxxl,
    backgroundColor: Theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowColor: Theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: Theme.colors.card,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    height: '90%',
  },
  modalHeader: {
    alignItems: 'center',
    paddingVertical: 15,
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: Theme.colors.border,
    borderRadius: 2,
  },
  modalClose: {
    position: 'absolute',
    right: 20,
    top: 20,
  },
  modalBody: {
    padding: Theme.spacing.xl,
  },
  modalProfileHeader: {
    alignItems: 'center',
    marginBottom: 30,
  },
  modalAvatarContainer: {
    position: 'relative',
    marginBottom: 15,
  },
  modalLargeAvatar: {
    width: 100,
    height: 100,
    borderRadius: Theme.radius.xxxl,
  },
  modalLargePlaceholder: {
    width: 100,
    height: 100,
    borderRadius: Theme.radius.xxxl,
    backgroundColor: Theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalLargeAvatarText: {
    fontSize: 32,
    color: Theme.colors.primary,
  },
  modalStatusBadge: {
    position: 'absolute',
    bottom: -10,
    alignSelf: 'center',
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.md,
    borderWidth: 3,
    borderColor: Theme.colors.card,
  },
  modalStatusText: {
    ...Theme.typography.label,
    color: Theme.colors.card,
  },
  modalName: {
    fontSize: Theme.typography.h2.fontSize,
    color: '#1E293B',
  },
  modalSub: {
    ...Theme.typography.body,
    color: Theme.colors.textSec,
    marginTop: Theme.spacing.xs,
  },
  infoSection: {
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.xxxl,
    padding: Theme.spacing.xl,
    marginBottom: Theme.spacing.lg,
  },
  infoRow: {
    flexDirection: 'row',
    marginBottom: Theme.spacing.xl,
  },
  infoItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
  },
  infoIcon: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoLabel: {
    ...Theme.typography.label,
    color: Theme.colors.textMuted,
    textTransform: 'uppercase',
  },
  infoValue: {
    ...Theme.typography.body,
    color: '#1E293B',
    marginTop: 2,
  },
  sectionTitle: {
    fontSize: Theme.typography.h4.fontSize,
    color: '#1E293B',
    marginBottom: Theme.spacing.md,
    marginLeft: Theme.spacing.xs,
  },
  parentCard: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.xxxl,
    borderWidth: 1,
    borderColor: Theme.colors.background,
    padding: Theme.spacing.xl,
  },
  parentItem: {
    paddingVertical: 10,
  },
  parentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.sm,
  },
  parentRole: {
    ...Theme.typography.caption,
    color: Theme.colors.textSec,
    textTransform: 'uppercase',
  },
  callBtn: {
    width: 32,
    height: 32,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  parentName: {
    fontSize: Theme.typography.h4.fontSize,
    color: '#1E293B',
  },
  parentPhone: {
    ...Theme.typography.body,
    color: Theme.colors.primary,
    marginTop: Theme.spacing.xs,
  },
  parentDivider: {
    height: 1,
    backgroundColor: Theme.colors.background,
    marginVertical: 15,
  },
  modalFooter: {
    padding: Theme.spacing.xl,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.background,
  },
  doneBtn: {
    backgroundColor: Theme.colors.primary,
    height: 56,
    borderRadius: Theme.radius.lg,
  },
});
