import { StyleSheet, Dimensions } from 'react-native';
import {Theme, C, colors} from '../../../theme/tokens';

const { width } = Dimensions.get('window');

export const leaveStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: C.colors.background,
    },
    pageBody: {},
    formCard: {
        backgroundColor: C.colors.card,
        borderRadius: Theme.radius.md,
        padding: Theme.spacing.md,
        ...C.shadow.sm,
        marginTop: 10,
    },
    cardTitle: {
        ...Theme.typography.body,
        fontWeight: '700',
        color: C.colors.text,
        marginBottom: Theme.spacing.md,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    formGroup: {
        marginBottom: Theme.spacing.xl,
    },
    formLabel: {
        ...Theme.typography.body,
        color: C.colors.textSec,
        marginBottom: Theme.spacing.sm,
        fontWeight: '500',
    },
    toggleContainer: {
        flexDirection: 'row',
        gap: Theme.spacing.md,
    },
    toggleButton: {
        flex: 1,
        height: 44,
        borderRadius: 22,
        borderWidth: 1,
        borderColor: C.colors.blue,
        justifyContent: 'center',
        alignItems: 'center',
    },
    toggleButtonActive: {
        backgroundColor: C.colors.blue,
    },
    toggleButtonText: {
        color: C.colors.blue,
        fontWeight: '600',
    },
    toggleButtonTextActive: {
        color: C.colors.card,
    },
    dropdownText: {
        ...Theme.typography.bodyMd,
        color: C.colors.text,
    },
    autoTeacherCard: {
        minHeight: 52,
        backgroundColor: C.colors.inputBg,
        borderRadius: Theme.radius.md,
        borderWidth: 1,
        borderColor: C.colors.blueLight,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: Theme.spacing.md,
        paddingVertical: Theme.spacing.md,
    },
    autoTeacherTextBlock: {
        flex: 1,
        paddingRight: Theme.spacing.md,
    },
    autoTeacherHint: {
        marginTop: Theme.spacing.xs,
        ...Theme.typography.caption,
        color: C.colors.textSec,
    },
    dropdownPlaceholder: {
        color: C.colors.textMuted,
    },
    inputField: {
        height: 52,
        backgroundColor: C.colors.inputBg,
        borderRadius: Theme.radius.md,
        borderWidth: 1,
        borderColor: C.colors.border,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: Theme.spacing.md,
    },
    inputText: {
        ...Theme.typography.bodyMd,
        color: C.colors.text,
    },
    textInputArea: {
        backgroundColor: C.colors.inputBg,
        borderRadius: Theme.radius.md,
        borderWidth: 1,
        borderColor: C.colors.border,
        padding: Theme.spacing.md,
        ...Theme.typography.bodyMd,
        color: C.colors.text,
        minHeight: 120,
    },
    submitBtn: {
        backgroundColor: C.colors.blue,
        height: 54,
        borderRadius: Theme.radius.md,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,
    },
    submitIcon: {
        marginRight: 10,
        transform: [{ rotate: '-45deg' }, { translateY: -2 }],
    },
    submitBtnText: {
        color: C.colors.card,
        ...Theme.typography.h4,
    },
    historyCardContainer: {
        backgroundColor: C.colors.card,
        marginTop: 15,
        borderRadius: Theme.radius.md,
        padding: Theme.spacing.md,
        ...C.shadow.sm,
    },
    emptyHistoryState: {
        alignItems: 'center',
        paddingVertical: 30,
    },
    illustrationPlaceholder: {
        width: 150,
        height: 120,
        marginBottom: Theme.spacing.xl,
        justifyContent: 'center',
        alignItems: 'center',
    },
    illuLayer1: {
        width: 100,
        height: 100,
        backgroundColor: C.colors.backgroundAlt,
        borderRadius: 50,
        position: 'absolute',
    },
    illuLayer2: {
        width: 80,
        height: 80,
        backgroundColor: C.colors.border,
        borderRadius: 40,
        position: 'absolute',
        opacity: 0.5,
    },
    illuLayer3: {
        width: 60,
        height: 60,
        backgroundColor: C.colors.card,
        borderRadius: Theme.radius.xxxl,
        position: 'absolute',
        ...C.shadow.sm,
    },
    illuIcon: {
        zIndex: 1,
    },
    emptyHistoryTitle: {
        ...Theme.typography.h4,
        color: C.colors.text,
        marginBottom: Theme.spacing.sm,
    },
    emptyHistorySubtitle: {
        fontSize: Theme.typography.caption.fontSize,
        color: C.colors.textSec,
        textAlign: 'center',
    },
    viewMoreBtn: {
        marginTop: Theme.spacing.sm,
        alignSelf: 'center',
        paddingHorizontal: 18,
        paddingVertical: 10,
        borderRadius: Theme.radius.full,
        borderWidth: 1,
        borderColor: C.colors.border,
        backgroundColor: C.colors.card,
    },
    viewMoreText: {
        fontSize: Theme.typography.caption.fontSize,
        fontWeight: '700',
        color: C.colors.blue,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: C.colors.text + '80',
        justifyContent: 'flex-end',
    },
    modalOverlayCenter: {
        flex: 1,
        backgroundColor: C.colors.text + '80',
        justifyContent: 'center',
        alignItems: 'center',
    },
    teacherModalContent: {
        backgroundColor: C.colors.card,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        maxHeight: '80%',
        paddingBottom: 30,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: Theme.spacing.xl,
        borderBottomWidth: 1,
        borderBottomColor: C.colors.border,
    },
    modalTitle: {
        ...Theme.typography.h3,
        color: C.colors.text,
    },
    teacherList: {
        padding: Theme.spacing.xl,
    },
    teacherItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: Theme.spacing.md,
        borderBottomWidth: 1,
        borderBottomColor: C.colors.backgroundAlt,
    },
    teacherItemSelected: {
        backgroundColor: C.colors.blueLight,
        borderRadius: Theme.radius.md,
        paddingHorizontal: Theme.spacing.md,
        marginHorizontal: -12,
    },
    teacherItemAvatar: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: C.colors.blue,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: Theme.spacing.md,
    },
    teacherItemAvatarText: {
        color: C.colors.card,
        ...Theme.typography.h3,
    },
    teacherItemName: {
        ...Theme.typography.bodyMd,
        fontWeight: '600',
        color: C.colors.text,
    },
    teacherItemSubject: {
        fontSize: Theme.typography.caption.fontSize,
        color: C.colors.textSec,
        marginTop: 2,
    },
    checkIcon: {
        marginLeft: 'auto',
    },
    successModal: {
        backgroundColor: C.colors.card,
        borderRadius: Theme.radius.xxl,
        padding: Theme.spacing.lg,
        alignItems: 'center',
        width: width * 0.8,
    },
    successIconContainer: {
        marginBottom: Theme.spacing.md,
    },
    successTitle: {
        fontSize: Theme.typography.h3.fontSize,
        fontWeight: '800',
        color: C.colors.text,
        marginBottom: Theme.spacing.sm,
    },
    successMessage: {
        ...Theme.typography.body,
        color: C.colors.textSec,
        textAlign: 'center',
        lineHeight: 20,
    },
    badge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: Theme.spacing.xs,
        paddingVertical: Theme.spacing.xs,
        paddingHorizontal: 10,
        borderRadius: Theme.radius.md,
    },
    badgeText: {
        ...Theme.typography.label,
        fontWeight: 'bold',
    },
    historyCard: {
        backgroundColor: C.colors.cardAlt,
        borderRadius: Theme.radius.lg,
        padding: Theme.spacing.md,
        marginBottom: Theme.spacing.md,
        borderWidth: 1,
        borderColor: C.colors.border,
    },
    historyCardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: Theme.spacing.md,
    },
    historyTeacherInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    historyTeacherAvatar: {
        width: 40,
        height: 40,
        borderRadius: Theme.radius.xl,
        backgroundColor: C.colors.border,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: Theme.spacing.md,
    },
    historyTeacherAvatarText: {
        color: C.colors.textSec,
        ...Theme.typography.h4,
    },
    historyTeacherName: {
        ...Theme.typography.body,
        fontWeight: 'bold',
        color: C.colors.text,
    },
    historyDuration: {
        ...Theme.typography.caption,
        color: C.colors.textSec,
        marginTop: 2,
    },
    historyCardBody: {
        gap: 10,
    },
    historyDateRange: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: Theme.spacing.sm,
    },
    historyDateText: {
        fontSize: Theme.typography.caption.fontSize,
        color: C.colors.text,
    },
    historyReason: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: Theme.spacing.sm,
    },
    historyReasonText: {
        fontSize: Theme.typography.caption.fontSize,
        color: C.colors.textSec,
        lineHeight: 18,
        flex: 1,
    },
    historyFooter: {
        marginTop: Theme.spacing.md,
        paddingTop: Theme.spacing.md,
        borderTopWidth: 1,
        borderTopColor: C.colors.border,
        flexDirection: 'row',
        justifyContent: 'flex-end',
    },
    viewDetailsBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    viewDetailsText: {
        fontSize: Theme.typography.caption.fontSize,
        color: C.colors.blue,
        fontWeight: '600',
    },
    detailCard: {
        backgroundColor: C.colors.card,
    },
    detailStatusRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: Theme.spacing.xl,
    },
    detailDateText: {
        ...Theme.typography.caption,
        color: C.colors.textMuted,
    },
    detailInfoSection: {
        marginBottom: Theme.spacing.xl,
    },
    detailLabel: {
        ...Theme.typography.label,
        fontWeight: 'bold',
        color: C.colors.textMuted,
        marginBottom: Theme.spacing.sm,
        letterSpacing: 0.5,
    },
    detailValueContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 10,
    },
    detailValueText: {
        ...Theme.typography.bodyMd,
        color: C.colors.text,
        fontWeight: '600',
    },
    detailSubValueText: {
        ...Theme.typography.caption,
        color: C.colors.textMuted,
        marginTop: 2,
    },
    detailAvatar: {
        width: 40,
        height: 40,
        borderRadius: Theme.radius.xl,
        backgroundColor: C.colors.blueLight,
        justifyContent: 'center',
        alignItems: 'center',
    },
    detailAvatarText: {
        color: C.colors.blue,
        ...Theme.typography.h4,
    },
    detailDurationText: {
        fontSize: Theme.typography.caption.fontSize,
        color: C.colors.blue,
        fontWeight: '600',
    },
    detailReasonBox: {
        backgroundColor: C.colors.background,
        padding: Theme.spacing.md,
        borderRadius: Theme.radius.md,
        borderWidth: 1,
        borderColor: C.colors.border,
    },
    detailReasonText: {
        ...Theme.typography.body,
        color: C.colors.text,
        lineHeight: 20,
    },
    modalCloseBtn: {
        margin: Theme.spacing.xl,
        backgroundColor: C.colors.backgroundAlt,
        height: 50,
        borderRadius: Theme.radius.md,
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalCloseBtnText: {
        color: C.colors.textSec,
        ...Theme.typography.h4,
    },
});
