import { StyleSheet } from 'react-native';
import {Theme, colors} from '../../../theme/tokens';

export const calendarModalStyles = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  box: {
    backgroundColor: Theme.colors.background,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '88%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 10,
  },
  head: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 18,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
  },
  headTitle: { fontSize: 16, fontWeight: '700', color: Theme.colors.text },
  centered: { alignItems: 'center', paddingVertical: 40 },
  scroll: { padding: Theme.spacing.md },
  monthNav: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: Theme.spacing.md },
  navBtn: { padding: Theme.spacing.sm, borderRadius: 8, backgroundColor: Theme.colors.background },
  monthText: { fontSize: 16, fontWeight: '700', color: Theme.colors.text },
  weekRow: { flexDirection: 'row', marginBottom: Theme.spacing.sm },
  weekDay: { flex: 1, textAlign: 'center', ...Theme.typography.caption, fontWeight: '700', color: Theme.colors.textMuted },
  daysGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginBottom: Theme.spacing.md },
  dayCell: {
    width: '12.5%',
    aspectRatio: 1,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Theme.colors.background,
    position: 'relative',
  },
  dayCellBlocked: { backgroundColor: Theme.colors.background, opacity: 0.55 },
  emptyCell: { width: '12.5%', aspectRatio: 1 },
  dayCellToday: { borderWidth: 2, borderColor: Theme.colors.primary },
  dayNum: { fontSize: 13, fontWeight: '500', color: Theme.colors.text },
  dayNumBlocked: { color: '#94a3b8' },
  leaveDot: { position: 'absolute', bottom: 2, right: 2, width: 5, height: 5, borderRadius: 3, backgroundColor: '#f59e0b' },
  legend: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, justifyContent: 'center', marginBottom: Theme.spacing.sm },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  legendDot: { width: 14, height: 14, borderRadius: 7 },
  legendText: { ...Theme.typography.caption, color: Theme.colors.textMuted },
  blockedNote: { textAlign: 'center', ...Theme.typography.label, color: Theme.colors.textMuted, marginBottom: 14 },
  saveBtn: {
    backgroundColor: Theme.colors.primary,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: Theme.spacing.lg,
  },
});
