# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m

# AndroidX support
android.useAndroidX=true
android.enableJetifier=true

# Target Architectures
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# Enable New Architecture
newArchEnabled=false
hermesEnabled=false
edgeToEdgeEnabled=false

MYAPP_UPLOAD_STORE_FILE=attendx.keystore
MYAPP_UPLOAD_KEY_ALIAS=attendx
MYAPP_UPLOAD_STORE_PASSWORD=Visys@123
MYAPP_UPLOAD_KEY_PASSWORD=Visys@123
