import { StyleSheet } from 'react-native';
import {Theme, C, colors} from '../../../theme/tokens';

export const studentDashboardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.colors.background,
  },
  center: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerContent: {
    backgroundColor: C.colors.primary,
    paddingHorizontal: Theme.spacing.xl,
    paddingBottom: 40,
    marginBottom: Theme.spacing.xl,
    marginHorizontal: -20,
    overflow: 'hidden',
  },
  statsGrid: {
    marginTop: Theme.spacing.md,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  statCard: {
    backgroundColor: C.colors.card,
    borderRadius: 22,
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.md,
    width: '46%',
    marginBottom: Theme.spacing.md,
    ...C.shadow.sm,
  },
  attendancePctCard: {
    backgroundColor: C.colors.card,
    borderRadius: 22,
    paddingHorizontal: Theme.spacing.xl,
    paddingVertical: Theme.spacing.md,
    marginTop: Theme.spacing.sm,
    ...C.shadow.sm,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  statLabel: {
    ...Theme.typography.body,
    color: '#6B7280',
    fontWeight: '600',
  },
  statValue: {
    fontSize: Theme.typography.h3.fontSize,
    fontWeight: '800',
    color: '#111827',
    marginTop: 2,
  },
  chartPlaceholder: {
    width: 110,
    height: 40,
    justifyContent: 'center',
  },
  sheet: {
    marginTop: -20,
  },
  sectionCard: {
    backgroundColor: C.colors.card,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.md,
    marginBottom: 14,
    ...C.shadow.sm,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  sectionAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  sectionTitle: {
    fontSize: Theme.typography.h4.fontSize,
    fontWeight: '800',
    color: C.colors.text,
    lineHeight: 22,
  },
  viewAll: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.colors.blue,
    fontWeight: '700',
  },
  gridItemInner: {
    alignItems: 'center',
    width: '100%',
    paddingVertical: Theme.spacing.xs,
  },
  iconContainer: {
    width: 48,
    height: 48,
    borderRadius: Theme.radius.lg,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Theme.spacing.sm,
  },
  gridLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: C.colors.text,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 14,
  },
  listRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
  },
  listRowDivider: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: C.colors.border,
  },
  rowIcon: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Theme.spacing.md,
  },
  rowBody: {
    flex: 1,
    minWidth: 0,
  },
  rowTitle: {
    fontSize: Theme.typography.bodyMd.fontSize,
    fontWeight: '700',
    color: C.colors.text,
  },
  rowMeta: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.colors.textMuted,
    marginTop: 2,
  },
  rowStatus: {
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginLeft: Theme.spacing.sm,
  },
  rowActionBtn: {
    backgroundColor: '#EFF6FF',
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 7,
    borderRadius: Theme.radius.md,
    marginLeft: Theme.spacing.sm,
  },
  rowActionText: {
    color: C.colors.blue,
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '700',
  },
  emptyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
  },
  emptyIconWrap: {
    width: 42,
    height: 42,
    borderRadius: Theme.radius.md,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Theme.spacing.md,
  },
  emptyCopy: {
    flex: 1,
  },
  emptyMessage: {
    fontSize: Theme.typography.body.fontSize,
    color: C.colors.textMuted,
    lineHeight: 20,
  },
  emptyAction: {
    marginTop: Theme.spacing.xs,
    fontSize: Theme.typography.caption.fontSize,
    color: C.colors.blue,
    fontWeight: '700',
  },
  viewerContainer: {
    flex: 1,
    backgroundColor: C.colors.card,
  },
  viewerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Theme.spacing.md,
    paddingBottom: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: C.colors.border,
  },
  viewerCloseBtn: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewerTitle: {
    flex: 1,
    textAlign: 'center',
    ...Theme.typography.h3,
    color: C.colors.text,
  },
  loaderOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: C.colors.card + 'CC', // 0.8 opacity
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 999,
  },
  loaderText: {
    marginTop: Theme.spacing.md,
    ...Theme.typography.bodyMd,
    color: C.colors.blue,
    fontWeight: '600',
  },
  decCircle1: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(255,255,255,0.06)',
    top: -50,
    right: -40,
  },
  decCircle2: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255,255,255,0.05)',
    bottom: -20,
    left: 60,
  },
});
