import { StyleSheet } from 'react-native';
import {Theme, colors} from '../../../theme/tokens';
import { HEADER_CONSTANTS } from '../../../constants/headerConstants';

export const teacherDashboardStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Theme.colors.background },
  scrollView: { flex: 1 },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: Theme.colors.background },
  gridItemInner: { alignItems: 'center', width: '100%' },
  scrollContent: { paddingHorizontal: HEADER_CONSTANTS.DASHBOARD_HORIZONTAL, paddingTop: 0 },
  section: { marginBottom: 26 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: Theme.spacing.md },
  sectionTitle: { fontSize: Theme.typography.h2.fontSize, color: Theme.colors.text, fontWeight: '800' },
  viewDetailsBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#EFF6FF', paddingHorizontal: 14, paddingVertical: Theme.spacing.sm, borderRadius: Theme.radius.xl },
  linkText: { color: Theme.colors.primaryLight, ...Theme.typography.body, fontWeight: '700', marginRight: 2 },

  /* Unified Analytics Card Styles */
  analyticsCard: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.xxl,
    padding: Theme.spacing.xl,
    borderWidth: 1,
    borderColor: Theme.colors.background,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  analyticsTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  analyticsLabel: { ...Theme.typography.body, color: Theme.colors.textSec, fontWeight: '600' },
  analyticsMainValue: { fontSize: 36, color: '#1E293B', fontWeight: '800', marginTop: Theme.spacing.xs },
  analyticsIconWrap: { width: 50, height: 50, borderRadius: 25, justifyContent: 'center', alignItems: 'center' },
  progressBarContainer: { height: 10, backgroundColor: Theme.colors.background, borderRadius: 5, marginTop: Theme.spacing.xl, overflow: 'hidden' },
  progressBarFill: { height: '100%', backgroundColor: Theme.colors.blue, borderRadius: 5 },
  analyticsDivider: { height: 1, backgroundColor: Theme.colors.background, marginVertical: Theme.spacing.xl },
  analyticsBottomRow: { flexDirection: 'row', justifyContent: 'space-around' },
  analyticsStatBox: { flexDirection: 'row', alignItems: 'center' },
  miniDot: { width: 10, height: 10, borderRadius: 5, marginRight: 10 },
  analyticsStatValue: { fontSize: Theme.typography.h3.fontSize, fontWeight: '800', color: '#1E293B' },
  analyticsStatLabel: { fontSize: Theme.typography.caption.fontSize, color: Theme.colors.textSec, fontWeight: '600', marginTop: 2 },

  actionIcon: {
    width: 46,
    height: 46,
    borderRadius: Theme.radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Theme.spacing.sm,
  },
  actionText: {
    ...Theme.typography.label,
    color: '#1E293B',
    textAlign: 'center',
    fontWeight: '600',
    lineHeight: 14,
  },

  /* Today's Inspiration Banner Styles */
  quoteBanner: {
    borderRadius: Theme.radius.xxl,
    padding: Theme.spacing.xl,
    marginBottom: 26,
    backgroundColor: Theme.colors.primary,
    shadowColor: Theme.colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 4,
  },
  quoteHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Theme.spacing.sm,
  },
  quoteLabel: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  quoteText: {
    color: Theme.colors.card,
    fontSize: Theme.typography.h4.fontSize,
    fontWeight: '600',
    lineHeight: 22,
    fontStyle: 'italic',
  },
  quoteAuthor: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '700',
    textAlign: 'right',
    marginTop: Theme.spacing.sm,
  },

  /* My Classes Slider Styles */
  classesScrollContent: {
    paddingHorizontal: Theme.spacing.xl,
    paddingBottom: Theme.spacing.sm,
    gap: Theme.spacing.md,
  },
  classCard: {
    width: 280,
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    shadowColor: Theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  classCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
  },
  classBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EFF6FF',
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.md,
  },
  classBadgeText: {
    color: Theme.colors.primary,
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '700',
    marginLeft: Theme.spacing.xs,
  },
  subjectBadge: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.md,
  },
  subjectBadgeText: {
    color: '#4B5563',
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '600',
  },
  classCardTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: Theme.colors.text,
    fontWeight: '800',
    marginBottom: 6,
  },
  classCardStats: {
    flexDirection: 'row',
    marginBottom: Theme.spacing.sm,
  },
  classCardStatItem: {
    flex: 1,
  },
  classCardStatLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: Theme.colors.textMuted,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  classCardStatValue: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textSec,
    fontWeight: '700',
    marginTop: 2,
  },
  classCardDivider: {
    height: 1,
    backgroundColor: Theme.colors.border,
    marginVertical: Theme.spacing.md,
  },
  classCardFooter: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
  },
  classCardBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.radius.md,
    gap: Theme.spacing.xs,
  },
  classCardBtnText: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '700',
  },
  noClassesCard: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  noClassesTitle: {
    fontSize: Theme.typography.h4.fontSize,
    color: Theme.colors.text,
    fontWeight: '700',
    marginTop: Theme.spacing.sm,
  },
  noClassesDesc: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textMuted,
    textAlign: 'center',
    marginTop: Theme.spacing.xs,
  },

  /* Quick Stats Summary */
  statsRow: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
  },
  statsCard: {
    flex: 1,
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.lg,
    padding: 14,
    borderLeftWidth: 3,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    alignItems: 'center',
    gap: Theme.spacing.xs,
  },
  statsValue: {
    fontSize: Theme.typography.h2.fontSize,
    fontWeight: '800',
    color: Theme.colors.text,
  },
  statsLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: Theme.colors.textMuted,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
});
