import { StyleSheet } from 'react-native';
import {Theme, C, colors} from '../../../theme/tokens';

export const expenseStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.colors.background,
  },
  content: {
    padding: Theme.spacing.xl,
    paddingBottom: 100,
        backgroundColor: Theme.colors.background,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  actionBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
  },
  filterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: 14,
    borderRadius: Theme.radius.xl,
    backgroundColor: Theme.colors.primary + '10',
    borderWidth: 1,
    borderColor: Theme.colors.primary + '30',
  },
  filterBtnText: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '600',
    color: Theme.colors.primary,
  },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.xl,
    backgroundColor: Theme.colors.primary,
  },
  addBtnText: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '600',
    color: Theme.colors.card,
  },
  summaryContainer: {
    marginBottom: Theme.spacing.xl,
  },
  summaryCard: {
    backgroundColor: Theme.colors.card || Theme.colors.card,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Theme.colors.border,
    marginBottom: Theme.spacing.md,
  },
  summaryLabel: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textMuted,
    marginTop: Theme.spacing.sm,
  },
  summaryValue: {
    fontSize: Theme.typography.h1.fontSize,
    fontWeight: '800',
    color: Theme.colors.text,
    marginTop: Theme.spacing.xs,
  },
  summaryCount: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textMuted,
    marginTop: 2,
  },
  categoryScroll: {
    marginHorizontal: -20,
    paddingHorizontal: Theme.spacing.xl,
  },
  categoryMiniCard: {
    width: 120,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    marginRight: 10,
    alignItems: 'center',
  },
  categoryDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginBottom: 6,
  },
  categoryMiniName: {
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '600',
    color: Theme.colors.text,
    marginBottom: 2,
  },
  categoryMiniAmount: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '700',
    color: Theme.colors.text,
  },
  categoryMiniCount: {
    fontSize: Theme.typography.label.fontSize,
    color: Theme.colors.textMuted,
    marginTop: 2,
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
  },
  listTitle: {
    fontSize: Theme.typography.h4.fontSize,
    fontWeight: '700',
    color: Theme.colors.text,
  },
  listCount: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textMuted,
    backgroundColor: Theme.colors.background,
    paddingVertical: 2,
    paddingHorizontal: 10,
    borderRadius: Theme.radius.md,
    overflow: 'hidden',
  },
  loader: {
    paddingVertical: 40,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyText: {
    fontSize: Theme.typography.h4.fontSize,
    fontWeight: '600',
    color: Theme.colors.textSec,
    marginTop: Theme.spacing.md,
  },
  emptySubtext: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textMuted,
    marginTop: 6,
  },
  expenseCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.card || Theme.colors.card,
    borderRadius: Theme.radius.md,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  categoryBadge: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Theme.spacing.md,
  },
  categoryBadgeText: {
    fontSize: Theme.typography.h4.fontSize,
    fontWeight: '700',
    color: Theme.colors.card,
  },
  expenseInfo: {
    flex: 1,
  },
  expenseTitle: {
    fontSize: Theme.typography.body.fontSize,
    fontWeight: '600',
    color: Theme.colors.text,
    marginBottom: 3,
  },
  expenseDate: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textMuted,
  },
  expenseRight: {
    alignItems: 'flex-end',
  },
  expenseAmount: {
    fontSize: Theme.typography.bodyMd.fontSize,
    fontWeight: '700',
    color: Theme.colors.text,
    marginBottom: Theme.spacing.xs,
  },
  categoryTag: {
    paddingVertical: 2,
    paddingHorizontal: Theme.spacing.sm,
    borderRadius: Theme.radius.sm,
  },
  categoryTagText: {
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '600',
  },
  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: Theme.colors.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '85%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Theme.spacing.xl,
    paddingBottom: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
  },
  modalTitle: {
    fontSize: Theme.typography.h3.fontSize,
    fontWeight: '700',
    color: Theme.colors.text,
  },
  modalBody: {
    padding: Theme.spacing.xl,
  },
  label: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '600',
    color: Theme.colors.textSec,
    marginBottom: Theme.spacing.sm,
    marginTop: Theme.spacing.md,
  },
  input: {
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    fontSize: Theme.typography.bodyMd.fontSize,
    color: Theme.colors.text,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  multiline: {
    height: 80,
    textAlignVertical: 'top',
  },
  optionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Theme.spacing.sm,
  },
  optionChip: {
    paddingVertical: 7,
    paddingHorizontal: 14,
    borderRadius: Theme.radius.lg,
    backgroundColor: Theme.colors.background,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  optionChipActive: {
    backgroundColor: Theme.colors.primary,
    borderColor: Theme.colors.primary,
  },
  optionText: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '500',
    color: Theme.colors.textSec,
  },
  optionTextActive: {
    color: Theme.colors.card,
  },
  dateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  dateBtnText: {
    fontSize: Theme.typography.bodyMd.fontSize,
    color: Theme.colors.text,
  },
  modalFooter: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    padding: Theme.spacing.xl,
    paddingTop: Theme.spacing.md,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.border,
  },
  cancelBtn: {
    flex: 1,
    padding: 14,
    borderRadius: Theme.radius.md,
    alignItems: 'center',
    backgroundColor: Theme.colors.background,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  cancelBtnText: {
    fontSize: Theme.typography.bodyMd.fontSize,
    fontWeight: '600',
    color: Theme.colors.textSec,
  },
  submitBtn: {
    flex: 1,
    padding: 14,
    borderRadius: Theme.radius.md,
    alignItems: 'center',
    backgroundColor: Theme.colors.primary,
  },
  submitBtnText: {
    fontSize: Theme.typography.bodyMd.fontSize,
    fontWeight: '600',
    color: Theme.colors.card,
  },
  // Delete modal
  deleteModal: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.lg,
    margin: Theme.spacing.xl,
    alignItems: 'center',
  },
  deleteTitle: {
    fontSize: Theme.typography.h3.fontSize,
    fontWeight: '700',
    color: Theme.colors.text,
    marginTop: Theme.spacing.md,
  },
  deleteMessage: {
    fontSize: Theme.typography.body.fontSize,
    color: Theme.colors.textSec,
    marginTop: Theme.spacing.sm,
    textAlign: 'center',
  },
  deleteActions: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    marginTop: Theme.spacing.xl,
    width: '100%',
  },
  deleteConfirmBtn: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    padding: 14,
    borderRadius: Theme.radius.md,
    backgroundColor: C.error || Theme.colors.error,
  },
  deleteConfirmText: {
    fontSize: Theme.typography.bodyMd.fontSize,
    fontWeight: '600',
    color: Theme.colors.card,
  },
  // Filter modal
  filterModal: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.xl,
    margin: Theme.spacing.xl,
  },
  filterOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 14,
    borderRadius: Theme.radius.md,
    marginTop: Theme.spacing.sm,
    backgroundColor: Theme.colors.background,
  },
  filterOptionActive: {
    backgroundColor: Theme.colors.primary + '15',
    borderWidth: 1,
    borderColor: Theme.colors.primary,
  },
  filterDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  filterOptionText: {
    fontSize: Theme.typography.bodyMd.fontSize,
    color: Theme.colors.text,
    fontWeight: '500',
  },
  filterOptionTextActive: {
    color: Theme.colors.primary,
    fontWeight: '600',
  },
});
