import { StyleSheet , Platform} from 'react-native';
import {Theme, C, colors} from '../../../theme/tokens';

export const studentMarksStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.colors.background,
  },
  pageBody: {
  },
  header: {
    backgroundColor: C.colors.primary,
    paddingHorizontal: Theme.spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: C.colors.card,
    ...Theme.typography.h3,
    textAlign: 'center',
  },
  notificationIcon: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollView: {
    flex: 1,
  },
  contentContainer: {
    paddingBottom: 40,
    paddingTop: Theme.spacing.md,
  },
  mainCard: {
    backgroundColor: C.colors.card,
    marginHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    ...C.shadow.sm,
    minHeight: 200,
    marginTop: 10,
  },
  summaryCard: {
    backgroundColor: C.colors.card,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    ...C.shadow.sm,
  },
  summaryIconContainer: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.md,
    backgroundColor: C.colors.blueLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: Theme.spacing.md,
  },
  summaryContent: {
    flex: 1,
  },
  summaryLabel: {
    ...Theme.typography.caption,
    color: C.colors.textSec,
    marginBottom: 2,
    fontWeight: '600',
  },
  summaryValue: {
    fontSize: Theme.typography.h3.fontSize,
    color: C.colors.primary,
    fontWeight: '700',
  },
  trendContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: Theme.spacing.xs,
    gap: Theme.spacing.xs,
  },
  trendText: {
    ...Theme.typography.label,
    fontWeight: '700',
  },
  selectLabel: {
    ...Theme.typography.caption,
    color: C.colors.textSec,
    marginBottom: Theme.spacing.xs,
    fontWeight: '600',
  },
  examSelectionRow: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
    marginBottom: Theme.spacing.md,
  },
  dropdownButton: {
    flex: 1,
    height: 44,
    backgroundColor: C.colors.background,
    borderRadius: Theme.radius.sm,
    borderWidth: 1,
    borderColor: C.colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
  },
  dropdownText: {
    ...Theme.typography.body,
    color: C.colors.primary,
    fontWeight: '500',
  },
  dropdownPlaceholder: {
    color: C.colors.textMuted,
  },
  viewMarksButton: {
    backgroundColor: C.colors.blue,
    borderRadius: Theme.radius.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Theme.spacing.md,
    height: 44,
  },
  viewMarksText: {
    color: C.colors.card,
    ...Theme.typography.body,
    fontWeight: 'bold',
  },
  refreshIcon: {
    marginRight: Theme.spacing.sm,
  },
  subjectListContainer: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: C.colors.border,
    borderRadius: Theme.radius.md,
    overflow: 'hidden',
  },
  subjectListHeader: {
    flexDirection: 'row',
    backgroundColor: C.colors.background,
    borderBottomWidth: 1,
    borderBottomColor: C.colors.border,
    paddingVertical: 10,
    paddingHorizontal: Theme.spacing.sm,
  },
  subjectListHeaderCell: {
    ...Theme.typography.label,
    textTransform: 'uppercase',
    color: C.colors.textMuted,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  subjectListRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: C.colors.backgroundAlt,
  },
  subjectListRowAlt: {
    backgroundColor: C.colors.cardAlt,
  },
  subjectListCell: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.colors.primary,
    fontWeight: '600',
  },
  subjectCol: {
    flex: 2.2,
  },
  maxCol: {
    flex: 1,
    textAlign: 'center',
  },
  passCol: {
    flex: 1,
    textAlign: 'center',
  },
  obtainedCol: {
    flex: 1,
    textAlign: 'center',
  },
  resultCol: {
    flex: 1.4,
    alignItems: 'flex-end',
  },
  resultCellWrap: {
    justifyContent: 'center',
  },
  marksGrid: {
    gap: Theme.spacing.md,
  },
  gridRow: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
    marginBottom: Theme.spacing.sm,
  },
  gridItem: {
    flex: 1,
    backgroundColor: C.colors.background,
    borderRadius: Theme.radius.sm,
    padding: 10,
    borderWidth: 1,
    borderColor: C.colors.backgroundAlt,
  },
  gridLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: C.colors.textMuted,
    marginBottom: 2,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  gridValue: {
    ...Theme.typography.bodyMd,
    fontWeight: '700',
    color: C.colors.primary,
  },
  marksCard: {
    backgroundColor: C.colors.card,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    ...C.shadow.sm,
  },
  marksCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: Theme.spacing.md,
  },
  subjectContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: Theme.spacing.md,
  },
  subjectIcon: {
    width: 32,
    height: 32,
    borderRadius: Theme.radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  subjectName: {
    ...Theme.typography.bodyMd,
    color: C.colors.primary,
    fontWeight: '700',
    flexShrink: 1,
  },
  marksDetails: {
    gap: Theme.spacing.md,
  },
  marksRow: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
  },
  marksItem: {
    flex: 1,
    backgroundColor: C.colors.background,
    borderRadius: Theme.radius.sm,
    padding: 10,
    borderWidth: 1,
    borderColor: C.colors.backgroundAlt,
  },
  marksLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: C.colors.textMuted,
    marginBottom: 2,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  marksValue: {
    ...Theme.typography.bodyMd,
    fontWeight: '700',
    color: C.colors.primary,
  },
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
  },
  progressBar: {
    flex: 1,
    height: 8,
    borderRadius: Theme.radius.full,
    backgroundColor: C.colors.border,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: Theme.radius.full,
  },
  percentageText: {
    width: 52,
    textAlign: 'right',
    ...Theme.typography.caption,
    fontWeight: '700',
    color: C.colors.textSec,
  },
  resultContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Theme.spacing.md,
  },
  remarksContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  remarksText: {
    flex: 1,
    ...Theme.typography.caption,
    color: C.colors.textSec,
  },
  resultBadgeContainer: {
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: Theme.radius.sm,
    alignSelf: 'flex-start',
    marginTop: 2,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.sm,
    gap: Theme.spacing.xs,
    alignSelf: 'flex-start',
    marginTop: 2,
  },
  badgePass: {
    backgroundColor: C.colors.successBg,
  },
  badgeFail: {
    backgroundColor: C.colors.errorBg,
  },
  badgeText: {
    ...Theme.typography.caption,
    fontWeight: '700',
  },
  badgeTextPass: {
    color: C.colors.success,
  },
  badgeTextFail: {
    color: C.colors.error,
  },
  // grading styles removed
  emptyResults: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  emptyResultsText: {
    ...Theme.typography.body,
    color: C.colors.textMuted,
    textAlign: 'center',
    marginTop: Theme.spacing.md,
    lineHeight: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: '#00000080',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: C.colors.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '90%',
    minHeight: 420,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Theme.spacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: C.colors.borderLight,
    backgroundColor: C.colors.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  modalTitle: {
    ...Theme.typography.h3,
    color: C.colors.primary,
  },
  modalScrollContainer: {
    flex: 1,
    maxHeight: 600,
  },
  modalScrollView: {
    flex: 1,
  },
  modalScrollContent: {
    paddingHorizontal: Theme.spacing.xl,
    paddingTop: 10,
    paddingBottom: Platform.OS === 'ios' ? 30 : 20,
  },
  modalList: {
    flexGrow: 0,
  },
  modalItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: C.colors.background,
  },
  modalItemSelected: {
    backgroundColor: C.colors.blueLight,
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.md,
    marginHorizontal: -12,
  },
  modalItemText: {
    fontSize: Theme.typography.h4.fontSize,
    color: C.colors.primary,
    fontWeight: '500',
    flex: 1,
  },
  modalItemTextSelected: {
    color: C.colors.blue,
    fontWeight: 'bold',
  },
});
