import { StyleSheet } from 'react-native';
import {Theme, colors} from '../../../theme/tokens';

export const principalRegistrationStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.colors.background,
  },
  limitCheckingText: {
    fontSize: Theme.typography.body.fontSize,
    color: Theme.colors.textSec,
    fontWeight: '600',
    padding: Theme.spacing.lg,
    textAlign: 'center',
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    padding: Theme.spacing.md,
    paddingBottom: 150,
  },
  formCard: {
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.8)',
    shadowColor: Theme.colors.primary,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 8,
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.xl,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Theme.spacing.xl,
    paddingVertical: 18,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.background,
    backgroundColor: Theme.colors.background,
  },
  cardTitle: {
    fontSize: Theme.typography.h4.fontSize,
    fontWeight: '700',
    color: Theme.colors.text,
  },
  cardBadges: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
    marginTop: 6,
  },
  cardBadge: {
    backgroundColor: '#eff6ff',
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: 2,
    borderRadius: Theme.radius.sm,
  },
  cardBadgeText: {
    fontSize: Theme.typography.label.fontSize,
    color: Theme.colors.blue,
    fontWeight: '600',
  },
  copyLinkBtn: {
    backgroundColor: 'rgba(59, 130, 246, 0.08)',
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.radius.sm,
  },
  copyLinkBtnText: {
    color: Theme.colors.blue,
    ...Theme.typography.caption,
    fontWeight: '600',
  },
  linkBanner: {
    backgroundColor: '#fffbeb',
    padding: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: '#fde68a',
  },
  linkBannerText: {
    ...Theme.typography.caption,
    color: '#92400e',
  },
  linkBannerLabel: {
    fontWeight: 'bold',
  },
  formBody: {
    padding: Theme.spacing.xl,
  },
  sectionTitle: {
    ...Theme.typography.caption,
    fontWeight: '800',
    color: Theme.colors.success,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: Theme.spacing.md,
  },
  formGroup: {
    marginBottom: Theme.spacing.md,
  },
  label: {
    ...Theme.typography.caption,
    fontWeight: '600',
    color: Theme.colors.textSec,
    marginBottom: 6,
  },
  required: {
    color: Theme.colors.error,
  },
  input: {
    borderWidth: 1,
    borderColor: Theme.colors.textSec,
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 14,
    ...Theme.typography.body,
    backgroundColor: Theme.colors.background,
    color: Theme.colors.text,
  },
  inputFocused: {
    borderColor: Theme.colors.primary,
    backgroundColor: Theme.colors.background,
    shadowColor: Theme.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  inputError: {
    borderColor: Theme.colors.error,
    backgroundColor: '#fff8f8',
  },
  errorText: {
    ...Theme.typography.label,
    color: Theme.colors.error,
    marginTop: Theme.spacing.xs,
  },
  verifyBtn: {
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.xl,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.primary,
  },
  verifyBtnDisabled: {
    opacity: 0.6,
  },
  verifyBtnText: {
    color: Theme.colors.card,
    fontWeight: '600',
    fontSize: Theme.typography.caption.fontSize,
  },
  verifyOtpBtn: {
    backgroundColor: Theme.colors.success,
  },
  pickerContainer: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
  },
  pickerOption: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.background,
    borderWidth: 1.5,
    borderColor: Theme.colors.textSec,
    alignItems: 'center',
  },
  pickerOptionActive: {
    backgroundColor: Theme.colors.primary,
    borderColor: Theme.colors.primary,
    shadowColor: Theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
  },
  pickerText: {
    ...Theme.typography.body,
    fontWeight: '600',
    color: Theme.colors.textSec,
  },
  pickerTextActive: {
    color: Theme.colors.card,
    fontWeight: '700',
  },
  warningBox: {
    backgroundColor: '#fef2f2',
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.md,
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  warningText: {
    color: Theme.colors.error,
    fontSize: Theme.typography.caption.fontSize,
    marginBottom: Theme.spacing.xs,
  },
  classCard: {
    backgroundColor: Theme.colors.card,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
  },
  classHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
  },
  classNumber: {
    width: 32,
    height: 32,
    borderRadius: Theme.radius.sm,
    backgroundColor: Theme.colors.blueLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  classNumberText: {
    ...Theme.typography.caption,
    fontWeight: '800',
    color: Theme.colors.primary,
  },
  classNameField: {
    flex: 1,
  },
  removeClassBtn: {
    padding: 6,
    backgroundColor: Theme.colors.redLight,
    borderRadius: Theme.radius.sm,
  },
  removeClassBtnText: {
    ...Theme.typography.body,
  },
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
  },
  sectionInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: Theme.colors.textSec,
    borderRadius: Theme.radius.md,
    paddingHorizontal: 14,
    paddingVertical: Theme.spacing.md,
    ...Theme.typography.body,
    backgroundColor: Theme.colors.background,
    color: Theme.colors.text,
  },
  sectionInputFocused: {
    borderColor: Theme.colors.primary,
    backgroundColor: Theme.colors.background,
    shadowColor: Theme.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  removeSectionBtn: {
    width: 32,
    height: 32,
    borderRadius: Theme.radius.lg,
    backgroundColor: Theme.colors.redLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeSectionBtnText: {
    ...Theme.typography.body,
    color: Theme.colors.error,
  },
  addSectionBtn: {
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.md,
    backgroundColor: Theme.colors.blueLight,
    borderRadius: Theme.radius.md,
    alignSelf: 'flex-start',
  },
  addSectionBtnText: {
    ...Theme.typography.caption,
    fontWeight: '700',
    color: Theme.colors.primary,
  },
  addClassBtn: {
    width: '100%',
    paddingVertical: 14,
    backgroundColor: Theme.colors.background,
    borderWidth: 2,
    borderColor: Theme.colors.border,
    borderStyle: 'dashed',
    borderRadius: Theme.radius.md,
    alignItems: 'center',
  },
  addClassBtnText: {
    ...Theme.typography.body,
    fontWeight: '600',
    color: Theme.colors.textSec,
  },
  formFooter: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    marginTop: Theme.spacing.lg,
    paddingTop: Theme.spacing.xl,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.border,
  },
  hintBox: {
    marginTop: Theme.spacing.md,
    marginHorizontal: Theme.spacing.xl,
    marginBottom: Theme.spacing.xl,
    padding: 14,
    backgroundColor: '#eff6ff',
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.blueLight,
    alignItems: 'center',
  },
  hintText: {
    ...Theme.typography.caption,
    color: Theme.colors.primaryDark,
    textAlign: 'center',
    lineHeight: 18,
    fontWeight: '500',
  },
  footer: {
    marginTop: Theme.spacing.xl,
    marginHorizontal: Theme.spacing.md,
    padding: Theme.spacing.md,
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: Theme.spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 2,
  },
  footerText: {
    ...Theme.typography.caption,
    color: Theme.colors.textSec,
    fontWeight: '600',
  },
  toast: {
    position: 'absolute',
    top: 60,
    left: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
    zIndex: 1000,
    gap: 10,
  },
  toastSuccess: {
    borderLeftWidth: 4,
    borderLeftColor: Theme.colors.success,
  },
  toastError: {
    borderLeftWidth: 4,
    borderLeftColor: Theme.colors.error,
  },
  toastIcon: {
    fontSize: Theme.typography.h3.fontSize,
  },
  toastMessage: {
    flex: 1,
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.text,
  },
  toastClose: {
    fontSize: Theme.typography.h4.fontSize,
    color: Theme.colors.textMuted,
    padding: Theme.spacing.xs,
  },
});
