import { StyleSheet } from 'react-native';
import {Theme, colors} from '../../../theme/tokens';

export const adminAgentsStyles = StyleSheet.create({
  screenContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Theme.spacing.xl,
  },
  modalContent: {
    width: '100%',
    maxHeight: '90%',
    backgroundColor: colors.surface,
    borderRadius: Theme.radius.xl,
    overflow: 'hidden',
    flexDirection: 'column',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 15,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Theme.spacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalTitle: { ...Theme.typography.h3, color: colors.textPrimary },
  modalClose: { padding: Theme.spacing.xs },
  modalBodyScroll: {
    flexGrow: 0,
    flexShrink: 1,
  },
  modalBodyContent: {
    padding: Theme.spacing.xl,
    paddingBottom: Theme.spacing.sm,
  },
  modalFooter: { flexDirection: 'row', gap: Theme.spacing.md, padding: Theme.spacing.xl, borderTopWidth: 1, borderTopColor: colors.border },
  formGroup: { marginBottom: Theme.spacing.md },
  formLabel: { fontSize: Theme.typography.caption.fontSize, fontWeight: '600', color: colors.textPrimary, marginBottom: 6 },
  formInput: { backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border, borderRadius: Theme.radius.sm, padding: Theme.spacing.md, ...Theme.typography.body, color: colors.textPrimary },
  formInputError: { borderColor: colors.error },
  formError: { ...Theme.typography.label, color: colors.error, marginTop: Theme.spacing.xs },
  switchRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  switchLabel: { ...Theme.typography.body, color: colors.textPrimary },
  searchContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border, borderRadius: Theme.radius.sm, paddingHorizontal: Theme.spacing.md, height: 40, flex: 1 },
  searchInput: { flex: 1, ...Theme.typography.body, color: colors.textPrimary, padding: 0 },
  clearBtn: { padding: Theme.spacing.xs },
  agentCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: Theme.colors.background,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.md,
    marginBottom: 14,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  cardInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(30, 58, 138, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(30, 58, 138, 0.15)',
  },
  avatarText: {
    ...Theme.typography.body,
    fontWeight: 'bold',
    color: colors.primary,
  },
  agentName: {
    fontSize: Theme.typography.h4.fontSize,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  agentUsername: {
    ...Theme.typography.caption,
    color: colors.textMuted,
    marginTop: 1,
  },
  emailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: Theme.spacing.xs,
  },
  agentEmail: {
    ...Theme.typography.caption,
    color: colors.textMuted,
  },
  agentEditBtn: {
    padding: Theme.spacing.sm,
    backgroundColor: 'rgba(30, 58, 138, 0.06)',
    borderRadius: Theme.radius.sm,
    borderWidth: 1,
    borderColor: 'rgba(30, 58, 138, 0.1)',
  },
  statusBadge: {
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: Theme.radius.sm,
  },
  statusText: {
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '700',
  },
  capabilitiesWrapper: {
    marginTop: Theme.spacing.md,
    paddingTop: Theme.spacing.md,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.background,
  },
  capTitle: {
    ...Theme.typography.label,
    fontWeight: '700',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  capabilitiesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  capTag: {
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.sm,
  },
  capTagText: {
    ...Theme.typography.label,
    fontWeight: '600',
  },
  cardActionsRow: {
    marginTop: 14,
  },
  statusToggleBtn: {
    width: '100%',
    height: 36,
    borderRadius: Theme.radius.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  btnDeactivate: {
    borderColor: colors.errorSoft,
    backgroundColor: colors.errorSoft,
  },
  btnActivate: {
    borderColor: colors.successSoft,
    backgroundColor: colors.successSoft,
  },
  actionBtnText: {
    ...Theme.typography.caption,
    fontWeight: '700',
  },
});
