import { StyleSheet, Platform } from 'react-native';
import {Theme, C, colors} from '../../../theme/tokens';
import { HEADER_CONSTANTS } from '../../../constants/headerConstants';
import { PICKER_TEXT } from './types';

export const studentPromotionStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Theme.colors.background },
  scrollContent: {
    paddingTop: Theme.spacing.xl,
    paddingBottom: 100,
    paddingHorizontal: HEADER_CONSTANTS.PADDING_HORIZONTAL,
  },
  tabBarWrap: {
    marginBottom: Theme.spacing.md,
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    padding: 5,
    ...Platform.select({
      android: { elevation: 3 },
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 8,
      },
    }),
  },
  tabBarScroll: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.xs,
    paddingHorizontal: 2,
  },
  tabPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
  },
  tabPillActive: {
    backgroundColor: Theme.colors.primary,
  },
  tabPillText: { fontSize: Theme.typography.caption.fontSize, color: Theme.colors.textSec },
  tabPillTextActive: { color: Theme.colors.card },
  yearRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
  },
  smallBtn: {
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.radius.sm,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    backgroundColor: Theme.colors.background,
  },
  smallBtnDanger: { borderColor: '#fecaca', backgroundColor: '#fef2f2' },
  smallBtnText: { fontSize: Theme.typography.caption.fontSize, color: Theme.colors.primary },
  smallBtnTextSuccess: { fontSize: Theme.typography.caption.fontSize, color: Theme.colors.success },
  smallBtnTextDanger: { fontSize: Theme.typography.caption.fontSize, color: Theme.colors.error },
  historyActions: { flexDirection: 'row', gap: Theme.spacing.sm, marginTop: 10 },
  transitionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.border,
  },
  settingRuleCard: {
    marginBottom: Theme.spacing.md,
    paddingBottom: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Theme.spacing.md,
  },
  statusText: { color: Theme.colors.primary, fontWeight: '700' },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    padding: Theme.spacing.xl,
  },
  modalCard: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  stepBarWrap: {
    marginTop: Theme.spacing.xs,
    marginBottom: 18,
    position: 'relative',
  },
  stepBarTrack: {
    position: 'absolute',
    top: 14,
    left: '12%',
    right: '12%',
    height: 2,
    backgroundColor: Theme.colors.border,
    zIndex: 0,
  },
  stepBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 0,
    zIndex: 1,
  },
  stepItem: { alignItems: 'center', flex: 1, minWidth: 0 },
  stepDot: {
    width: 28,
    height: 28,
    borderRadius: Theme.radius.md,
    borderWidth: 2,
    borderColor: Theme.colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Theme.colors.card,
  },
  stepDotActive: { borderColor: Theme.colors.primary, backgroundColor: Theme.colors.primary },
  stepDotDone: { borderColor: Theme.colors.success, backgroundColor: Theme.colors.success },
  stepDotText: { fontSize: Theme.typography.caption.fontSize, fontWeight: '700', color: Theme.colors.textSec },
  stepDotTextActive: { color: Theme.colors.card },
  stepLabel: { fontSize: Theme.typography.label.fontSize, color: Theme.colors.textSec, marginTop: 6, fontWeight: '600', textAlign: 'center' },
  stepLabelActive: { color: Theme.colors.primary },
  card: {
    marginBottom: Theme.spacing.md,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    backgroundColor: Theme.colors.card,
  },
  cardTitle: { fontSize: Theme.typography.h4.fontSize, color: Theme.colors.text, marginBottom: 6 },
  cardHint: { fontSize: Theme.typography.caption.fontSize, color: Theme.colors.textSec, marginBottom: Theme.spacing.md, lineHeight: 18 },
  fieldGroup: { marginBottom: 14 },
  fieldLabel: { fontSize: Theme.typography.caption.fontSize, fontWeight: '700', color: Theme.colors.text, marginBottom: Theme.spacing.sm },
  pickerWrap: {
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.inputBg,
    overflow: 'hidden',
    minHeight: Platform.OS === 'ios' ? 48 : 52,
    justifyContent: 'center',
  },
  picker: {
    color: PICKER_TEXT,
    marginHorizontal: Platform.OS === 'android' ? -4 : 0,
  },
  pickerItem: {
    color: PICKER_TEXT,
    fontSize: Theme.typography.h4.fontSize,
  },
  pickerDisabled: {
    backgroundColor: Theme.colors.backgroundAlt,
  },
  staticField: {
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.backgroundAlt,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  staticFieldText: {
    fontSize: Theme.typography.body.fontSize,
    color: Theme.colors.textSec,
  },
  statsRow: { flexDirection: 'row', gap: 10, marginBottom: Theme.spacing.md },
  statCard: {
    flex: 1,
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    alignItems: 'center',
  },
  statValue: { fontSize: Theme.typography.h3.fontSize, color: Theme.colors.text },
  statLabel: { fontSize: Theme.typography.label.fontSize, color: Theme.colors.textSec, marginTop: 2 },
  previewHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  linkText: { color: Theme.colors.primary, fontWeight: '700', fontSize: Theme.typography.caption.fontSize },
  studentList: { maxHeight: 320, marginBottom: 14 },
  studentRow: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
    gap: Theme.spacing.sm,
  },
  studentName: { fontSize: Theme.typography.body.fontSize, color: Theme.colors.text },
  studentMeta: { fontSize: Theme.typography.caption.fontSize, color: Theme.colors.textSec, marginTop: 2 },
  actionChips: { flexDirection: 'row', gap: 6 },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: Theme.radius.sm,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    backgroundColor: Theme.colors.background,
  },
  chipActive: { backgroundColor: Theme.colors.primary, borderColor: Theme.colors.primary },
  chipText: { fontSize: Theme.typography.label.fontSize, fontWeight: '700', color: Theme.colors.textSec },
  chipTextActive: { color: Theme.colors.card },
  input: {
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    paddingHorizontal: 14,
    paddingVertical: Theme.spacing.md,
    fontSize: Theme.typography.body.fontSize,
    color: Theme.colors.text,
    backgroundColor: Theme.colors.card,
    marginBottom: 14,
  },
  confirmStats: { flexDirection: 'row', alignItems: 'center', gap: Theme.spacing.sm, marginBottom: Theme.spacing.md },
  confirmStatsText: { fontSize: Theme.typography.body.fontSize, color: Theme.colors.text, flex: 1 },
  confirmActions: { flexDirection: 'row' },
  doneIcon: { alignSelf: 'center', marginBottom: Theme.spacing.md },
  doneTitle: { fontSize: Theme.typography.h3.fontSize, textAlign: 'center', marginBottom: Theme.spacing.sm, color: Theme.colors.text },
  historyCard: { marginBottom: 10, padding: 14 },
  historyName: { fontSize: Theme.typography.bodyMd.fontSize, color: Theme.colors.text },
  historyMeta: { fontSize: Theme.typography.caption.fontSize, color: Theme.colors.textSec, marginTop: Theme.spacing.xs },
  historyDate: { fontSize: Theme.typography.label.fontSize, color: Theme.colors.textSec, marginTop: Theme.spacing.xs },
  emptyTitle: { fontSize: Theme.typography.h4.fontSize, textAlign: 'center', marginBottom: Theme.spacing.sm },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Theme.spacing.sm,
    backgroundColor: '#fef2f2',
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  errorText: { flex: 1, fontSize: Theme.typography.caption.fontSize, color: Theme.colors.error },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15,23,42,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
