export const tokens = {
  colors: {
    light: {
      primary: '#1e3a8a', // Navy
      primaryDark: '#172554',
      primaryLight: '#3b82f6',
      secondary: '#38bdf8',
      accent: '#1e3a8a',
      background: '#f5f7fa',
      backgroundAlt: '#eef2f8',
      card: '#ffffff',
      cardAlt: '#f7f9fc',
      text: '#0d1b2a',
      textSec: '#4a5568',
      textMuted: '#8898aa',
      border: '#e4e9f2',
      borderLight: 'rgba(148,163,184,0.18)',
      success: '#059669',
      successBg: 'rgba(5,150,105,0.1)',
      warning: '#d97706',
      warningBg: 'rgba(217,119,6,0.1)',
      error: '#dc2626',
      errorBg: 'rgba(220,38,38,0.1)',
      info: '#0ea5e9',
      infoBg: 'rgba(14,165,233,0.1)',
      blue: '#3b82f6',
      blueLight: '#dbeafe',
      violet: '#7c3aed',
      violetLight: '#ede9fe',
      green: '#059669',
      greenLight: '#d1fae5',
      amber: '#d97706',
      amberLight: '#fef3c7',
      red: '#dc2626',
      redLight: '#fee2e2',
      sky: '#38bdf8',
      skyLight: '#e0f2fe',
      gradientStart: '#1e3a8a',
      gradientEnd: '#3b82f6',
      gradientBlue: '#38bdf8',
      inputBg: '#f8fafc',
      // Role Accents (Unified Navy Blue)
      accentDirector: '#1e3a8a',
      accentPrincipal: '#1e3a8a',
      accentTeacher: '#1e3a8a',
      accentStudent: '#1e3a8a',
      accentAccountant: '#1e3a8a',
    },
    dark: {
      primary: '#3b82f6',
      primaryDark: '#1e3a8a',
      primaryLight: '#60a5fa',
      secondary: '#38bdf8',
      accent: '#3b82f6',
      background: '#0f172a',
      backgroundAlt: '#1e293b',
      card: '#1e293b',
      cardAlt: '#334155',
      text: '#f8fafc',
      textSec: '#cbd5e1',
      textMuted: '#94a3b8',
      border: '#334155',
      borderLight: 'rgba(255,255,255,0.1)',
      success: '#34d399',
      successBg: 'rgba(52,211,153,0.1)',
      warning: '#fbbf24',
      warningBg: 'rgba(251,191,36,0.1)',
      error: '#f87171',
      errorBg: 'rgba(248,113,113,0.1)',
      info: '#38bdf8',
      infoBg: 'rgba(56,189,248,0.1)',
      blue: '#60a5fa',
      blueLight: '#1d4ed8',
      violet: '#a78bfa',
      violetLight: '#5b21b6',
      green: '#34d399',
      greenLight: '#065f46',
      amber: '#fbbf24',
      amberLight: '#92400e',
      red: '#f87171',
      redLight: '#991b1b',
      sky: '#7dd3fc',
      skyLight: '#0369a1',
      gradientStart: '#1e3a8a',
      gradientEnd: '#3b82f6',
      gradientBlue: '#38bdf8',
      inputBg: '#1e293b',
      // Role Accents (Unified Navy Blue)
      accentDirector: '#3b82f6',
      accentPrincipal: '#3b82f6',
      accentTeacher: '#3b82f6',
      accentStudent: '#3b82f6',
      accentAccountant: '#3b82f6',
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 36,
    full: 999,
  },
  shadow: {
    sm: {
      shadowColor: '#1e3a8a',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 2,
    },
    md: {
      shadowColor: '#1e3a8a',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 12,
      elevation: 4,
    },
    lg: {
      shadowColor: '#1e3a8a',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.18,
      shadowRadius: 20,
      elevation: 8,
    },
  },
  typography: {
    h1: { fontSize: 28, fontWeight: '800' as const, letterSpacing: -0.8 },
    h2: { fontSize: 22, fontWeight: '700' as const, letterSpacing: -0.5 },
    h3: { fontSize: 18, fontWeight: '700' as const, letterSpacing: -0.3 },
    h4: { fontSize: 16, fontWeight: '600' as const },
    body: { fontSize: 14, fontWeight: '400' as const, lineHeight: 22 },
    bodyMd: { fontSize: 15, fontWeight: '400' as const, lineHeight: 24 },
    caption: { fontSize: 12, fontWeight: '500' as const },
    label: { fontSize: 11, fontWeight: '700' as const, letterSpacing: 0.8, textTransform: 'uppercase' as const },
  },
};

import { buildTheme, lightTheme } from './buildTheme';

/** Static light theme — prefer `useTheme()` from ThemeContext for runtime dark mode. */
export const Theme = lightTheme;

export const createTheme = buildTheme;

export const C = Theme;

export const colors = {
  primary: Theme.colors.primary,
  secondary: Theme.colors.secondary,
  bg: Theme.colors.background,
  surface: Theme.colors.card,
  textPrimary: Theme.colors.text,
  textMuted: Theme.colors.textMuted,
  border: Theme.colors.border,
  accent: Theme.colors.primary,
  accentSoft: Theme.colors.violetLight,
  success: Theme.colors.success,
  successSoft: Theme.colors.successBg,
  warning: Theme.colors.warning,
  warningSoft: Theme.colors.warningBg,
  error: Theme.colors.error,
  errorSoft: Theme.colors.errorBg,
  danger: Theme.colors.error,
  background: Theme.colors.background,
};

