import { StyleSheet } from 'react-native';
import {Theme, colors} from '../../../theme/tokens';

export const questionPaperStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Theme.colors.background },
  pageBody: { paddingBottom: 96 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: Theme.spacing.sm },
  toolbarCard: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
    ...Theme.shadow.sm,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    paddingHorizontal: Theme.spacing.md,
    height: 48,
    gap: Theme.spacing.sm,
    marginBottom: Theme.spacing.md,
  },
  searchInput: {
    flex: 1,
    ...Theme.typography.body,
    color: Theme.colors.text,
    paddingVertical: 0,
  },
  filterScroll: { marginTop: Theme.spacing.xs },
  filterRow: { flexDirection: 'row', gap: Theme.spacing.sm },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.radius.full,
    backgroundColor: Theme.colors.background,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  filterChipActive: {
    backgroundColor: Theme.colors.primary,
    borderColor: Theme.colors.primary,
  },
  filterText: { fontSize: Theme.typography.body.fontSize, color: Theme.colors.text },
  filterTextActive: { color: Theme.colors.card },
  loaderWrap: { paddingVertical: Theme.spacing.xxl, alignItems: 'center', gap: Theme.spacing.md },
  loaderText: { color: Theme.colors.textMuted },
  errorCard: { padding: Theme.spacing.lg, alignItems: 'center', gap: Theme.spacing.sm },
  errorTitle: { color: Theme.colors.text, fontSize: Theme.typography.h4.fontSize, marginTop: Theme.spacing.xs },
  errorText: { color: Theme.colors.textMuted, textAlign: 'center', ...Theme.typography.body },
  retryBtn: {
    marginTop: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.xl,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.primary,
  },
  retryBtnText: { color: Theme.colors.card },
  emptyCard: { padding: 28, alignItems: 'center', gap: Theme.spacing.sm },
  emptyTitle: { color: Theme.colors.text, marginTop: Theme.spacing.xs },
  emptyText: { color: Theme.colors.textMuted, textAlign: 'center', ...Theme.typography.body },
  uploadEmptyBtn: {
    marginTop: Theme.spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.xl,
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.primary,
  },
  uploadEmptyBtnText: { color: Theme.colors.card },
  paperCard: { padding: Theme.spacing.xl, marginBottom: Theme.spacing.md },
  paperTop: { flexDirection: 'row', alignItems: 'center', marginBottom: Theme.spacing.sm },
  paperIconWrap: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.md,
    backgroundColor: '#eef2ff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  typeBadge: {
    marginLeft: 'auto',
    paddingHorizontal: 10,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.full,
    backgroundColor: '#eef2ff',
  },
  typeBadgeText: { fontSize: Theme.typography.label.fontSize, color: Theme.colors.primary },
  paperTitle: { fontSize: Theme.typography.h4.fontSize, color: Theme.colors.text, marginBottom: Theme.spacing.sm },
  paperMeta: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: Theme.spacing.sm, marginBottom: Theme.spacing.sm },
  metaItem: { flexDirection: 'row', alignItems: 'center', gap: Theme.spacing.xs },
  metaText: { ...Theme.typography.caption, color: Theme.colors.textMuted },
  paperDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    paddingTop: Theme.spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.border,
    marginBottom: Theme.spacing.md,
  },
  detailItem: { flexDirection: 'row', alignItems: 'center', gap: Theme.spacing.xs },
  detailText: { ...Theme.typography.caption, color: Theme.colors.textMuted },
  paperActions: {
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: Theme.colors.border,
    paddingTop: Theme.spacing.md,
  },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: Theme.spacing.xs,
    paddingVertical: Theme.spacing.sm,
  },
  actionText: { fontSize: Theme.typography.caption.fontSize, color: Theme.colors.primary },
  actionTextDanger: { fontSize: Theme.typography.caption.fontSize, color: Theme.colors.error },
  actionDivider: { width: 1, height: 20, backgroundColor: Theme.colors.border },
  processingRow: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    paddingVertical: Theme.spacing.sm,
  },
  processingText: { color: Theme.colors.textMuted, ...Theme.typography.body },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Theme.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    ...Theme.shadow.md,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    maxHeight: '92%',
    backgroundColor: Theme.colors.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: Theme.spacing.xl,
    paddingTop: Theme.spacing.xl,
    paddingBottom: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
    gap: Theme.spacing.md,
  },
  modalTitle: { fontSize: Theme.typography.h3.fontSize, color: Theme.colors.text },
  modalSubtitle: { marginTop: Theme.spacing.xs, color: Theme.colors.textMuted, ...Theme.typography.caption },
  modalCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: Theme.radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Theme.colors.background,
  },
  modalScroll: { maxHeight: 520 },
  modalScrollContent: { padding: Theme.spacing.xl, paddingBottom: Theme.spacing.sm },
  modalLoader: { paddingVertical: Theme.spacing.xl, alignItems: 'center', gap: 10 },
  modalFooter: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    padding: Theme.spacing.xl,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.border,
  },
  modalFooterBtn: { flex: 1 },
  formGroup: { marginBottom: 14 },
  formLabel: { fontSize: Theme.typography.caption.fontSize, color: Theme.colors.text, marginBottom: 6 },
  pickerField: {
    minHeight: 48,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    backgroundColor: Theme.colors.background,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pickerValue: { flex: 1, color: Theme.colors.text, ...Theme.typography.body },
  pickerPlaceholder: { color: Theme.colors.textMuted },
  textInput: {
    minHeight: 48,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    backgroundColor: Theme.colors.background,
    paddingHorizontal: 14,
    color: Theme.colors.text,
    ...Theme.typography.body,
  },
  textArea: { minHeight: 88, paddingTop: Theme.spacing.md, paddingBottom: Theme.spacing.md },
  filePickBox: {
    minHeight: 72,
    borderRadius: Theme.radius.md,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: Theme.colors.border,
    backgroundColor: Theme.colors.background,
    paddingHorizontal: 14,
    paddingVertical: Theme.spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  filePickText: { flex: 1, color: Theme.colors.textMuted, ...Theme.typography.body },
  fieldError: { marginTop: Theme.spacing.xs, color: Theme.colors.error, fontSize: Theme.typography.caption.fontSize },
});
