require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

platform :ios, '15.1'

# Enable New Architecture (Required for Reanimated 4.x)
ENV['RCT_NEW_ARCH_ENABLED'] = '1'

target 'AttendX' do
  config = use_native_modules!
  
  # Ensure these are found in the New Architecture
  pod 'RNWorklets', :path => '../node_modules/react-native-worklets'
  pod 'react-native-worklets-core', :path => '../node_modules/react-native-worklets-core'
  
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => true
  )
end

post_install do |installer|
  react_native_post_install(installer)
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
      
      # Fix for React-Core
      if target.name == 'React-Core'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEBUG=1'
      end
    end
  end
end
