import { StyleSheet, Platform, Dimensions } from 'react-native';
import {Theme, C, colors} from '../../../theme/tokens';
import { HEADER_CONSTANTS } from '../../../constants/headerConstants';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const CARD_SHADOW = Platform.select({
  ios: {
    shadowColor: Theme.colors.text,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
  },
  android: { elevation: 2 },
});

export const principalDashboardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },
  headerStandard: {
    backgroundColor: C.navy,
    paddingHorizontal: Theme.spacing.xl,
    paddingBottom: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: Theme.colors.card,
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
  },
  refreshIconBtn: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: Theme.radius.lg,
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.xl,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  badge: { position: 'absolute', top: -2, right: -2, minWidth: 18, height: 18, borderRadius: 9, backgroundColor: Theme.colors.error, justifyContent: 'center', alignItems: 'center', paddingHorizontal: Theme.spacing.xs },
  badgeText: { color: Theme.colors.card, fontSize: Theme.typography.label.fontSize, fontWeight: '700', lineHeight: 14 },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: HEADER_CONSTANTS.DASHBOARD_HORIZONTAL,
  },
  dashboardSheet: {
    marginTop: -20,
    marginHorizontal: -HEADER_CONSTANTS.DASHBOARD_HORIZONTAL,
    paddingHorizontal: HEADER_CONSTANTS.DASHBOARD_HORIZONTAL,
    paddingTop: Theme.spacing.sm,
    paddingBottom: Theme.spacing.xs,
  },
  sectionCard: {
    backgroundColor: C.card,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
    ...CARD_SHADOW,
  },
  overviewDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: C.border,
    marginVertical: 14,
  },
  sectionHead: {
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: Theme.typography.h4.fontSize,
    color: C.text,
    letterSpacing: -0.3,
  },
  sectionSub: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.muted,
    marginTop: 2,
    marginBottom: Theme.spacing.md,
  },
  toolsGrid: {
    marginTop: Theme.spacing.md,
  },
  toolItem: {
    alignItems: 'center',
    width: '100%',
    paddingVertical: 6,
  },
  toolIcon: {
    width: 44,
    height: 44,
    borderRadius: Theme.radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  toolLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: C.textSec,
    textAlign: 'center',
    lineHeight: 14,
  },
  attendanceRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: Theme.spacing.xs,
  },
  metricCard: {
    flex: 1,
    backgroundColor: C.bg,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    gap: 5,
  },
  metricSkeleton: {
    minHeight: 108,
    backgroundColor: C.border,
  },
  metricTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  metricLabel: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.muted,
  },
  metricPct: {
    fontSize: Theme.typography.h3.fontSize,
    letterSpacing: -0.5,
  },
  metricBarTrack: {
    height: 5,
    backgroundColor: C.border,
    borderRadius: 3,
    overflow: 'hidden',
  },
  metricBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  metricValue: {
    fontSize: Theme.typography.h3.fontSize,
    color: C.text,
    letterSpacing: -0.3,
  },
  metricValueMuted: {
    fontSize: Theme.typography.body.fontSize,
    color: C.muted,
    fontWeight: '500',
  },
  metricSub: {
    fontSize: Theme.typography.label.fontSize,
    color: C.muted,
  },
  heroTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  profileAvatar: {
    width: 48,
    height: 48,
    borderRadius: Theme.radius.xxl,
    backgroundColor: 'rgba(255,255,255,0.10)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  profileAvatarText: {
    color: Theme.colors.card,
    fontSize: Theme.typography.h3.fontSize,
  },
  heroActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  heroCopy: {
    gap: Theme.spacing.xs,
    marginTop: Theme.spacing.xs,
  },
  heroGreetingLabel: {
    ...Theme.typography.caption,
    color: 'rgba(255,255,255,0.72)',
    letterSpacing: 0.5,
  },
  heroGreetingName: {
    fontSize: Theme.typography.h1.fontSize,
    color: Theme.colors.card,
    letterSpacing: -0.5,
  },
  heroSubtitle: {
    fontSize: Theme.typography.caption.fontSize,
    color: 'rgba(255,255,255,0.85)',
  },
  welcomeSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingHorizontal: Theme.spacing.md,
    paddingTop: Theme.spacing.xl,
    paddingBottom: Theme.spacing.sm,
    marginBottom: Theme.spacing.md,
    marginTop: Theme.spacing.xs,
  },
  welcomeTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: C.text,
  },
  welcomeSub: {
    ...Theme.typography.caption,
    color: C.muted,
    marginTop: 2,
  },
  dateBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: C.card,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: C.border,
  },
  dateText: {
    ...Theme.typography.caption,
    color: C.text,
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    backgroundColor: C.errorSoft,
    marginBottom: Theme.spacing.md,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: C.errorSoft,
  },
  errorText: {
    flex: 1,
    ...Theme.typography.body,
    color: C.error,
  },
  grid4: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Theme.spacing.sm,
    marginTop: Theme.spacing.md,
  },
  statCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: C.bg,
    borderRadius: Theme.radius.md,
    padding: 10,
    width: '48.5%',
  },
  statCopy: {
    flex: 1,
    minWidth: 0,
  },
  iconBox: {
    width: 36,
    height: 36,
    borderRadius: Theme.radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: C.muted,
  },
  cardValue: {
    fontSize: Theme.typography.h3.fontSize,
    color: C.text,
    letterSpacing: -0.4,
    lineHeight: 24,
  },
  cardSub: {
    fontSize: Theme.typography.label.fontSize,
    color: C.textSec,
    marginTop: 1,
  },
  skeletonText: {
    height: 16,
    backgroundColor: C.border,
    borderRadius: Theme.radius.sm,
    marginTop: Theme.spacing.xs,
  },
  summaryStrip: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 14,
    marginTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: C.border,
  },
  barBody: {
    padding: Theme.spacing.md,
    gap: Theme.spacing.md,
  },
  barRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
  },
  barLabel: {
    ...Theme.typography.caption,
    color: C.text,
    width: 52,
  },
  barTrack: {
    flex: 1,
    height: 12,
    backgroundColor: C.bg,
    borderRadius: 4,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: C.border,
  },
  barFill: {
    height: '100%',
    borderRadius: 4,
  },
  barPct: {
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '700',
    width: 36,
    textAlign: 'right',
  },
  barCount: {
    fontSize: Theme.typography.label.fontSize,
    color: C.muted,
    width: 52,
    textAlign: 'right',
  },
  sumDivider: {
    width: StyleSheet.hairlineWidth,
    height: 28,
    backgroundColor: 'rgba(148, 163, 184, 0.25)',
    alignSelf: 'center',
  },
  sumItem: {
    alignItems: 'center',
    minWidth: 72,
  },
  sumVal: {
    fontSize: Theme.typography.h4.fontSize,
    letterSpacing: -0.3,
  },
  sumLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: C.muted,
    marginTop: 3,
    fontWeight: '500',
  },
  classGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  classChip: {
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    flexBasis: '47%',
    flexGrow: 1,
    backgroundColor: C.bg,
  },
  chipLabel: {
    fontSize: Theme.typography.body.fontSize,
    color: C.text,
    fontWeight: '600',
  },
  chipPct: {
    fontSize: Theme.typography.body.fontSize,
    fontWeight: '700',
  },
  chipSub: {
    fontSize: Theme.typography.label.fontSize,
    color: C.muted,
    marginTop: 2,
  },
  classChipHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.sm,
  },
  progressTrackCompact: {
    width: '100%',
    height: 4,
    backgroundColor: C.border,
    borderRadius: 2,
    overflow: 'hidden',
    marginBottom: 6,
  },
  progressFillCompact: {
    height: '100%',
    borderRadius: 3,
  },
  progressTrack: {
    width: 72,
    height: 8,
    backgroundColor: C.bg,
    borderRadius: Theme.radius.sm,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: C.border,
    marginBottom: 6,
  },
  progressFill: {
    height: '100%',
    borderRadius: Theme.radius.sm,
  },
  bottomBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    flexWrap: 'wrap',
    backgroundColor: C.card,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    marginHorizontal: Theme.spacing.md,
    marginBottom: Theme.spacing.lg,
    borderWidth: 1,
    borderColor: C.border,
  },
  bottomItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  bottomText: {
    ...Theme.typography.label,
    color: C.muted,
  },
  bottomStrong: {
    color: C.text,
  },
  liveIndicator: {
    marginLeft: 'auto',
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: C.success,
  },
  emptyState: {
    padding: Theme.spacing.lg,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.muted,
  },
  skeletonBarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
  },
  skeletonBox: {
    backgroundColor: C.border,
    borderRadius: Theme.radius.sm,
  },
  skeletonRingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    padding: Theme.spacing.md,
  },
  skeletonClassChip: {
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: C.border,
    padding: Theme.spacing.md,
    width: SCREEN_WIDTH > 400 ? '47%' : '100%',
  },
  decCircle1: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(255,255,255,0.06)',
    top: -50,
    right: -40,
  },
  decCircle2: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255,255,255,0.05)',
    bottom: -20,
    left: 60,
  },
});
