import { StyleSheet } from 'react-native';
import {Theme, colors} from '../../../theme/tokens';

export const principalFaceReviewStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Theme.colors.background },

  statsScroll: { marginBottom: Theme.spacing.md, marginHorizontal: Theme.spacing.md },
  statCard: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    marginRight: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Theme.colors.border,
    minWidth: 130,
  },
  statVal: { fontSize: Theme.typography.h2.fontSize, fontWeight: '800' },
  statLabel: { ...Theme.typography.label, color: Theme.colors.textMuted, marginTop: 3, fontWeight: '500' },

  tabs: {
    marginHorizontal: Theme.spacing.md,
    marginBottom: 14,
  },
  tabCount: { ...Theme.typography.caption, fontWeight: '400' },

  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    paddingHorizontal: Theme.spacing.md,
    height: 42,
    marginBottom: 10,
  },
  searchInput: { flex: 1, ...Theme.typography.body, color: Theme.colors.text },

  chip: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: Theme.radius.xl,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    backgroundColor: Theme.colors.card,
    marginRight: Theme.spacing.sm,
  },
  chipActive: { backgroundColor: Theme.colors.primary, borderColor: Theme.colors.primary },
  chipText: { ...Theme.typography.caption, color: Theme.colors.textMuted, fontWeight: '600' },
  chipTextActive: { color: Theme.colors.card },

  resultInfo: { ...Theme.typography.caption, color: Theme.colors.textMuted, marginBottom: 10 },

  errorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    backgroundColor: Theme.colors.errorBg,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
  },
  errorBoxText: { flex: 1, color: Theme.colors.error, fontSize: Theme.typography.caption.fontSize },

  centered: { alignItems: 'center', paddingVertical: Theme.spacing.xxl, gap: Theme.spacing.md },
  loadingText: { color: Theme.colors.textMuted, ...Theme.typography.body, marginTop: Theme.spacing.sm },
  emptyTitle: { ...Theme.typography.bodyMd, fontWeight: '700', color: Theme.colors.text, textAlign: 'center' },
  emptyText: { fontSize: Theme.typography.caption.fontSize, color: Theme.colors.textMuted, textAlign: 'center' },

  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: Theme.spacing.md },

  card: {
    width: '47%',
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.md,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Theme.colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  photoArea: {
    height: 130,
    backgroundColor: Theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  photo: { width: '100%', height: '100%', resizeMode: 'cover' },
  noPhotoWrap: { alignItems: 'center', gap: Theme.spacing.xs },
  noPhotoText: { ...Theme.typography.label, color: Theme.colors.textMuted },
  badge: {
    position: 'absolute',
    top: 6,
    right: 6,
    borderRadius: Theme.radius.xl,
    paddingVertical: 3,
    paddingHorizontal: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  badgeText: { fontSize: Theme.typography.label.fontSize, fontWeight: '700' },
  cardBody: { padding: 10 },
  cardName: { fontSize: Theme.typography.caption.fontSize, fontWeight: '700', color: Theme.colors.text },
  cardSub: { ...Theme.typography.label, color: Theme.colors.textMuted, marginBottom: Theme.spacing.sm },
  resolvedRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Theme.spacing.xs },
  resolvedText: { ...Theme.typography.caption, fontWeight: '700' },
  btnCol: { gap: 5 },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingVertical: 6,
    borderRadius: 7,
  },
  actionBtnText: { color: Theme.colors.card, ...Theme.typography.label, fontWeight: '700' },

  pagination: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Theme.spacing.md, marginTop: Theme.spacing.xl },
  pageBtn: {
    width: 36,
    height: 36,
    borderRadius: Theme.radius.sm,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    backgroundColor: Theme.colors.card,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageBtnDisabled: { opacity: 0.4 },
  pageInfo: { fontSize: Theme.typography.caption.fontSize, fontWeight: '600', color: Theme.colors.text },

  // Modal
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.55)', alignItems: 'center', justifyContent: 'center', padding: Theme.spacing.md },
  modalBox: {
    backgroundColor: Theme.colors.background, borderRadius: Theme.radius.lg, width: '100%', maxWidth: 440,
    overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 20 }, shadowOpacity: 0.25, shadowRadius: 30, elevation: 20,
  },
  modalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: Theme.spacing.md, borderBottomWidth: 1, borderBottomColor: Theme.colors.border },
  modalTitle: { ...Theme.typography.body, fontWeight: '700', color: Theme.colors.text },
  modalSubtitle: { ...Theme.typography.caption, color: Theme.colors.textMuted, marginTop: 2 },
  closeX: { fontSize: Theme.typography.h3.fontSize, color: Theme.colors.textMuted, paddingHorizontal: Theme.spacing.xs },
  modalBody: { padding: Theme.spacing.md },
  errorRow: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: Theme.colors.errorBg, borderRadius: Theme.radius.sm, padding: 10, marginBottom: Theme.spacing.md },
  errorText: { flex: 1, color: Theme.colors.error, fontSize: Theme.typography.caption.fontSize },
  previewWrap: { alignItems: 'center', gap: 6, marginBottom: 14 },
  previewImg: { width: 110, height: 110, borderRadius: 55, borderWidth: 3, borderColor: Theme.colors.success },
  previewName: { fontSize: Theme.typography.caption.fontSize, fontWeight: '600', color: Theme.colors.text, maxWidth: 220 },
  previewHint: { ...Theme.typography.label, color: Theme.colors.textMuted },
  emptyPreview: { height: 130, backgroundColor: Theme.colors.background, borderRadius: Theme.radius.md, borderWidth: 2, borderColor: Theme.colors.border, borderStyle: 'dashed', alignItems: 'center', justifyContent: 'center', gap: 6, marginBottom: 14 },
  emptyPreviewText: { ...Theme.typography.body, color: Theme.colors.textMuted },
  emptyPreviewHint: { ...Theme.typography.label, color: Theme.colors.textMuted },
  pickRow: { flexDirection: 'row', gap: 10 },
  pickBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, backgroundColor: Theme.colors.primary, borderRadius: Theme.radius.sm, paddingVertical: 10 },
  pickBtnText: { color: Theme.colors.card, fontSize: Theme.typography.caption.fontSize, fontWeight: '700' },
  modalFooter: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10, padding: 14, borderTopWidth: 1, borderTopColor: Theme.colors.border },
  outlineBtn: { paddingVertical: Theme.spacing.sm, paddingHorizontal: Theme.spacing.md, borderRadius: Theme.radius.sm, borderWidth: 1, borderColor: Theme.colors.border },
  outlineBtnText: { fontSize: Theme.typography.caption.fontSize, fontWeight: '600', color: Theme.colors.text },
  primaryBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: Theme.colors.primary, borderRadius: Theme.radius.sm, paddingVertical: Theme.spacing.sm, paddingHorizontal: Theme.spacing.md },
  primaryBtnText: { color: Theme.colors.card, fontSize: Theme.typography.caption.fontSize, fontWeight: '700' },
});
