import { StyleSheet, Platform } from 'react-native';
import {Theme, C, colors} from '../../../theme/tokens';
import { CALENDAR_COLORS } from './helpers';

export const calendarStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: CALENDAR_COLORS.bg,
  },
  scrollViewContainer: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  loadingText: {
    marginTop: Theme.spacing.md,
    color: CALENDAR_COLORS.textSecondary,
  },
  errorContainer: {
    backgroundColor: Theme.colors.redLight,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    marginHorizontal: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: CALENDAR_COLORS.danger + '40',
  },
  errorText: {
    color: CALENDAR_COLORS.danger,
    marginBottom: Theme.spacing.sm,
    textAlign: 'center',
  },
  retryButton: {
    backgroundColor: CALENDAR_COLORS.danger,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.radius.sm,
  },
  retryButtonText: {
    color: Theme.colors.card,
    fontSize: Theme.typography.caption.fontSize,
  },
  actionRowContainer: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    marginHorizontal: Theme.spacing.md,
    marginTop: 14,
    marginBottom: Theme.spacing.sm,
  },
  actionRowContainerStacked: {
    flexDirection: 'column',
  },
  actionRowButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.card,
    borderWidth: 1.5,
    borderColor: C.border,
    borderRadius: Theme.radius.md,
    paddingVertical: Theme.spacing.md,
    gap: Theme.spacing.sm,
    ...Platform.select({
      android: { elevation: 2 },
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.04,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },
      },
    }),
  },
  actionRowButtonPrimary: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  actionRowButtonText: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.text,
  },
  actionRowButtonTextPrimary: {
    color: C.white,
  },
  calendarContainer: {
    backgroundColor: C.card,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.md,
    marginHorizontal: Theme.spacing.md,
    marginTop: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
    borderWidth: 1.5,
    borderColor: C.border,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
  },
  navButton: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.md,
    backgroundColor: '#eff6ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  monthYear: {
    fontSize: Theme.typography.h3.fontSize,
    color: CALENDAR_COLORS.text,
  },
  weekdaysRow: {
    flexDirection: 'row',
    marginBottom: 10,
    paddingBottom: Theme.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.background,
  },
  weekday: {
    flex: 1,
    textAlign: 'center',
    ...Theme.typography.caption,
    color: CALENDAR_COLORS.textMuted,
  },
  daysGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
  },
  dayCell: {
    width: '14.28%',
    aspectRatio: 1,
    borderWidth: 1,
    borderColor: Theme.colors.background,
    padding: 6,
    backgroundColor: Theme.colors.background,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  otherMonthCell: {
    backgroundColor: Theme.colors.background,
    opacity: 0.35,
  },
  dayNumber: {
    fontSize: Theme.typography.caption.fontSize,
    color: CALENDAR_COLORS.textSecondary,
  },
  dayCellToday: {
    backgroundColor: C.primarySoft,
    borderColor: C.primary + '30',
  },
  dayNumberToday: {
    color: C.primary,
  },
  dotsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 3,
    width: '100%',
    height: 8,
  },
  eventDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
  },
  holidaysListBtn: {
    backgroundColor: '#047857',
    paddingVertical: 14,
    marginHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
    shadowColor: '#064e3b',
    shadowOpacity: 0.15,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  holidaysListBtnText: {
    color: Theme.colors.card,
    ...Theme.typography.bodyMd,
  },
  holidaysSidebar: {
    backgroundColor: C.card,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.md,
    marginHorizontal: Theme.spacing.md,
    marginBottom: Theme.spacing.lg,
    borderWidth: 1.5,
    borderColor: C.border,
  },
  sidebarTitle: {
    fontSize: Theme.typography.h4.fontSize,
    color: CALENDAR_COLORS.text,
    marginBottom: Theme.spacing.md,
  },
  holidayItemCard: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.md,
    padding: 14,
    marginBottom: 10,
    borderLeftWidth: 4,
    borderWidth: 1,
    borderColor: Theme.colors.background,
  },
  holidayItemContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  holidayName: {
    ...Theme.typography.body,
    color: CALENDAR_COLORS.text,
    marginBottom: Theme.spacing.xs,
  },
  holidayDate: {
    ...Theme.typography.caption,
    color: CALENDAR_COLORS.textMuted,
  },
  eventTypeBadge: {
    fontSize: Theme.typography.label.fontSize,
    marginTop: Theme.spacing.xs,
    textTransform: 'capitalize',
  },
  holidayItemActions: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
  },
  readOnlyNotice: {
    backgroundColor: '#f8fbff',
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.lg,
    borderWidth: 1.5,
    borderColor: '#bfdbfe',
    marginHorizontal: Theme.spacing.md,
    marginTop: Theme.spacing.md,
    marginBottom: Theme.spacing.sm,
  },
  readOnlyNoticeTitle: {
    ...Theme.typography.body,
    color: CALENDAR_COLORS.text,
    marginBottom: Theme.spacing.xs,
  },
  readOnlyNoticeText: {
    color: CALENDAR_COLORS.textSecondary,
    fontSize: Theme.typography.caption.fontSize,
    lineHeight: 18,
  },
  dayCellReadOnly: {
    backgroundColor: '#fafafa',
  },
  actionButton: {
    padding: Theme.spacing.xs,
  },
  emptyText: {
    textAlign: 'center',
    color: CALENDAR_COLORS.textMuted,
    padding: Theme.spacing.xl,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    padding: Theme.spacing.xl,
  },
  modalKeyboard: {
    flex: 1,
  },
  modalScroll: {
    flexGrow: 0,
  },
  modalScrollContent: {
    paddingBottom: Theme.spacing.sm,
  },
  modalContent: {
    backgroundColor: C.card,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.xl,
    maxHeight: '88%',
    width: '100%',
    borderWidth: 1.5,
    borderColor: C.border,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.xl,
    paddingBottom: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.background,
  },
  modalTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: CALENDAR_COLORS.text,
  },
  formGroup: {
    marginBottom: Theme.spacing.md,
  },
  label: {
    marginBottom: Theme.spacing.sm,
    color: CALENDAR_COLORS.text,
    ...Theme.typography.body,
  },
  input: {
    borderWidth: 1.5,
    borderColor: C.border,
    borderRadius: Theme.radius.sm,
    padding: Theme.spacing.md,
    ...Theme.typography.body,
    backgroundColor: CALENDAR_COLORS.bg,
    color: CALENDAR_COLORS.text,
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  pickerContainer: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
  },
  typeOption: {
    flex: 1,
    padding: 10,
    borderRadius: Theme.radius.sm,
    backgroundColor: '#eff6ff',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Theme.colors.blueLight,
  },
  typeOptionActive: {
    backgroundColor: CALENDAR_COLORS.primary,
    borderColor: CALENDAR_COLORS.primary,
  },
  typeOptionText: {
    color: CALENDAR_COLORS.textSecondary,
    ...Theme.typography.caption,
  },
  typeOptionTextActive: {
    color: Theme.colors.card,
  },
  buttonGroup: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    marginTop: Theme.spacing.xl,
  },
  cancelButton: {
    flex: 1,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.sm,
    backgroundColor: '#eff6ff',
    alignItems: 'center',
  },
  cancelButtonText: {
    color: CALENDAR_COLORS.primary,
  },
  submitButton: {
    flex: 1,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.sm,
    backgroundColor: CALENDAR_COLORS.primary,
    alignItems: 'center',
  },
  submitButtonText: {
    color: Theme.colors.card,
  },
  previewField: {
    marginBottom: Theme.spacing.md,
  },
  previewLabel: {
    ...Theme.typography.caption,
    color: CALENDAR_COLORS.textMuted,
    marginBottom: Theme.spacing.xs,
    textTransform: 'uppercase',
  },
  previewValue: {
    ...Theme.typography.body,
    padding: Theme.spacing.md,
    backgroundColor: '#eff6ff',
    borderRadius: Theme.radius.sm,
    color: CALENDAR_COLORS.text,
  },
  previewDescription: {
    ...Theme.typography.body,
    padding: Theme.spacing.md,
    backgroundColor: CALENDAR_COLORS.bg,
    borderRadius: Theme.radius.sm,
    color: CALENDAR_COLORS.textSecondary,
    lineHeight: 20,
  },
  previewButtonGroup: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    marginTop: Theme.spacing.xl,
  },
  previewEditBtn: {
    flex: 1,
    flexDirection: 'row',
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    backgroundColor: CALENDAR_COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    gap: Theme.spacing.sm,
  },
  previewEditBtnText: {
    color: Theme.colors.card,
  },
  previewDeleteBtn: {
    flex: 1,
    flexDirection: 'row',
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.redLight,
    alignItems: 'center',
    justifyContent: 'center',
    gap: Theme.spacing.sm,
  },
  previewDeleteBtnText: {
    color: CALENDAR_COLORS.danger,
  },
  googleApiSection: {
    backgroundColor: '#f0fdf4',
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
    borderWidth: 1,
    borderColor: '#bbf7d0',
  },
  googleApiTitle: {
    ...Theme.typography.bodyMd,
    color: '#166534',
    marginBottom: Theme.spacing.md,
  },
  countrySelector: {
    marginBottom: Theme.spacing.md,
  },
  countryButtons: {
    flexDirection: 'row',
    gap: 6,
    marginTop: Theme.spacing.sm,
    flexWrap: 'wrap',
  },
  countryButton: {
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 6,
    borderRadius: Theme.radius.sm,
    backgroundColor: Theme.colors.background,
    borderWidth: 1,
    borderColor: C.border,
  },
  countryButtonActive: {
    backgroundColor: Theme.colors.success,
    borderColor: Theme.colors.success,
  },
  countryButtonText: {
    color: CALENDAR_COLORS.textSecondary,
    ...Theme.typography.caption,
  },
  countryButtonTextActive: {
    color: Theme.colors.card,
  },
  fetchButton: {
    backgroundColor: Theme.colors.success,
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.sm,
    alignItems: 'center',
  },
  fetchButtonText: {
    color: Theme.colors.card,
  },
  holidaysList: {
    maxHeight: 250,
    marginBottom: Theme.spacing.md,
  },
  holidaysListTitle: {
    fontSize: Theme.typography.caption.fontSize,
    color: CALENDAR_COLORS.textSecondary,
    marginBottom: Theme.spacing.sm,
  },
  holidayItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Theme.spacing.md,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: Theme.radius.sm,
    marginBottom: Theme.spacing.sm,
    backgroundColor: Theme.colors.background,
  },
  holidayItemSelected: {
    backgroundColor: '#e8f5e9',
    borderColor: Theme.colors.success,
  },
  holidayItemText: {
    flex: 1,
    color: CALENDAR_COLORS.text,
    fontSize: Theme.typography.caption.fontSize,
  },
  holidayItemDate: {
    ...Theme.typography.label,
    color: CALENDAR_COLORS.textMuted,
    backgroundColor: Theme.colors.background,
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: Theme.spacing.xs,
    borderRadius: 4,
  },
  dayEventCard: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.md,
    padding: 14,
    borderLeftWidth: 4,
    borderWidth: 1,
    borderColor: Theme.colors.background,
  },
  dayEventCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  dayEventTitle: {
    ...Theme.typography.body,
    color: CALENDAR_COLORS.text,
    flex: 1,
  },
  dayEventTypeBadge: {
    fontSize: Theme.typography.label.fontSize,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: Theme.radius.sm,
    textTransform: 'capitalize',
    overflow: 'hidden',
  },
  dayEventDesc: {
    ...Theme.typography.caption,
    color: CALENDAR_COLORS.textSecondary,
    lineHeight: 18,
    marginBottom: Theme.spacing.sm,
  },
  dayEventCardActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: Theme.spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.background,
    paddingTop: 10,
    marginTop: Theme.spacing.xs,
  },
  dayEventActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.xs,
    paddingVertical: Theme.spacing.xs,
    paddingHorizontal: 10,
    borderRadius: Theme.radius.sm,
    backgroundColor: '#eff6ff',
  },
  dayEventActionBtnDelete: {
    backgroundColor: Theme.colors.redLight,
  },
  dayEventActionText: {
    ...Theme.typography.label,
    color: CALENDAR_COLORS.primary,
  },
  dayEventActionTextDelete: {
    color: CALENDAR_COLORS.danger,
  },
});
