import { StyleSheet } from 'react-native';
import {Theme, colors} from '../../../theme/tokens';

export const payrollStyles = StyleSheet.create({
  mainContainer: { flex: 1, backgroundColor: Theme.colors.background },
  tabsScroll: {
    flexGrow: 0,
    marginBottom: Theme.spacing.md,
  },
  tabsContainer: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
  },
  tab: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: Theme.radius.md,
    gap: 6,
    backgroundColor: Theme.colors.backgroundAlt,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    minWidth: 108,
  },
  tabActive: {
    backgroundColor: Theme.colors.card,
    borderColor: Theme.colors.primary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  tabLabel: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '600',
    color: Theme.colors.textSec,
  },
  tabLabelActive: {
    color: Theme.colors.primary,
    fontWeight: '700',
  },
  tabDesc: { display: 'none' },
  tabDescActive: { display: 'none' },
  tabContentArea: {
    flex: 1,
    minHeight: 0,
  },
  awaitingCard: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
    marginTop: Theme.spacing.sm,
    marginBottom: Theme.spacing.md,
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    gap: 10,
  },
  awaitingTitle: {
    ...Theme.typography.body,
    fontWeight: '700',
    color: Theme.colors.text,
    textAlign: 'center',
  },
  awaitingDesc: {
    ...Theme.typography.caption,
    color: Theme.colors.textSec,
    textAlign: 'center',
    lineHeight: 18,
  },
  tabContainer: { flex: 1, backgroundColor: Theme.colors.background },
  card: { backgroundColor: Theme.colors.card, borderRadius: Theme.radius.xl, borderWidth: 1, borderColor: Theme.colors.border, marginBottom: Theme.spacing.md, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.04, shadowRadius: 8, elevation: 2 },
  cardSection: { padding: Theme.spacing.md, borderBottomWidth: 1, borderBottomColor: Theme.colors.borderLight },
  sectionHeaderText: { ...Theme.typography.label, fontWeight: 'bold', color: Theme.colors.textSec, textTransform: 'uppercase', letterSpacing: 1, marginBottom: Theme.spacing.md },
  configGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 16, marginBottom: Theme.spacing.md },
  fieldContainer: { minWidth: 100 },
  fieldLabel: { fontSize: Theme.typography.label.fontSize, fontWeight: '700', color: Theme.colors.textSec, marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 },
  fieldHint: { fontSize: Theme.typography.label.fontSize, color: Theme.colors.textMuted, marginTop: Theme.spacing.xs },
  pickerContainer: { borderWidth: 1, borderColor: Theme.colors.border, borderRadius: Theme.radius.md, backgroundColor: Theme.colors.background },
  pickerContainerSmall: { borderWidth: 1, borderColor: Theme.colors.border, borderRadius: Theme.radius.md, backgroundColor: Theme.colors.background, minWidth: 120 },
  picker: { height: 48 },
  input: { borderWidth: 1, borderColor: Theme.colors.border, borderRadius: Theme.radius.md, paddingHorizontal: Theme.spacing.md, height: 44, color: Theme.colors.text, backgroundColor: Theme.colors.background },
  pctInputContainer: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: Theme.colors.border, borderRadius: Theme.radius.md, backgroundColor: Theme.colors.background, paddingHorizontal: 10 },
  pctInput: { flex: 1, height: 44, color: Theme.colors.text },
  pctInputSymbol: { color: Theme.colors.textSec, fontWeight: '700' },
  rupeeInputContainer: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: Theme.colors.border, borderRadius: Theme.radius.md, backgroundColor: Theme.colors.background, paddingHorizontal: 10 },
  rupeeInputSymbol: { color: Theme.colors.textSec, marginRight: Theme.spacing.xs, fontWeight: '700' },
  rupeeInput: { flex: 1, height: 44, color: Theme.colors.text },
  toggleContainer: { flexDirection: 'column', gap: Theme.spacing.md, marginTop: Theme.spacing.sm },
  toggleOption: { flexDirection: 'row', alignItems: 'center', borderWidth: 1.5, borderColor: Theme.colors.border, borderRadius: Theme.radius.lg, padding: Theme.spacing.md, backgroundColor: Theme.colors.background },
  toggleOptionActive: { borderColor: Theme.colors.primary, backgroundColor: '#f8faff' },
  radioOuter: { width: 20, height: 20, borderRadius: Theme.radius.md, borderWidth: 2, borderColor: Theme.colors.textSec, alignItems: 'center', justifyContent: 'center', marginRight: Theme.spacing.md },
  radioInner: { width: 10, height: 10, borderRadius: 5, backgroundColor: Theme.colors.primary },
  toggleTextContainer: { flex: 1 },
  toggleOptionTitle: { ...Theme.typography.body, fontWeight: '700', color: Theme.colors.cardAlt },
  toggleOptionTitleActive: { color: Theme.colors.primary },
  toggleOptionDesc: { marginTop: 2, color: Theme.colors.textSec, ...Theme.typography.label },
  toggleOptionDescActive: { color: Theme.colors.blue },
  configForm: { gap: Theme.spacing.xs },
  divider: { height: 1, backgroundColor: Theme.colors.background, marginVertical: Theme.spacing.md },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: Theme.spacing.md },
  sectionTitle: { ...Theme.typography.caption, fontWeight: '700', color: Theme.colors.textSec, textTransform: 'uppercase', letterSpacing: 0.5 },
  addButton: { backgroundColor: '#eff6ff', borderColor: '#bfdbfe', borderWidth: 1, borderRadius: Theme.radius.md, paddingHorizontal: Theme.spacing.md, paddingVertical: 6 },
  addButtonRed: { backgroundColor: '#fff5f5', borderColor: '#feb2b2' },
  addButtonTextRed: { color: '#c53030' },
  allowancesGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 12, marginBottom: Theme.spacing.sm },
  deductionsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 12, marginBottom: Theme.spacing.sm },
  extraItemContainer: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: Theme.spacing.sm, backgroundColor: Theme.colors.background, borderRadius: Theme.radius.md, padding: Theme.spacing.sm, borderWidth: 1, borderColor: Theme.colors.border },
  extraItemContainerRed: { backgroundColor: '#fff5f5', borderColor: '#feb2b2' },
  extraItemInput: { flex: 1, borderWidth: 1, borderColor: Theme.colors.border, borderRadius: Theme.radius.md, paddingHorizontal: 10, height: 42, backgroundColor: Theme.colors.background },
  removeButton: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: Theme.colors.redLight },
  removeButtonText: { color: Theme.colors.error, ...Theme.typography.h3, lineHeight: 18 },
  previewContainer: { marginTop: Theme.spacing.xl, borderRadius: Theme.radius.xl, backgroundColor: Theme.colors.background, borderWidth: 1.5, borderColor: Theme.colors.border, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.05, shadowRadius: 10, elevation: 3 },
  previewHeader: { backgroundColor: Theme.colors.primary, paddingVertical: Theme.spacing.md, paddingHorizontal: Theme.spacing.md },
  previewHeaderTitle: { color: Theme.colors.card, ...Theme.typography.caption, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5 },
  previewContent: { padding: Theme.spacing.md },
  previewRow: { flexDirection: 'column', gap: Theme.spacing.md },
  previewColumn: { width: '100%' },
  previewSubtitle: { ...Theme.typography.label, fontWeight: '700', marginBottom: Theme.spacing.sm, color: Theme.colors.textSec, textTransform: 'uppercase', letterSpacing: 0.5 },
  previewLine: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: Theme.spacing.xs },
  previewLabel: { color: Theme.colors.textSec, ...Theme.typography.caption },
  previewValue: { color: Theme.colors.text, ...Theme.typography.caption, fontWeight: '600' },
  previewValueRed: { color: '#b91c1c' },
  previewValueGreen: { color: '#166534' },
  previewColDivider: { height: 1, backgroundColor: Theme.colors.border, marginVertical: Theme.spacing.xs },
  previewTotalLine: { backgroundColor: Theme.colors.background, borderRadius: Theme.radius.sm, padding: Theme.spacing.sm, marginTop: Theme.spacing.sm, borderWidth: 1, borderColor: Theme.colors.border },
  previewTotalLabel: { color: Theme.colors.textSec, fontWeight: '700' },
  previewTotalValue: { color: Theme.colors.text, ...Theme.typography.body, fontWeight: '800', marginTop: 2 },
  previewTotalValueGreen: { color: '#16a34a' },
  modalContainer: { flex: 1, backgroundColor: Theme.colors.background },
  payslipHeader: {
    padding: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    backgroundColor: Theme.colors.card,
  },
  payslipFooter: {
    padding: Theme.spacing.md,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.border,
    backgroundColor: Theme.colors.card,
  },
  payslipDownloadBtn: { width: '100%', height: 48, alignItems: 'center', justifyContent: 'center' },
  modalHeader: { padding: 14, borderBottomWidth: 1, borderBottomColor: Theme.colors.border, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  modalTitle: { fontSize: Theme.typography.h4.fontSize, fontWeight: '700', color: Theme.colors.text },
  modalSubtitle: { ...Theme.typography.caption, color: Theme.colors.textSec, marginTop: 2 },
  modalActions: { flexDirection: 'row', gap: Theme.spacing.sm },
  modalButton: { borderRadius: Theme.radius.md, borderWidth: 1, borderColor: Theme.colors.textSec, paddingHorizontal: Theme.spacing.md, height: 38, justifyContent: 'center', backgroundColor: Theme.colors.background },
  modalButtonPrimary: { backgroundColor: Theme.colors.primary, borderColor: Theme.colors.primary },
  modalButtonText: { color: Theme.colors.card, ...Theme.typography.caption, fontWeight: '700' },
  modalButtonTextClose: { color: Theme.colors.cardAlt, ...Theme.typography.caption, fontWeight: '600' },
  webviewContainer: { flex: 1 },
  webview: { flex: 1 },
  warningBox: { marginTop: 10, backgroundColor: '#fff7ed', borderColor: '#fdba74', borderWidth: 1, borderRadius: Theme.radius.md, padding: 10, flexDirection: 'row', alignItems: 'center', gap: Theme.spacing.sm },
  warningText: { color: '#c2410c', ...Theme.typography.caption },
  loadingRow: { marginTop: 10, flexDirection: 'row', alignItems: 'center', gap: Theme.spacing.sm },
  loadingText: { color: Theme.colors.textSec, ...Theme.typography.caption },
  loadingContainer: { padding: 22, alignItems: 'center', justifyContent: 'center', gap: Theme.spacing.sm },
  staffBadge: { marginTop: 10, alignSelf: 'flex-start', backgroundColor: '#ecfeff', borderColor: '#a5f3fc', borderWidth: 1, borderRadius: Theme.radius.full, paddingHorizontal: Theme.spacing.md, paddingVertical: 6, flexDirection: 'row', alignItems: 'center' },
  staffBadgeText: { color: '#0891b2', ...Theme.typography.caption, fontWeight: '600' },
  modeSection: { marginTop: 10 },
  fixedInfoBox: { backgroundColor: '#eff6ff', borderColor: '#bfdbfe', borderWidth: 1, borderRadius: Theme.radius.md, padding: Theme.spacing.md, flexDirection: 'row', alignItems: 'center', gap: Theme.spacing.sm },
  fixedInfoText: { color: Theme.colors.primary, ...Theme.typography.caption, fontWeight: '600' },
  fixedInfoSubtext: { color: Theme.colors.blue, ...Theme.typography.label, marginTop: Theme.spacing.xs },
  fetchRow: { gap: 10, marginTop: Theme.spacing.md },
  fetchButton: { backgroundColor: Theme.colors.primary, borderRadius: Theme.radius.md, paddingHorizontal: Theme.spacing.md, minHeight: 44, justifyContent: 'center', alignItems: 'center', alignSelf: 'stretch', shadowColor: Theme.colors.primary, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 2 },
  fetchButtonDisabled: { opacity: 0.5 },
  fetchButtonText: { color: Theme.colors.card, fontWeight: '700', fontSize: Theme.typography.caption.fontSize },
  viewAttButton: { backgroundColor: Theme.colors.background, borderWidth: 1, borderColor: Theme.colors.textSec, borderRadius: Theme.radius.md, paddingHorizontal: Theme.spacing.md, minHeight: 44, justifyContent: 'center', alignItems: 'center', alignSelf: 'stretch' },
  viewAttButtonText: { color: Theme.colors.cardAlt, fontWeight: '700', fontSize: Theme.typography.caption.fontSize },
  attLoadedBadge: { backgroundColor: '#ecfdf5', borderColor: '#bbf7d0', borderWidth: 1, borderRadius: Theme.radius.full, paddingHorizontal: Theme.spacing.md, paddingVertical: 6, alignSelf: 'flex-start' },
  attLoadedText: { color: '#166534', ...Theme.typography.label, fontWeight: '600' },
  attSummaryContainer: { marginTop: Theme.spacing.md, borderWidth: 1, borderColor: '#bfdbfe', borderRadius: Theme.radius.md, backgroundColor: '#f8fbff', padding: 10 },
  attSummaryHeaderRow: { flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: Theme.colors.blueLight, paddingBottom: Theme.spacing.sm, marginBottom: Theme.spacing.xs },
  attSummaryRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: Theme.spacing.sm, borderBottomWidth: 1, borderBottomColor: '#eff6ff' },
  attSummaryHeaderCell: { width: 52, textAlign: 'center', fontSize: Theme.typography.label.fontSize, fontWeight: '700', color: Theme.colors.primary, textTransform: 'uppercase' },
  attSummaryCell: { width: 52, textAlign: 'center', fontSize: Theme.typography.caption.fontSize, fontWeight: '600', color: Theme.colors.text },
  attSummaryNameCol: { width: 120, paddingRight: Theme.spacing.sm },
  attSummaryLopCol: { backgroundColor: '#f3e8ff' },
  attSummaryName: { fontSize: Theme.typography.caption.fontSize, fontWeight: '700', color: Theme.colors.text },
  attSummaryId: { fontSize: Theme.typography.label.fontSize, color: Theme.colors.textSec, marginTop: 2 },
  attSummaryPresent: { color: '#166534', fontWeight: '700' },
  attSummaryLop: { color: '#7e22ce', fontWeight: '800' },
  attSummaryPct: { fontWeight: '700', fontSize: Theme.typography.label.fontSize },
  attPctGreen: { color: '#166534' },
  attPctYellow: { color: '#a16207' },
  attPctRed: { color: '#b91c1c' },
  attSummaryFootnote: { marginTop: Theme.spacing.sm, textAlign: 'center', fontSize: Theme.typography.label.fontSize, color: Theme.colors.textSec },
  generatePrompt: {
    marginBottom: Theme.spacing.md,
    backgroundColor: Theme.colors.card,
    borderWidth: 1.5,
    borderColor: Theme.colors.primary,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.md,
    gap: Theme.spacing.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  generatePromptCopy: {
    flex: 1,
  },
  generatePromptTitle: { ...Theme.typography.body, fontWeight: '700', color: Theme.colors.text },
  generatePromptDesc: { color: Theme.colors.textSec, ...Theme.typography.caption, marginTop: 2 },
  generateButton: {
    backgroundColor: '#16a34a',
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.md,
    minHeight: 44,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'stretch',
  },
  generateButtonText: { color: Theme.colors.card, fontWeight: '700', fontSize: Theme.typography.body.fontSize },
  resultsContainer: { backgroundColor: Theme.colors.card, borderRadius: Theme.radius.lg, borderWidth: 1, borderColor: Theme.colors.border, padding: Theme.spacing.md, marginBottom: Theme.spacing.md },
  summaryBar: { flexDirection: 'row', flexWrap: 'wrap', gap: Theme.spacing.sm, marginBottom: Theme.spacing.md },
  summaryBarHours: { flexDirection: 'row', gap: 10, marginBottom: Theme.spacing.md, flexWrap: 'wrap' },
  summaryItem: { backgroundColor: Theme.colors.backgroundAlt, borderRadius: Theme.radius.md, padding: Theme.spacing.md, borderWidth: 1, borderColor: Theme.colors.border, flexBasis: '47%', flexGrow: 1 },
  summaryLabel: { color: Theme.colors.textSec, ...Theme.typography.label, textTransform: 'uppercase', letterSpacing: 0.5 },
  summaryValue: { ...Theme.typography.body, color: Theme.colors.text, fontWeight: '700', marginTop: Theme.spacing.xs },
  summaryValueLarge: { color: Theme.colors.text, fontSize: Theme.typography.h4.fontSize, fontWeight: '800', marginTop: Theme.spacing.xs },
  summaryValueRed: { color: '#b91c1c' },
  summaryValueGreen: { color: '#166534' },
  actionBar: { gap: 10, marginBottom: Theme.spacing.xs },
  searchInput: { width: '100%', borderWidth: 1, borderColor: Theme.colors.border, borderRadius: Theme.radius.md, minHeight: 44, paddingHorizontal: 14, backgroundColor: Theme.colors.background, color: Theme.colors.text },
  actionButtonsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Theme.spacing.sm },
  generateAllButton: { flexGrow: 1, flexBasis: '47%', backgroundColor: '#eff6ff', borderRadius: Theme.radius.md, paddingHorizontal: Theme.spacing.md, minHeight: 44, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#bfdbfe' },
  generateAllButtonText: { ...Theme.typography.caption, color: Theme.colors.primary, fontWeight: '700', textAlign: 'center' },
  saveAllButton: { flexGrow: 1, flexBasis: '47%', backgroundColor: '#16a34a', borderRadius: Theme.radius.md, paddingHorizontal: Theme.spacing.md, minHeight: 44, justifyContent: 'center', alignItems: 'center' },
  saveAllButtonText: { ...Theme.typography.caption, color: Theme.colors.card, fontWeight: '700', textAlign: 'center' },
  emailAllButton: { flexGrow: 1, flexBasis: '47%', backgroundColor: '#0284c7', borderRadius: Theme.radius.md, paddingHorizontal: Theme.spacing.md, minHeight: 44, justifyContent: 'center', alignItems: 'center' },
  emailAllButtonText: { ...Theme.typography.caption, color: Theme.colors.card, fontWeight: '700', textAlign: 'center' },
  employeeCard: { borderWidth: 1, borderColor: Theme.colors.border, borderRadius: Theme.radius.lg, backgroundColor: Theme.colors.card, padding: Theme.spacing.md, marginBottom: Theme.spacing.sm, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.03, shadowRadius: 6, elevation: 1 },
  employeeCardGenerated: { borderColor: Theme.colors.primary, backgroundColor: '#f8faff', borderWidth: 1.5 },
  employeeInfo: { flexDirection: 'row', alignItems: 'center', gap: Theme.spacing.md },
  employeeTextBlock: { flex: 1, minWidth: 0 },
  avatar: { width: 40, height: 40, borderRadius: Theme.radius.xl, backgroundColor: Theme.colors.primary, alignItems: 'center', justifyContent: 'center' },
  avatarText: { ...Theme.typography.body, color: Theme.colors.card, fontWeight: '700' },
  employeeNameText: { ...Theme.typography.body, fontWeight: '700', color: Theme.colors.text, flexShrink: 1 },
  employeeIdText: { color: Theme.colors.textSec, ...Theme.typography.label, marginTop: 2, flexShrink: 1 },
  employeeStatsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Theme.spacing.sm, marginTop: Theme.spacing.md },
  statItem: { backgroundColor: Theme.colors.backgroundAlt, borderWidth: 1, borderColor: Theme.colors.border, borderRadius: Theme.radius.md, paddingHorizontal: 10, paddingVertical: Theme.spacing.sm, flexBasis: '47%', flexGrow: 1 },
  statLabel: { color: Theme.colors.textSec, fontSize: Theme.typography.label.fontSize, textTransform: 'uppercase', letterSpacing: 0.5 },
  statValue: { ...Theme.typography.caption, color: Theme.colors.text, fontWeight: '700', marginTop: 2 },
  statValueBold: { fontWeight: '800' },
  statValueRed: { color: '#b91c1c' },
  statValueGreen: { color: '#166534' },
  employeeActionsRow: { marginTop: Theme.spacing.md, flexDirection: 'row', justifyContent: 'flex-end' },
  generateEmpButton: { backgroundColor: Theme.colors.primary, borderRadius: Theme.radius.md, paddingHorizontal: Theme.spacing.lg, minHeight: 40, justifyContent: 'center', alignItems: 'center' },
  generateEmpButtonText: { ...Theme.typography.caption, color: Theme.colors.card, fontWeight: '700' },
  actionButtonsGroup: { flexDirection: 'row', gap: Theme.spacing.sm, flexWrap: 'wrap', justifyContent: 'flex-end' },
  actionBtn: { borderRadius: Theme.radius.md, paddingHorizontal: 14, minHeight: 40, justifyContent: 'center', alignItems: 'center', minWidth: 64 },
  actionBtnText: { ...Theme.typography.caption, color: Theme.colors.primary, fontWeight: '700' },
  actionBtnTextLight: { color: Theme.colors.card },
  viewBtn: { backgroundColor: '#eff6ff', borderWidth: 1, borderColor: '#bfdbfe' },
  pdfBtn: { backgroundColor: Theme.colors.primary },
  recalcBtn: { backgroundColor: Theme.colors.background, borderWidth: 1, borderColor: Theme.colors.textSec },
  emailBtn: { backgroundColor: '#0284c7' },
  recalcBtnText: { ...Theme.typography.body, color: Theme.colors.cardAlt, fontWeight: '700' },
  emptyState: { alignItems: 'center', justifyContent: 'center', padding: 28 },
  emptyStateText: { color: Theme.colors.textSec },
  emptyStateLarge: { alignItems: 'center', justifyContent: 'center', padding: 30, backgroundColor: Theme.colors.background, borderWidth: 1, borderColor: Theme.colors.border, borderRadius: Theme.radius.lg },
  emptyStateLargeText: { color: Theme.colors.text, fontWeight: '600' },
  emptyStateSubtext: { color: Theme.colors.textSec, marginTop: Theme.spacing.xs, ...Theme.typography.caption },
  employeeHeader: { flexDirection: 'row', alignItems: 'center', gap: Theme.spacing.md, marginBottom: Theme.spacing.md },
  avatarLarge: { width: 48, height: 48, borderRadius: Theme.radius.xxl, backgroundColor: Theme.colors.primary, alignItems: 'center', justifyContent: 'center' },
  avatarLargeText: { color: Theme.colors.card, ...Theme.typography.h3 },
  employeeNameLarge: { fontWeight: '700', color: Theme.colors.text, fontSize: Theme.typography.h4.fontSize },
  employeeDetailsText: { color: Theme.colors.textSec, marginTop: 2, ...Theme.typography.caption },
  resultSummary: { flexDirection: 'row', gap: Theme.spacing.sm, marginTop: Theme.spacing.md, flexWrap: 'wrap' },
  resultItem: { flex: 1, borderWidth: 1, borderColor: Theme.colors.border, borderRadius: Theme.radius.md, padding: Theme.spacing.md, backgroundColor: Theme.colors.background, minWidth: 90 },
  resultLabel: { color: Theme.colors.textSec, fontSize: Theme.typography.label.fontSize, textTransform: 'uppercase', letterSpacing: 0.5 },
  resultValue: { color: Theme.colors.text, fontWeight: '700', marginTop: Theme.spacing.xs },
  resultValueRed: { color: '#b91c1c' },
  resultValueGreen: { color: '#166534' },
  infoBanner: { backgroundColor: '#eff6ff', borderWidth: 1, borderColor: '#bfdbfe', borderRadius: Theme.radius.md, padding: Theme.spacing.md, marginBottom: Theme.spacing.md },
  infoBannerText: { color: Theme.colors.primary, ...Theme.typography.caption, lineHeight: 16 },
  hoursConfigRow: { display: 'none' },
  applyRateRow: { flexDirection: 'row', alignItems: 'center', gap: Theme.spacing.sm },
  applyButton: { backgroundColor: Theme.colors.primary, borderRadius: Theme.radius.md, paddingHorizontal: Theme.spacing.md, height: 44, justifyContent: 'center' },
  applyButtonDisabled: { opacity: 0.5 },
  applyButtonText: { ...Theme.typography.caption, color: Theme.colors.card, fontWeight: '700' },
  hoursListContainer: { gap: Theme.spacing.md, marginBottom: Theme.spacing.xl },
  hoursHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: Theme.spacing.sm, paddingHorizontal: Theme.spacing.xs },
  hoursHeaderTitle: { ...Theme.typography.body, fontWeight: '700', color: Theme.colors.text },
  hoursHeaderCount: { color: Theme.colors.textSec, ...Theme.typography.caption },
  hoursRow: {
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.02,
    shadowRadius: 6,
    elevation: 1,
  },
  hoursRowGenerated: { backgroundColor: '#f8faff', borderColor: '#bfdbfe' },
  hoursAvatar: { width: 36, height: 36, borderRadius: Theme.radius.lg, backgroundColor: '#0284c7', alignItems: 'center', justifyContent: 'center' },
  hoursAvatarText: { ...Theme.typography.body, color: Theme.colors.card, fontWeight: '700' },
  hoursInfo: { flex: 1, marginLeft: Theme.spacing.sm },
  hoursName: { ...Theme.typography.body, color: Theme.colors.text, fontWeight: '600' },
  hoursId: { color: Theme.colors.textSec, ...Theme.typography.label, marginTop: 2 },
  hoursRateContainer: { display: 'none' },
  hoursTotal: { display: 'none' },
  fetchHoursButton: { backgroundColor: '#eff6ff', borderRadius: Theme.radius.md, paddingHorizontal: Theme.spacing.md, height: 36, justifyContent: 'center', borderWidth: 1, borderColor: '#bfdbfe' },
  hoursGross: { alignItems: 'flex-end' },
  hoursGrossDetail: { color: Theme.colors.textSec, fontSize: Theme.typography.label.fontSize, marginTop: 2 },
  pickerTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.md,
    height: 44,
    backgroundColor: Theme.colors.background,
  },
  pickerTriggerText: {
    ...Theme.typography.body,
    color: Theme.colors.text,
  },
  hoursHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.background,
    paddingBottom: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
  },
  hoursBodyRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: Theme.spacing.md,
  },
  hoursRateCol: {
    flex: 1.2,
  },
  hoursStatusCol: {
    flex: 1,
    alignItems: 'flex-end',
  },
  hoursRateLabel: {
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '700',
    color: Theme.colors.textSec,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  hoursBadge: {
    backgroundColor: '#eff6ff',
    borderRadius: Theme.radius.md,
    paddingHorizontal: 10,
    paddingVertical: Theme.spacing.sm,
    borderWidth: 1,
    borderColor: '#bfdbfe',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 50,
  },
  hoursBadgeText: {
    color: Theme.colors.primary,
    ...Theme.typography.caption,
    fontWeight: '700',
  },
});
