import { StyleSheet, Platform } from 'react-native';
import { Theme, C } from '../../../theme/tokens';

export const PAGE_PAD = 16;

export const teacherManagementStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg },
  scrollView: { flex: 1 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: Theme.spacing.md,
    paddingBottom: Theme.spacing.md,
  },
  headerCopy: { flex: 1, gap: Theme.spacing.xs },
  kicker: {
    ...Theme.typography.label,
    color: C.primary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  title: { fontSize: Theme.typography.h2.fontSize, color: C.text, lineHeight: 28 },
  titleSub: { ...Theme.typography.caption, color: C.muted, lineHeight: 18, maxWidth: 320 },
  headerActions: { flexDirection: 'row', gap: Theme.spacing.sm, flexWrap: 'wrap', justifyContent: 'flex-end' },
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: C.primary,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
  },
  primaryBtnText: { color: Theme.colors.card, fontSize: Theme.typography.caption.fontSize },
  secondaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: C.card,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: C.border,
  },
  secondaryBtnText: { color: C.text, fontSize: Theme.typography.caption.fontSize },
  summaryRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: Theme.spacing.md,
    justifyContent: 'space-between',
  },
  summaryRowStacked: {
    flexDirection: 'column',
  },
  summaryCard: {
    width: '32%',
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: Theme.radius.md,
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: 14,
    ...Platform.select({
      android: { elevation: 1 },
      ios: {
        shadowColor: Theme.colors.text,
        shadowOpacity: 0.05,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
      },
    }),
  },
  summaryValue: { fontSize: Theme.typography.h3.fontSize, color: C.text },
  summaryLabel: { ...Theme.typography.label, color: C.muted, marginTop: 2 },
  tabs: {
    flexDirection: 'row',
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: Theme.radius.lg,
    marginBottom: Theme.spacing.md,
    padding: Theme.spacing.xs,
  },
  tab: { flex: 1, paddingVertical: 11, paddingHorizontal: Theme.spacing.md, alignItems: 'center', justifyContent: 'center', borderRadius: Theme.radius.md },
  activeTab: { backgroundColor: C.primarySoft, borderBottomWidth: 0 },
  tabText: { fontSize: Theme.typography.caption.fontSize, color: C.muted, textAlign: 'center' },
  activeTabText: { color: C.primary },
  errorBox: { marginBottom: Theme.spacing.md, padding: Theme.spacing.md, backgroundColor: C.errorSoft, borderRadius: Theme.radius.sm, borderWidth: 1, borderColor: C.error },
  errorBoxText: { color: C.error, fontSize: Theme.typography.caption.fontSize },
  successBox: { marginBottom: Theme.spacing.md, padding: Theme.spacing.md, backgroundColor: C.successSoft, borderRadius: Theme.radius.sm, borderWidth: 1, borderColor: C.success },
  successBoxText: { color: C.success, fontSize: Theme.typography.caption.fontSize },
  formCard: { backgroundColor: C.card, marginBottom: Theme.spacing.md, borderRadius: Theme.radius.md, borderWidth: 1, borderColor: C.border, overflow: 'hidden' },
  formCardHeader: { padding: Theme.spacing.md, borderBottomWidth: 1, borderBottomColor: C.border, backgroundColor: C.bg },
  stepperWrapper: {
    alignItems: 'center',
  },
  stepperContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  stepItem: {
    alignItems: 'center',
    width: 60,
  },
  stepCircle: {
    width: 28,
    height: 28,
    borderRadius: Theme.radius.md,
    backgroundColor: C.bg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Theme.spacing.xs,
    borderWidth: 1,
    borderColor: C.border,
  },
  stepActive: {
    backgroundColor: Theme.colors.violet,
    borderColor: Theme.colors.violet,
  },
  stepDone: {
    backgroundColor: C.success,
    borderColor: C.success,
  },
  stepNumber: {
    ...Theme.typography.caption,
    color: C.muted,
  },
  stepNumberActive: {
    color: Theme.colors.card,
  },
  stepLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: C.muted,
  },
  stepLabelActive: {
    color: Theme.colors.violet,
  },
  stepConnector: {
    flex: 1,
    height: 2,
    backgroundColor: C.border,
    marginHorizontal: -15,
      },
  stepConnectorDone: {
    backgroundColor: C.success,
  },
  formBody: { padding: Theme.spacing.md },
  sectionTitle: { ...Theme.typography.body, color: C.text, marginBottom: Theme.spacing.md, paddingBottom: Theme.spacing.sm, borderBottomWidth: 1, borderBottomColor: C.border },
  formGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Theme.spacing.md },
  formGroup: { flex: 1, minWidth: '45%' },
  formGroupFull: { width: '100%' },
  label: { ...Theme.typography.caption, color: C.muted, marginBottom: Theme.spacing.xs },
  input: { borderWidth: 1, borderColor: Theme.colors.textSec, borderRadius: Theme.radius.md, padding: Theme.spacing.md, ...Theme.typography.body, backgroundColor: Theme.colors.background, color: C.text },
  inputError: { borderColor: C.error },
  readOnlyInput: { backgroundColor: C.bg, color: C.muted, opacity: 0.7 },
  pickerContainer: { borderWidth: 1, borderColor: Theme.colors.textSec, borderRadius: Theme.radius.md, overflow: 'hidden', backgroundColor: Theme.colors.background },
  picker: { height: 44, color: C.text },
  pickerSmall: { minWidth: 120, borderWidth: 1, borderColor: C.border, borderRadius: Theme.radius.sm, overflow: 'hidden', backgroundColor: C.bg },
  emailRow: { flexDirection: 'row', gap: Theme.spacing.sm, alignItems: 'center' },
  emailInput: { flex: 1 },
  verifyBtn: { paddingHorizontal: Theme.spacing.md, paddingVertical: 10, backgroundColor: C.primary, borderRadius: Theme.radius.sm },
  verifyBtnSuccess: { backgroundColor: C.success },
  verifyBtnText: { color: Theme.colors.card, ...Theme.typography.caption },
  otpRow: { flexDirection: 'row', gap: Theme.spacing.sm, marginTop: Theme.spacing.sm },
  otpInput: { flex: 1 },
  hintText: { ...Theme.typography.label, color: C.muted, marginTop: Theme.spacing.xs },
  formFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: Theme.spacing.md, borderTopWidth: 1, borderTopColor: C.border, backgroundColor: C.bg },
  footerRight: { flexDirection: 'row', alignItems: 'center', gap: Theme.spacing.md },
  stepIndicator: { ...Theme.typography.caption, color: C.muted },
  cancelBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Theme.spacing.xs, paddingHorizontal: Theme.spacing.lg, paddingVertical: Theme.spacing.md, borderRadius: Theme.radius.md, borderWidth: 1, borderColor: Theme.colors.textSec, backgroundColor: Theme.colors.background },
  cancelBtnText: { color: Theme.colors.textSec, ...Theme.typography.body, fontWeight: '600' },
  nextBtn: { flexDirection: 'row', alignItems: 'center', gap: Theme.spacing.xs, backgroundColor: C.primary, paddingHorizontal: Theme.spacing.xl, paddingVertical: 10, borderRadius: Theme.radius.sm },
  nextBtnText: { color: Theme.colors.card, ...Theme.typography.body },
  submitBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: C.success, paddingHorizontal: Theme.spacing.xl, paddingVertical: 10, borderRadius: Theme.radius.sm },
  submitBtnText: { color: Theme.colors.card, ...Theme.typography.body },
  previewHint: { ...Theme.typography.caption, color: C.muted, marginBottom: Theme.spacing.md },
  previewCard: { borderWidth: 1, borderColor: C.border, borderRadius: Theme.radius.md, overflow: 'hidden', backgroundColor: C.card },
  previewHeader: { flexDirection: 'row', gap: Theme.spacing.md, padding: Theme.spacing.md, backgroundColor: C.primary },
  previewPhoto: { width: 64, height: 64, borderRadius: 32, backgroundColor: 'rgba(255,255,255,0.2)', alignItems: 'center', justifyContent: 'center' },
  previewInitial: { fontSize: Theme.typography.h2.fontSize, color: Theme.colors.card },
  previewInfo: { flex: 1 },
  previewName: { fontSize: Theme.typography.h4.fontSize, color: Theme.colors.card },
  previewDesignation: { ...Theme.typography.caption, color: 'rgba(255,255,255,0.8)', marginTop: 2 },
  previewEmail: { ...Theme.typography.caption, color: 'rgba(255,255,255,0.8)', marginTop: 2 },
  previewStatus: { flexDirection: 'row', alignItems: 'center', gap: Theme.spacing.xs, alignSelf: 'flex-start', paddingHorizontal: Theme.spacing.sm, paddingVertical: Theme.spacing.xs, borderRadius: Theme.radius.md, marginTop: 6 },
  previewStatusActive: { backgroundColor: 'rgba(16,185,129,0.3)' },
  previewStatusInactive: { backgroundColor: 'rgba(239,68,68,0.3)' },
  previewStatusText: { color: Theme.colors.card, fontSize: Theme.typography.label.fontSize },
  previewSectionTitle: { ...Theme.typography.label, color: C.primary, padding: Theme.spacing.md, paddingBottom: Theme.spacing.sm, backgroundColor: C.bg, borderBottomWidth: 1, borderBottomColor: C.border },
  previewGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  previewItem: { width: '50%', padding: 10, borderBottomWidth: 1, borderBottomColor: C.border, borderRightWidth: 1, borderRightColor: C.border },
  previewLabel: { fontSize: Theme.typography.label.fontSize, color: C.muted, textTransform: 'uppercase' },
  previewValue: { ...Theme.typography.caption, color: C.text, marginTop: 2 },
  tableContainer: {
    backgroundColor: C.card,
    marginBottom: Theme.spacing.md,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: C.border,
    overflow: 'hidden',
    ...Platform.select({
      android: { elevation: 2 },
      ios: {
        shadowColor: Theme.colors.text,
        shadowOpacity: 0.06,
        shadowRadius: 14,
        shadowOffset: { width: 0, height: 6 },
      },
    }),
  },
  filterBar: { padding: 14, borderBottomWidth: 1, borderBottomColor: C.border, gap: Theme.spacing.md },
  filterHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Theme.spacing.md },
  filterTitle: { ...Theme.typography.bodyMd, color: C.text },
  filterSubtitle: { ...Theme.typography.caption, color: C.muted, marginTop: 2 },
  filterBadge: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: Theme.radius.full, backgroundColor: C.primarySoft, borderWidth: 1, borderColor: C.primaryBorder },
  filterBadgeText: { ...Theme.typography.label, color: C.primary },
  searchInput: { flexDirection: 'row', alignItems: 'center', gap: Theme.spacing.sm, borderWidth: 1, borderColor: C.border, borderRadius: Theme.radius.md, paddingHorizontal: Theme.spacing.md, height: 46, backgroundColor: C.bg },
  searchField: { flex: 1, ...Theme.typography.body, color: C.text },
  filterGroup: { flexDirection: 'row', gap: Theme.spacing.sm, flexWrap: 'wrap' },
  filterGroupStack: { flexDirection: 'column' },
  filterRowMobile: { flexDirection: 'row', gap: Theme.spacing.sm, width: '100%', marginTop: Theme.spacing.xs },
  filterRowDesktop: { flexDirection: 'row', gap: Theme.spacing.sm },
  filterBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: Theme.spacing.md, paddingVertical: 10, borderRadius: Theme.radius.md, borderWidth: 1, borderColor: C.border, backgroundColor: C.card },
  filterBtnFullWidth: { width: '100%', justifyContent: 'center' },
  filterBtnText: { ...Theme.typography.caption, color: C.text },
  exportBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: Theme.spacing.md, paddingVertical: 10, borderRadius: Theme.radius.md, backgroundColor: C.success },
  exportBtnText: { ...Theme.typography.caption, color: Theme.colors.card },
  table: { minWidth: 800 },
  mobileList: { padding: Theme.spacing.md, gap: Theme.spacing.md },
  tableHeader: { flexDirection: 'row', backgroundColor: C.bg, paddingVertical: Theme.spacing.md, paddingHorizontal: Theme.spacing.md, borderBottomWidth: 1, borderBottomColor: C.border },
  headerCell: { ...Theme.typography.label, color: C.muted, textTransform: 'uppercase' },
  cellName: { width: '22%' },
  cellEmpId: { width: '10%' },
  cellContact: { width: '15%' },
  cellDesignation: { width: '15%' },
  cellDept: { width: '15%' },
  cellStatus: { width: '10%' },
  cellActions: { width: '10%' },
  teacherRow: { flexDirection: 'row', paddingVertical: 14, paddingHorizontal: Theme.spacing.md, borderBottomWidth: 1, borderBottomColor: C.border, alignItems: 'center', backgroundColor: C.card },
  teacherCellName: { width: '22%', flexDirection: 'row', alignItems: 'center', gap: 10 },
  teacherAvatar: { width: 36, height: 36, borderRadius: Theme.radius.md, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.18)' },
  avatarText: { color: Theme.colors.card, fontSize: Theme.typography.caption.fontSize },
  teacherName: { ...Theme.typography.body, color: C.text },
  teacherEmail: { ...Theme.typography.label, color: C.muted, marginTop: 2 },
  teacherCellEmpId: { width: '10%' },
  teacherCellContact: { width: '15%' },
  teacherCellDesignation: { width: '15%' },
  teacherCellDept: { width: '15%' },
  teacherCellStatus: { width: '10%' },
  teacherCellActions: { width: '10%', flexDirection: 'row', gap: Theme.spacing.sm },
  teacherText: { fontSize: Theme.typography.caption.fontSize, color: C.text },
  teacherSubText: { ...Theme.typography.label, color: C.muted, marginTop: 2 },
  iconBtn: { padding: Theme.spacing.sm, borderRadius: Theme.radius.sm, backgroundColor: C.bg, borderWidth: 1, borderColor: C.border },
  statusPill: { flexDirection: 'row', alignItems: 'center', gap: Theme.spacing.xs, paddingHorizontal: Theme.spacing.sm, paddingVertical: 5, borderRadius: Theme.radius.full, alignSelf: 'flex-start', borderWidth: 1 },
  statusActive: { backgroundColor: C.successSoft },
  statusInactive: { backgroundColor: C.errorSoft },
  statusText: { fontSize: Theme.typography.label.fontSize },
  statusActiveText: { color: C.success },
  statusInactiveText: { color: C.error },
  tableFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: Theme.spacing.md, borderTopWidth: 1, borderTopColor: C.border, backgroundColor: C.bg },
  footerText: { ...Theme.typography.caption, color: C.muted },
  pagination: { flexDirection: 'row', gap: 6 },
  pageBtn: { width: 34, height: 34, borderRadius: Theme.radius.sm, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: C.border, backgroundColor: C.card },
  pageBtnActive: { backgroundColor: C.primary, borderColor: C.primary },
  pageBtnDisabled: { opacity: 0.5 },
  pageBtnText: { ...Theme.typography.caption, color: C.muted },
  pageBtnTextActive: { color: Theme.colors.card },
  loadingContainer: { padding: Theme.spacing.xxl, alignItems: 'center', backgroundColor: C.card },
  loadingText: { marginTop: Theme.spacing.md, color: C.muted },
  emptyState: { alignItems: 'center', padding: Theme.spacing.xxl, backgroundColor: C.card },
  emptyTitle: { fontSize: Theme.typography.h4.fontSize, color: C.text, marginTop: Theme.spacing.md },
  emptyText: { fontSize: Theme.typography.caption.fontSize, color: C.muted, marginTop: Theme.spacing.xs },
  teacherCard: {
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: Theme.radius.lg,
    padding: 14,
    gap: Theme.spacing.md,
    ...Platform.select({
      android: { elevation: 1 },
      ios: {
        shadowColor: Theme.colors.text,
        shadowOpacity: 0.05,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
      },
    }),
  },
  teacherCardHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 },
  teacherCardIdentityContainer: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1, minWidth: 0 },
  teacherIdentity: { flex: 1, minWidth: 0 },
  teacherMetaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  teacherMetaItem: {
    width: '48%',
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: Theme.radius.md,
    paddingHorizontal: 10,
    paddingVertical: Theme.spacing.sm,
  },
  teacherMetaLabel: { fontSize: Theme.typography.label.fontSize, color: C.muted, textTransform: 'uppercase', marginBottom: 3 },
  teacherMetaValue: { fontSize: Theme.typography.caption.fontSize, color: C.text },
  teacherCardFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  teacherSubStack: { flex: 1, minWidth: 0 },
  teacherCardActions: { flexDirection: 'row', gap: Theme.spacing.sm },
  cardActionBtn: {
    minHeight: 34,
    paddingHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  cardActionSecondary: { backgroundColor: C.bg, borderWidth: 1, borderColor: C.border },
  cardActionPrimary: { backgroundColor: C.primary },
  cardActionSecondaryText: { ...Theme.typography.caption, color: C.primary },
  cardActionPrimaryText: { ...Theme.typography.caption, color: Theme.colors.card },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(15, 23, 42, 0.6)', justifyContent: 'center', alignItems: 'center', padding: Theme.spacing.md },
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  sheetCard: {
    backgroundColor: C.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '88%',
    width: '100%',
    overflow: 'hidden',
    ...Platform.select({
      android: { elevation: 16 },
      ios: {
        shadowColor: '#000',
        shadowOpacity: 0.18,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: -4 },
      },
    }),
  },
  sheetCardTall: {
    maxHeight: '92%',
  },
  sheetCardColumn: {
    flexDirection: 'column',
    flexShrink: 1,
  },
  sheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: C.border,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 6,
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Theme.spacing.xl,
    paddingBottom: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  sheetTitle: { fontSize: Theme.typography.h3.fontSize, color: C.text, fontWeight: '700' },
  sheetScroll: {
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 0,
  },
  sheetScrollContent: {
    paddingHorizontal: Theme.spacing.xl,
    paddingTop: Theme.spacing.md,
    paddingBottom: Theme.spacing.xl,
  },
  sheetFooter: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: Theme.spacing.xl,
    paddingTop: Theme.spacing.md,
    borderTopWidth: 1,
    borderTopColor: C.border,
    backgroundColor: C.card,
  },
  sheetFooterBtn: {
    flex: 1,
    minHeight: 46,
    borderRadius: Theme.radius.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  showMoreBtn: {
    alignSelf: 'center',
    marginTop: Theme.spacing.sm,
    marginBottom: Theme.spacing.xs,
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: 14,
    borderRadius: Theme.radius.full,
    backgroundColor: C.primarySoft,
  },
  showMoreText: { color: C.primary, fontSize: Theme.typography.caption.fontSize },
  modalContent: {
    backgroundColor: C.card,
    borderRadius: Theme.radius.xxl,
    width: '90%',
    maxHeight: '90%',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.15)',
    shadowColor: Theme.colors.text,
    shadowOpacity: 0.15,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  modalLarge: { width: '95%', maxWidth: 800 },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Theme.spacing.xl,
    paddingTop: Theme.spacing.xl,
    paddingBottom: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  modalTitle: { fontSize: Theme.typography.h3.fontSize, color: C.text, fontWeight: '700' },
  closeBtn: { width: 36, height: 36, borderRadius: Theme.radius.lg, backgroundColor: Theme.colors.background, alignItems: 'center', justifyContent: 'center' },
  modalBody: { paddingHorizontal: Theme.spacing.xl, paddingBottom: Theme.spacing.lg },
  profileSheet: { gap: 18 },
  profileHeaderCardGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    padding: Theme.spacing.xl,
    borderRadius: Theme.radius.xl,
    marginBottom: Theme.spacing.sm,
    backgroundColor: Theme.colors.primary,
  },
  profileHeaderCardGradientCompact: {
    flexDirection: 'column',
    alignItems: 'center',
    paddingVertical: Theme.spacing.lg,
  },
  profileHeaderMetaCentered: {
    alignItems: 'center',
  },
  profileTextCentered: {
    textAlign: 'center',
  },
  profileAvatarContainer: {
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    borderRadius: 26,
    padding: 2,
  },
  profileAvatarLarge: {
    width: 68,
    height: 68,
    borderRadius: 22,
    backgroundColor: Theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileAvatarText: { color: C.primary, fontSize: Theme.typography.h2.fontSize },
  profileHeaderMeta: { flex: 1, minWidth: 0, gap: Theme.spacing.xs },
  profileName: { fontSize: Theme.typography.h3.fontSize, color: Theme.colors.card, fontWeight: '700', textAlign: 'left' },
  profileRole: { fontSize: Theme.typography.caption.fontSize, color: '#93c5fd', fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5 },
  profileSubText: { ...Theme.typography.caption, color: Theme.colors.textSec },
  statusActiveCard: { backgroundColor: 'rgba(16, 185, 129, 0.18)', borderColor: 'rgba(16, 185, 129, 0.3)' },
  statusInactiveCard: { backgroundColor: 'rgba(239, 68, 68, 0.18)', borderColor: 'rgba(239, 68, 68, 0.3)' },
  statusActiveCardText: { color: Theme.colors.success },
  statusInactiveCardText: { color: Theme.colors.error },
  detailSection: { gap: 10, marginTop: Theme.spacing.xs },
  detailSectionTitle: { ...Theme.typography.caption, color: C.muted, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.8 },
  modalFooter: { flexDirection: 'row', justifyContent: 'flex-end', gap: Theme.spacing.md, paddingHorizontal: Theme.spacing.xl, paddingVertical: Theme.spacing.md, borderTopWidth: 1, borderTopColor: C.border },
  saveBtn: {
    backgroundColor: C.primary,
    paddingHorizontal: Theme.spacing.lg,
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: C.primary,
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  saveBtnText: { color: Theme.colors.card, ...Theme.typography.body, fontWeight: '700' },
  detailGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, justifyContent: 'space-between' },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    backgroundColor: Theme.colors.background,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    marginBottom: Theme.spacing.sm,
  },
  detailIconContainer: {
    width: 36,
    height: 36,
    borderRadius: Theme.radius.md,
    backgroundColor: C.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailInfoContainer: {
    flex: 1,
    minWidth: 0,
  },
  detailLabel: { fontSize: Theme.typography.label.fontSize, color: C.muted, textTransform: 'uppercase', fontWeight: '700', letterSpacing: 0.5 },
  detailValue: { fontSize: Theme.typography.caption.fontSize, color: C.text, marginTop: 2, fontWeight: '600' },
  dateText: { ...Theme.typography.body, color: C.text },
  placeholderText: { ...Theme.typography.body, color: C.muted },
  errorText: { ...Theme.typography.label, color: C.error, marginTop: Theme.spacing.xs },
  photoZone: {
    borderWidth: 2,
    borderColor: C.border,
    borderStyle: 'dashed',
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.xl,
    alignItems: 'center',
    backgroundColor: C.bg,
    marginTop: Theme.spacing.sm,
  },
  photoPreview: {
    width: 100,
    height: 100,
    borderRadius: Theme.radius.md,
    resizeMode: 'cover',
  },
  photoPlaceholder: {
    alignItems: 'center',
  },
  photoText: {
    ...Theme.typography.body,
    fontWeight: '600',
    color: C.text,
    marginTop: Theme.spacing.sm,
  },
  photoSubtext: {
    ...Theme.typography.label,
    color: C.muted,
    marginTop: Theme.spacing.xs,
  },
  previewPhotoImage: {
    width: '100%',
    height: '100%',
    borderRadius: 32,
  },
  footer: { flexDirection: 'row', flexWrap: 'wrap', gap: Theme.spacing.md, padding: Theme.spacing.md, backgroundColor: C.card, borderTopWidth: 1, borderTopColor: C.border },
  footerItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  footerStrong: { color: C.text },
  headerContentContainer: {
    marginBottom: Theme.spacing.sm,
  },
  headerToggle: {
    width: '100%',
  },
});
