import { StyleSheet , Platform} from 'react-native';
import {Theme, C, colors} from '../../../theme/tokens';
import { HEADER_CONSTANTS } from '../../../constants/headerConstants';

export const settingsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },
  headerStandard: {
    backgroundColor: C.navy,
    paddingHorizontal: Theme.spacing.xl,
    paddingBottom: HEADER_CONSTANTS.PADDING_BOTTOM,
    borderBottomLeftRadius: HEADER_CONSTANTS.BORDER_RADIUS,
    borderBottomRightRadius: HEADER_CONSTANTS.BORDER_RADIUS,
    ...Platform.select({
      android: { elevation: 10 },
      ios: {},
    }),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
  },
  contentOverlap: {
    flex: 1,
    backgroundColor: C.bg,
    borderTopLeftRadius: HEADER_CONSTANTS.BORDER_RADIUS,
    borderTopRightRadius: HEADER_CONSTANTS.BORDER_RADIUS,
    marginTop: -HEADER_CONSTANTS.BORDER_RADIUS,
    zIndex: 10,
    overflow: 'hidden',
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: Theme.spacing.md,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.xl,
    backgroundColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    color: Theme.colors.card,
    fontSize: Theme.typography.h3.fontSize,
    textAlign: 'center',
  },
  headerContent: {
    marginTop: Theme.spacing.lg,
  },
  headerGreeting: {
    color: Theme.colors.card,
    fontSize: Theme.typography.h1.fontSize,
    letterSpacing: -0.5,
  },
  headerSubtext: {
    color: 'rgba(255,255,255,0.7)',
    ...Theme.typography.body,
    marginTop: Theme.spacing.xs,
  },
  headerSpacer: {
    width: 40,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: Theme.spacing.md,
    paddingBottom: 100,
  },
  settingsPanel: {
    backgroundColor: C.card,
    borderRadius: Theme.radius.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
    overflow: 'hidden',
  },
  body: {
    paddingHorizontal: Theme.spacing.md,
    paddingTop: Theme.spacing.xs,
    paddingBottom: Theme.spacing.md,
  },
  settingRowContainer: {
    paddingVertical: 14,
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
  },
  settingRowHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
  },
  iconCircle: {
    width: 36,
    height: 36,
    borderRadius: Theme.radius.lg,
    backgroundColor: 'rgba(30, 58, 138, 0.06)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  settingTextContainer: {
    flex: 1,
  },
  settingTitle: {
    fontSize: Theme.typography.bodyMd.fontSize,
    fontWeight: '600',
    color: C.text,
    marginBottom: 2,
  },
  settingDescription: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.textMuted,
    lineHeight: 18,
  },
  segmentedControl: {
    flexDirection: 'row',
    backgroundColor: Theme.colors.backgroundAlt,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.xs,
    marginTop: Theme.spacing.xs,
  },
  segment: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: Theme.radius.sm,
  },
  segmentActive: {
    backgroundColor: Theme.colors.card,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  segmentText: {
    fontSize: Theme.typography.body.fontSize,
    color: Theme.colors.textSec,
    fontWeight: '500',
  },
  segmentTextActive: {
    color: C.primary,
    fontWeight: '700',
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: C.border,
    marginHorizontal: Theme.spacing.md,
  },
  actionRow: {
    marginTop: Theme.spacing.lg,
    marginBottom: 10,
    gap: Theme.spacing.md,
  },
  secondaryButton: {
    marginTop: Theme.spacing.sm,
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Theme.spacing.sm,
    borderWidth: 1,
    borderColor: C.primary,
    backgroundColor: 'rgba(30, 58, 138, 0.04)',
  },
  secondaryButtonText: {
    color: C.primary,
    fontSize: Theme.typography.body.fontSize,
  },
  warningButton: {
    backgroundColor: Theme.colors.warning,
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.xl,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Theme.spacing.sm,
  },
  warningHint: {
    marginTop: Theme.spacing.sm,
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.error,
    fontWeight: '600',
  },
  statusPill: {
    marginTop: Theme.spacing.sm,
    paddingHorizontal: 14,
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    borderWidth: 1,
  },
  statusPillOn: {
    backgroundColor: '#f0fdf4',
    borderColor: '#bcf0da',
  },
  statusPillOff: {
    backgroundColor: '#fef2f2',
    borderColor: '#fecaca',
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusDotOn: { backgroundColor: Theme.colors.success },
  statusDotOff: { backgroundColor: Theme.colors.error },
  statusPillText: { fontSize: Theme.typography.caption.fontSize },
  statusTextOn: { color: '#166534' },
  statusTextOff: { color: '#991b1b' },
  numberGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Theme.spacing.md,
    marginTop: Theme.spacing.sm,
  },
  numberField: {
    width: '47%',
    minWidth: 120,
  },
  numberLabel: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.textMuted,
    marginBottom: 6,
  },
  numberInput: {
    height: 42,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.md,
    fontSize: Theme.typography.bodyMd.fontSize,
    color: C.text,
    backgroundColor: Theme.colors.card,
  },
  totalHint: {
    marginTop: 10,
    fontSize: Theme.typography.caption.fontSize,
    color: C.textMuted,
  },
  saveButton: {
    backgroundColor: C.primary,
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.xl,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Theme.spacing.sm,
    shadowColor: C.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  saveButtonDisabled: {
    opacity: 0.55,
  },
  saveButtonText: {
    color: Theme.colors.card,
    fontSize: Theme.typography.bodyMd.fontSize,
  },
  messageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    marginTop: Theme.spacing.md,
  },
  successMessage: {
    backgroundColor: C.successBg,
  },
  errorMessage: {
    backgroundColor: C.errorBg,
  },
  messageText: {
    flex: 1,
    fontSize: Theme.typography.caption.fontSize,
  },
  successText: {
    color: C.successText,
  },
  errorText: {
    color: C.errorText,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: C.bg + 'CC',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Theme.radius.md,
  },
  loadingText: {
    marginTop: Theme.spacing.md,
    ...Theme.typography.body,
    color: C.textMuted,
  },
});
