import { StyleSheet } from 'react-native';
import {Theme, C, colors} from '../../../theme/tokens';

export const expenseStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },
  contentOverlap: {
        backgroundColor: C.bg,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingTop: Theme.spacing.md,
    flex: 1,
    minHeight: 800,
  },
  scrollView: {
    flex: 1,
  },
  formSection: {
    backgroundColor: Theme.colors.background,
    padding: Theme.spacing.lg,
    borderRadius: Theme.radius.xxl,
    marginBottom: Theme.spacing.md,
    shadowColor: Theme.colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.04)',
  },
  formTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: Theme.colors.text,
    marginBottom: Theme.spacing.md,
    marginLeft: Theme.spacing.sm,
  },
  formGroup: {
    gap: Theme.spacing.xl,
  },
  label: {
    color: Theme.colors.textMuted,
    ...Theme.typography.body,
    marginBottom: 6,
  },
  input: {
    padding: 14,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    ...Theme.typography.bodyMd,
    backgroundColor: Theme.colors.background,
    color: Theme.colors.text,
  },
  inputFocused: {
    borderColor: Theme.colors.blue,
    backgroundColor: Theme.colors.background,
    shadowColor: Theme.colors.blue,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 2,
  },
  dateInput: {
    padding: 14,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.background,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dateText: {
    ...Theme.typography.body,
    color: Theme.colors.text,
  },
  categoryScroll: {
    flexDirection: 'row',
    marginVertical: Theme.spacing.xs,
  },
  categoryContainer: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
  },
  categoryOption: {
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 10,
    borderRadius: Theme.radius.xxl,
    borderWidth: 1,
  },
  categoryOptionText: {
    ...Theme.typography.body,
  },
  submitButton: {
    marginTop: Theme.spacing.sm,
  },
  listSection: {
    flex: 1,
    margin: Theme.spacing.md,
    marginTop: Theme.spacing.sm,
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
    flexWrap: 'wrap',
    gap: Theme.spacing.md,
  },
  listTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: Theme.colors.text,
  },
  summaryCard: {
    backgroundColor: '#eff6ff',
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 10,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: '#bfdbfe',
    alignItems: 'flex-end',
    shadowColor: Theme.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1,
  },
  summaryLabel: {
    ...Theme.typography.label,
    color: Theme.colors.primaryDark,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  summaryAmount: {
    fontSize: Theme.typography.h2.fontSize,
    color: Theme.colors.blueLight,
  },
  categorySummary: {
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.xxl,
    padding: Theme.spacing.xl,
    marginBottom: Theme.spacing.xl,
    shadowColor: Theme.colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.04)',
  },
  categorySummaryTitle: {
    fontSize: Theme.typography.h4.fontSize,
    color: Theme.colors.text,
    marginBottom: Theme.spacing.md,
    marginLeft: Theme.spacing.sm,
  },
  categorySummaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Theme.spacing.md,
  },
  categorySummaryCard: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '28%',
    flexGrow: 1,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.04)',
    shadowColor: Theme.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1,
  },
  categorySummaryBadge: {
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.lg,
    marginBottom: 6,
  },
  categorySummaryText: {
    ...Theme.typography.caption,
  },
  categorySummaryAmount: {
    ...Theme.typography.body,
    color: Theme.colors.text,
  },
  expenseListContainer: {
    marginTop: Theme.spacing.sm,
  },
  expenseListItems: {
    gap: Theme.spacing.md,
  },
  expenseListHeader: {
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.xs,
    marginBottom: Theme.spacing.sm,
  },
  expenseListHeaderText: {
    fontSize: Theme.typography.h4.fontSize,
    color: Theme.colors.primary,
  },
  expenseCard: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.04)',
    shadowColor: Theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  expenseCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  expenseInfo: {
    flex: 1,
  },
  expenseTitle: {
    fontSize: Theme.typography.h4.fontSize,
    color: Theme.colors.text,
    marginBottom: 6,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    marginBottom: Theme.spacing.md,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: Theme.spacing.md,
  },
  expenseMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    flexWrap: 'wrap',
  },
  categoryBadge: {
    paddingHorizontal: 10,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.md,
  },
  categoryText: {
    ...Theme.typography.label,
  },
  expenseDate: {
    ...Theme.typography.caption,
    color: Theme.colors.textMuted,
  },
  expenseAmountContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: Theme.spacing.md,
  },
  expenseAmount: {
    fontSize: Theme.typography.h3.fontSize,
    color: Theme.colors.text,
  },
  deleteButtonCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: Theme.colors.redLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingContainer: {
    padding: Theme.spacing.xl,
    alignItems: 'center',
  },
  loadingText: {
    marginTop: Theme.spacing.md,
    color: C.textMuted,
  },
  emptyContainer: {
    padding: Theme.spacing.xxl,
    alignItems: 'center',
    backgroundColor: C.card,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: C.border,
  },
  emptyText: {
    fontSize: Theme.typography.h4.fontSize,
    color: C.textMuted,
    marginBottom: Theme.spacing.sm,
  },
  emptySubtext: {
    ...Theme.typography.body,
    color: C.border,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: C.card,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.xl,
    width: '80%',
    maxWidth: 320,
    borderWidth: 1,
    borderColor: C.border,
  },
  modalTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: C.text,
    marginBottom: Theme.spacing.md,
  },
  modalMessage: {
    ...Theme.typography.body,
    color: C.textMuted,
    marginBottom: Theme.spacing.xl,
    lineHeight: 20,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: Theme.radius.sm,
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: C.bg,
  },
  cancelButtonText: {
    color: C.text,
  },
  deleteButton: {
    backgroundColor: C.danger,
  },
  deleteButtonText: {
    color: Theme.colors.card,
  },
});
