import { StyleSheet, Platform } from 'react-native';
import { Theme, C } from '../../../theme/tokens';
import { PAGE_PAD } from './helpers';

export { PAGE_PAD };

export const attendanceStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },
  scrollView: {
    flex: 1,
  },
  contentContainer: {
    paddingTop: Theme.spacing.sm,
    paddingBottom: 40,
  },
  pagePad: {
    paddingHorizontal: PAGE_PAD,
  },
  segmentedTabContainer: {
    marginBottom: Theme.spacing.sm,
  },
  controlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Theme.spacing.sm,
    gap: Theme.spacing.sm,
  },
  controlPill: {
    flex: 1.1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.card,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
    borderRadius: Theme.radius.md,
    paddingVertical: 10,
  },
  controlPillText: {
    ...Theme.typography.caption,
    color: C.text,
  },
  scopeSwitcher: {
    flex: 1.2,
    flexDirection: 'row',
    backgroundColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    padding: 3,
  },
  scopeSwitcherBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 7,
    borderRadius: Theme.radius.sm,
  },
  scopeSwitcherBtnActive: {
    backgroundColor: C.card,
  },
  scopeSwitcherBtnText: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '600',
    color: C.muted,
  },
  scopeSwitcherBtnTextActive: {
    color: C.primary,
  },
  exportPill: {
    flex: 0.9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.primary,
    borderRadius: Theme.radius.md,
    paddingVertical: 10,
  },
  exportPillText: {
    ...Theme.typography.caption,
    color: C.white,
  },
  studentFilterRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: Theme.spacing.sm,
  },
  pickerPill: {
    flex: 1,
    backgroundColor: C.card,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 10,
  },
  pickerPillDisabled: {
    opacity: 0.55,
  },
  pickerPillContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pickerTextGroup: {
    flex: 1,
  },
  pickerLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: C.muted,
    marginBottom: 2,
  },
  pickerValue: {
    fontSize: Theme.typography.body.fontSize,
    color: C.text,
    fontWeight: '600',
  },
  pickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'flex-end',
    padding: Theme.spacing.md,
  },
  pickerSheet: {
    backgroundColor: C.card,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.md,
    maxHeight: '70%',
  },
  pickerSheetTitle: {
    fontSize: Theme.typography.h4.fontSize,
    color: C.text,
    marginBottom: Theme.spacing.md,
  },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  pickerRowTitle: {
    ...Theme.typography.body,
    color: C.text,
  },
  pickerRowSubtitle: {
    ...Theme.typography.label,
    color: C.muted,
    marginTop: 2,
  },
  pickerPct: {
    paddingHorizontal: 10,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.full,
  },
  toast: {
    position: 'absolute',
    top: 60,
    right: 16,
    left: 16,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    zIndex: 1000,
  },
  toastSuccess: {
    backgroundColor: C.success,
  },
  toastError: {
    backgroundColor: C.error,
  },
  toastText: {
    color: Theme.colors.card,
    textAlign: 'center',
  },
  header: {
    marginBottom: Theme.spacing.md,
  },
  title: {
    fontSize: Theme.typography.h2.fontSize,
    color: C.text,
  },
  subtitle: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.muted,
    marginTop: 2,
  },
  statementCard: {
    marginBottom: Theme.spacing.sm,
    borderRadius: Theme.radius.md,
  },
  statementHeader: {
    marginBottom: Theme.spacing.md,
  },
  statementTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: Theme.spacing.xs,
  },
  statementTitle: {
    ...Theme.typography.body,
    color: C.text,
  },
  statementRange: {
    fontSize: Theme.typography.label.fontSize,
    color: C.muted,
    fontWeight: '500',
  },
  statementGrid: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
  },
  statementItem: {
    flex: 1,
    paddingVertical: Theme.spacing.xs,
  },
  statementItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.sm,
  },
  statementItemLabel: {
    ...Theme.typography.caption,
    color: C.text2,
  },
  statementItemValue: {
    fontSize: Theme.typography.h3.fontSize,
    color: C.text,
  },
  progressBarBg: {
    height: 6,
    backgroundColor: 'rgba(226, 232, 240, 0.8)',
    borderRadius: 3,
    overflow: 'hidden',
    marginBottom: Theme.spacing.sm,
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  statementItemSub: {
    fontSize: Theme.typography.label.fontSize,
    color: C.muted,
  },
  searchFilterContainer: {
    marginBottom: Theme.spacing.sm,
  },
  searchBoxWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.card,
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.md,
    height: 44,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
    marginBottom: 10,
  },
  searchInputField: {
    flex: 1,
    fontSize: Theme.typography.caption.fontSize,
    color: C.text,
    paddingVertical: Theme.spacing.sm,
  },
  searchClearBtn: {
    padding: Theme.spacing.xs,
  },
  filterChipsScroll: {
    gap: Theme.spacing.sm,
  },
  filterChipItem: {
    paddingVertical: 6,
    paddingHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.sm,
    backgroundColor: '#F1F5F9',
  },
  filterChipItemActive: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  filterChipItemText: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '600',
    color: C.muted,
  },
  filterChipItemTextActive: {
    color: C.white,
  },
  listCard: {
    marginHorizontal: -PAGE_PAD,
    backgroundColor: C.card,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
    marginBottom: Theme.spacing.sm,
  },
  teacherCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.card,
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: PAGE_PAD,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.border,
    gap: Theme.spacing.md,
  },
  teacherAvatar: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.xl,
    backgroundColor: C.primary,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  teacherAvatarMuted: {
    opacity: 0.45,
  },
  teacherAvatarText: {
    fontSize: Theme.typography.h4.fontSize,
    color: C.white,
  },
  teacherInfo: {
    flex: 1,
    minWidth: 0,
  },
  teacherName: {
    fontSize: Theme.typography.bodyMd.fontSize,
    color: C.text,
    lineHeight: 20,
  },
  inactiveSuffix: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.muted,
    fontWeight: '400',
  },
  teacherMeta: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.text2,
    marginTop: 1,
    lineHeight: 16,
  },
  teacherEmail: {
    fontSize: Theme.typography.label.fontSize,
    color: C.muted,
    marginTop: 2,
    lineHeight: 14,
  },
  badge: {
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    flexShrink: 0,
  },
  badgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  badgeDotPresent: { backgroundColor: C.success },
  badgeDotHalfDay: { backgroundColor: C.warning },
  badgeDotAbsent: { backgroundColor: C.error },
  badgePresent: {
    backgroundColor: C.successSoft,
  },
  badgeHalfDay: {
    backgroundColor: C.warningSoft,
  },
  badgeAbsent: {
    backgroundColor: C.errorSoft,
  },
  badgeText: {
    fontSize: Theme.typography.label.fontSize,
  },
  badgePresentText: {
    color: C.success,
  },
  badgeHalfDayText: {
    color: C.warning,
  },
  badgeAbsentText: {
    color: C.error,
  },
  emptyStateCard: {
    padding: Theme.spacing.xl,
    backgroundColor: C.card,
    borderRadius: Theme.radius.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    fontSize: Theme.typography.h4.fontSize,
    color: C.text,
    marginBottom: Theme.spacing.xs,
  },
  emptyText: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.muted,
    textAlign: 'center',
  },
  pagination: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: Theme.spacing.md,
    marginTop: Theme.spacing.md,
  },
  pageBtn: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.md,
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: C.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageBtnDisabled: {
    opacity: 0.4,
  },
  pageBtnText: {
    ...Theme.typography.body,
    color: C.text,
  },
  pageInfo: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.muted,
  },
  splitLayout: {
    flexDirection: 'row',
    backgroundColor: C.card,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: C.border,
    overflow: 'hidden',
    minHeight: 500,
  },
  compactStack: {
    gap: Theme.spacing.sm,
  },
  classStatsBar: {
    marginHorizontal: -PAGE_PAD,
    paddingHorizontal: PAGE_PAD,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.border,
    backgroundColor: C.card,
    gap: Theme.spacing.sm,
  },
  classStatsTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  classStatsTitle: { flex: 1, minWidth: 0 },
  classStatsName: { fontSize: Theme.typography.bodyMd.fontSize, color: C.text, lineHeight: 20 },
  classStatsDate: { fontSize: Theme.typography.caption.fontSize, color: C.muted, marginTop: 2 },
  ratePill: {
    paddingHorizontal: 10,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.sm,
  },
  ratePillGood: { backgroundColor: C.successSoft },
  ratePillLow: { backgroundColor: C.errorSoft },
  ratePillText: { fontSize: Theme.typography.caption.fontSize },
  inlineStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: Theme.spacing.xs,
  },
  inlineStat: { fontSize: Theme.typography.caption.fontSize, color: C.text2 },
  inlineStatDot: { fontSize: Theme.typography.caption.fontSize, color: C.muted },
  mobilePanelCard: {
    marginBottom: Theme.spacing.sm,
    backgroundColor: C.card,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
  },
  statChipHeader: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: Theme.radius.md,
    minWidth: 54,
  },
  statSuccessBg: {
    backgroundColor: C.successSoft,
  },
  statDangerBg: {
    backgroundColor: C.errorSoft,
  },
  statChipValueText: {
    ...Theme.typography.body,
  },
  statChipLabelText: {
    fontSize: 8,
    textTransform: 'uppercase',
    marginTop: 1,
  },
  statsGridRow: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
  },
  miniStatBox: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.radius.md,
  },
  statTotalBg: {
    backgroundColor: 'rgba(241, 245, 249, 0.8)',
  },
  statPresentBg: {
    backgroundColor: C.successSoft,
  },
  statHalfBg: {
    backgroundColor: C.warningSoft,
  },
  statAbsentBg: {
    backgroundColor: C.errorSoft,
  },
  miniStatVal: {
    ...Theme.typography.bodyMd,
    color: C.text,
  },
  miniStatLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: C.muted,
    marginTop: 2,
  },
  sidebar: {
    width: 260,
    borderRightWidth: 1,
    borderRightColor: C.border,
    backgroundColor: C.bg,
  },
  sidebarTitle: {
    padding: Theme.spacing.md,
    ...Theme.typography.label,
    textTransform: 'uppercase',
    color: C.muted,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    backgroundColor: C.card,
  },
  classGroup: {
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  classHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  classDot: {
    width: 32,
    height: 32,
    borderRadius: Theme.radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  classDotText: {
    ...Theme.typography.caption,
    color: Theme.colors.card,
  },
  classTitle: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.text,
  },
  classSubtitle: {
    fontSize: Theme.typography.label.fontSize,
    color: C.muted,
    marginTop: 1,
  },
  sectionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    paddingLeft: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    borderLeftWidth: 3,
    borderLeftColor: 'transparent',
  },
  sectionItemSelected: {
    backgroundColor: C.primary + '20',
    borderLeftColor: C.primary,
  },
  radio: {
    width: 16,
    height: 16,
    borderRadius: Theme.radius.sm,
    borderWidth: 2,
    borderColor: C.muted,
    marginRight: 10,
  },
  radioSelected: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  sectionInfo: {
    flex: 1,
  },
  sectionName: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.text,
  },
  sectionNameSelected: {
    color: C.primary,
  },
  sectionSubtitle: {
    fontSize: Theme.typography.label.fontSize,
    color: C.muted,
    marginTop: 1,
  },
  sectionPct: {
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: 2,
    borderRadius: Theme.radius.md,
  },
  sectionPctHigh: {
    backgroundColor: C.successSoft,
  },
  sectionPctLow: {
    backgroundColor: C.errorSoft,
  },
  sectionPctText: {
    ...Theme.typography.label,
    color: C.text,
  },
  mainPanel: {
    flex: 1,
  },
  panelHeader: {
    padding: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 10,
  },
  panelTitle: {
    ...Theme.typography.bodyMd,
    color: C.text,
  },
  panelSubtitle: {
    ...Theme.typography.label,
    color: C.muted,
    marginTop: 2,
  },
  statsRow: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
  },
  statChip: {
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: Theme.radius.sm,
  },
  statTotal: {
    backgroundColor: C.bg,
  },
  statPresent: {
    backgroundColor: C.successSoft,
  },
  statHalf: {
    backgroundColor: C.warningSoft,
  },
  statAbsent: {
    backgroundColor: C.errorSoft,
  },
  statSuccess: {
    backgroundColor: C.successSoft,
  },
  statDanger: {
    backgroundColor: C.errorSoft,
  },
  statValue: {
    fontSize: Theme.typography.h4.fontSize,
    color: C.text,
  },
  statLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: C.muted,
    marginTop: 2,
  },
  searchFilterBar: {
    padding: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    gap: 10,
  },
  emptyPanel: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: C.bg,
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  tableHeaderText: {
    ...Theme.typography.label,
    color: C.muted,
    textTransform: 'uppercase',
  },
  colNumber: { width: 50 },
  colName: { width: 200 },
  colRoll: { width: 100 },
  colAdmission: { width: 120 },
  colStatus: { width: 110 },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  tableCell: {
    // Shared with View rows; avoid text-only props here.
  },
  cellNumber: {
    textAlign: 'center',
    color: C.muted,
  },
  cellName: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  cellMono: {
    fontFamily: Platform.OS === 'ios' ? 'Courier New' : 'monospace',
    color: C.muted,
  },
  studentAvatar: {
    width: 36,
    height: 36,
    borderRadius: Theme.radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  studentAvatarText: {
    ...Theme.typography.caption,
    color: Theme.colors.card,
  },
  studentNameText: {
    fontSize: Theme.typography.bodyMd.fontSize,
    color: C.text,
    lineHeight: 20,
  },
  attendanceBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    padding: Theme.spacing.md,
    borderTopWidth: 1,
    borderTopColor: C.border,
    backgroundColor: C.bg,
  },
  attendanceLabel: {
    ...Theme.typography.label,
    color: C.muted,
  },
  attendanceTrack: {
    flex: 1,
    height: 6,
    backgroundColor: C.border,
    borderRadius: 3,
    overflow: 'hidden',
  },
  attendanceFill: {
    height: '100%',
    backgroundColor: C.success,
    borderRadius: 3,
  },
  attendancePct: {
    fontSize: Theme.typography.caption.fontSize,
  },
  attendancePctHigh: {
    color: C.success,
  },
  attendancePctLow: {
    color: C.error,
  },
  footer: {
    marginTop: Theme.spacing.md,
    paddingTop: Theme.spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: C.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: Theme.spacing.xs,
  },
  footerText: {
    ...Theme.typography.label,
    color: C.muted,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Theme.spacing.md,
  },
  modalContent: {
    backgroundColor: C.card,
    borderRadius: Theme.radius.xl,
    width: '100%',
    maxHeight: '80%',
    borderWidth: 1,
    borderColor: C.border,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  modalTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: C.text,
  },
  modalClose: {
    width: 32,
    height: 32,
    borderRadius: Theme.radius.lg,
    backgroundColor: C.bg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCloseText: {
    fontSize: Theme.typography.h4.fontSize,
    color: C.muted,
  },
  modalBody: {
    padding: Theme.spacing.md,
  },
  modalLabel: {
    ...Theme.typography.body,
    color: C.text,
    marginBottom: Theme.spacing.md,
  },
  dateRangeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    marginBottom: Theme.spacing.sm,
  },
  dateBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: Theme.radius.sm,
    backgroundColor: C.bg,
  },
  dateText: {
    ...Theme.typography.body,
    color: C.text,
  },
  sectionActions: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
    alignItems: 'center',
  },
  dateArrow: {
    ...Theme.typography.body,
    color: C.muted,
  },
  modalHint: {
    ...Theme.typography.label,
    color: C.muted,
    marginBottom: Theme.spacing.md,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
  },
  selectAllBtn: {
    paddingHorizontal: 10,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.sm,
    borderWidth: 1,
    borderColor: C.primary,
  },
  selectAllText: {
    ...Theme.typography.label,
    color: C.primary,
  },
  clearAllBtn: {
    paddingHorizontal: 10,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.sm,
    borderWidth: 1,
    borderColor: C.error,
  },
  clearAllText: {
    ...Theme.typography.label,
    color: C.error,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: C.border,
    marginLeft: 'auto',
  },
  checkboxChecked: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  checkboxIndeterminate: {
    backgroundColor: C.muted,
    borderColor: C.muted,
  },
  checkboxSmall: {
    width: 16,
    height: 16,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: C.border,
    marginRight: 10,
  },
  checkboxSmallChecked: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Theme.spacing.sm,
    paddingLeft: Theme.spacing.xl,
    paddingRight: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  sectionRowSelected: {
    backgroundColor: C.primary + '20',
  },
  sectionText: {
    flex: 1,
    fontSize: Theme.typography.caption.fontSize,
    color: C.text,
  },
  sectionCount: {
    ...Theme.typography.label,
    color: C.muted,
  },
  selectedCount: {
    marginTop: Theme.spacing.md,
    ...Theme.typography.caption,
    color: C.primary,
  },
  progressWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    backgroundColor: C.primary + '20',
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    marginTop: Theme.spacing.md,
  },
  progressText: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.primary,
  },
  modalFooter: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    padding: Theme.spacing.md,
    borderTopWidth: 1,
    borderTopColor: C.border,
  },
  mobileStudentList: {
    marginHorizontal: -PAGE_PAD,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: C.border,
    backgroundColor: C.card,
  },
  mobileStudentCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: PAGE_PAD,
    backgroundColor: C.card,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: C.border,
  },
  studentMetaLine: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.muted,
    marginTop: 1,
    lineHeight: 16,
  },
  mobileStudentInfo: {
    flex: 1,
    minWidth: 0,
  },
});
