import { StyleSheet } from 'react-native';
import {Theme, colors} from '../../../theme/tokens';

export const settingsStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Theme.colors.background },
  headerStandard: {
    backgroundColor: colors.accent,
    paddingHorizontal: Theme.spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: Theme.radius.xl,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: Theme.typography.h3.fontSize,
    fontWeight: '800',
    color: Theme.colors.card,
  },
  contentContainer: {
    gap: Theme.spacing.md,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.xl,
    marginBottom: Theme.spacing.xl,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
    marginBottom: Theme.spacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingBottom: Theme.spacing.md,
  },
  cardTitle: {
    fontSize: Theme.typography.h4.fontSize,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: Theme.spacing.md,
  },
  rowText: {
    ...Theme.typography.bodyMd,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: Theme.spacing.xs,
  },
  helperText: {
    fontSize: Theme.typography.caption.fontSize,
    color: colors.textMuted,
    lineHeight: 18,
  },
  dangerZoneCard: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.xl,
    borderColor: '#fecaca',
    borderWidth: 1.5,
    padding: Theme.spacing.md,
    shadowColor: colors.error,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
    marginTop: Theme.spacing.xl,
  },
  dangerZoneTitle: {
    fontSize: Theme.typography.h4.fontSize,
    fontWeight: '800',
    color: colors.error,
    marginBottom: Theme.spacing.xs,
  },
  dangerZoneSub: {
    ...Theme.typography.caption,
    color: colors.textMuted,
    marginBottom: Theme.spacing.md,
    lineHeight: 18,
  },
  dangerZoneActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Theme.spacing.sm,
    backgroundColor: colors.error,
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.md,
  },
  dangerZoneActionBtnText: {
    color: Theme.colors.card,
    ...Theme.typography.body,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Theme.spacing.xl,
  },
  modalContent: {
    backgroundColor: colors.surface,
    borderRadius: Theme.radius.xxl,
    width: '100%',
    maxHeight: '90%',
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Theme.spacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalTitle: {
    fontSize: Theme.typography.h3.fontSize,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  modalClose: {
    width: 32,
    height: 32,
    borderRadius: Theme.radius.lg,
    backgroundColor: Theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalBody: {
    padding: Theme.spacing.xl,
  },
  formGroup: {
    marginBottom: Theme.spacing.xl,
  },
  formLabel: {
    ...Theme.typography.label,
    fontWeight: '700',
    textTransform: 'uppercase',
    color: colors.textMuted,
    marginBottom: Theme.spacing.sm,
    letterSpacing: 0.5,
  },
  formInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    ...Theme.typography.bodyMd,
    backgroundColor: Theme.colors.background,
    color: colors.textPrimary,
  },
  warningBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.warningSoft,
    padding: 10,
    borderRadius: Theme.radius.sm,
    marginBottom: Theme.spacing.md,
    gap: Theme.spacing.sm,
    borderWidth: 1,
    borderColor: colors.warningSoft,
  },
  deleteIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Theme.spacing.md,
  },
  deletedDetailsCard: {
    backgroundColor: Theme.colors.card,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    width: '100%',
    marginVertical: Theme.spacing.md,
    gap: Theme.spacing.sm,
  },
  deletedDetailsText: {
    fontSize: Theme.typography.caption.fontSize,
    color: colors.textMuted,
  },
});
