import { StyleSheet , Platform} from 'react-native';
import {Theme, colors} from '../../../theme/tokens';

export const adminPlansStyles = StyleSheet.create({
  screenContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Theme.spacing.xl,
  },
  modalContent: {
    width: '100%',
    maxHeight: '90%',
    backgroundColor: colors.surface,
    borderRadius: Theme.radius.xl,
    overflow: 'hidden',
    flexDirection: 'column',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 15,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Theme.spacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalTitle: { ...Theme.typography.h3, color: colors.textPrimary },
  modalClose: { padding: Theme.spacing.xs },
  modalBodyScroll: {
    flexGrow: 0,
    flexShrink: 1,
  },
  modalBodyContent: {
    padding: Theme.spacing.xl,
    paddingBottom: Theme.spacing.sm,
  },
  modalFooter: { flexDirection: 'row', gap: Theme.spacing.md, padding: Theme.spacing.xl, borderTopWidth: 1, borderTopColor: colors.border },
  formGroup: { marginBottom: Theme.spacing.md },
  formLabel: { fontSize: Theme.typography.caption.fontSize, fontWeight: '600', color: colors.textPrimary, marginBottom: 6 },
  formInput: { backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border, borderRadius: Theme.radius.sm, padding: Theme.spacing.md, ...Theme.typography.body, color: colors.textPrimary },
  formInputError: { borderColor: colors.error },
  formError: { ...Theme.typography.label, color: colors.error, marginTop: Theme.spacing.xs },
  switchRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  switchLabel: { ...Theme.typography.body, color: colors.textPrimary },
  textArea: { height: 60, textAlignVertical: 'top' },
  planCard: {
    backgroundColor: colors.surface,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.md,
    marginBottom: 14,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: Theme.colors.background,
  },
  planCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  planName: {
    fontSize: Theme.typography.h4.fontSize,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  planCodeBadge: {
    backgroundColor: 'rgba(30, 58, 138, 0.06)',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: Theme.radius.sm,
    marginTop: Theme.spacing.xs,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: 'rgba(30, 58, 138, 0.1)',
  },
  planCodeText: {
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '800',
    color: colors.primary,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    letterSpacing: 0.5,
  },
  planEditBtn: {
    padding: Theme.spacing.sm,
    backgroundColor: 'rgba(30, 58, 138, 0.06)',
    borderRadius: Theme.radius.sm,
    borderWidth: 1,
    borderColor: 'rgba(30, 58, 138, 0.1)',
  },
  planDeleteBtn: {
    padding: Theme.spacing.sm,
    backgroundColor: colors.errorSoft,
    borderRadius: Theme.radius.sm,
    borderWidth: 1,
    borderColor: 'rgba(220, 38, 38, 0.1)',
  },
  planDesc: {
    fontSize: Theme.typography.caption.fontSize,
    color: colors.textMuted,
    marginTop: 10,
    lineHeight: 18,
  },
  planLimits: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 14,
    paddingTop: Theme.spacing.md,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.background,
  },
  limitItem: {
    alignItems: 'center',
    flex: 1,
  },
  priceLabel: {
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '700',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  priceValue: {
    ...Theme.typography.body,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  statusBadge: {
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: Theme.radius.sm,
  },
  statusText: {
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '700',
  },
});
