import { StyleSheet, Platform } from 'react-native';
import {Theme, colors} from '../../../theme/tokens';

export const marksEntryStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.colors.background,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  mainCard: {
    zIndex: 1,
    position: 'relative',
    marginHorizontal: 0,
    backgroundColor: Theme.colors.card,
    padding: Theme.spacing.lg,
    borderRadius: Theme.radius.lg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Theme.colors.border,
    marginBottom: Theme.spacing.md,
  },
  selectionRow: {
    flexDirection: 'row',
    marginBottom: 14,
  },
  selectionField: {
    flex: 1,
  },
  selectionLabel: {
    ...Theme.typography.body,
    color: Theme.colors.textSec,
    marginBottom: Theme.spacing.sm,
    fontWeight: '700',
  },
  selectionDropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.inputBg,
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.lg,
    paddingHorizontal: Theme.spacing.md,
    height: 56,
  },
  selectionDropdownDisabled: {
    backgroundColor: Theme.colors.backgroundAlt,
    borderColor: Theme.colors.border,
    opacity: 0.6,
  },
  selectionDropdownText: {
    flex: 1,
    ...Theme.typography.body,
    color: Theme.colors.text,
    fontWeight: '600',
    marginLeft: Theme.spacing.xs,
  },
  selectionHelperText: {
    marginTop: 6,
    ...Theme.typography.caption,
    color: Theme.colors.textMuted,
    fontWeight: '500',
  },
  selectionSearchBtn: {
    height: 58,
    borderRadius: Theme.radius.lg,
    backgroundColor: Theme.colors.primary,
    marginTop: 25,
    shadowColor: Theme.colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 6,
  },
  primaryButton: {
    backgroundColor: Theme.colors.primary,
    borderRadius: Theme.radius.lg,
    height: 52,
  },
  configCard: {
    marginHorizontal: 0,
    backgroundColor: Theme.colors.background,
    padding: Theme.spacing.xl,
    marginBottom: Theme.spacing.md,
    borderWidth: 1.5,
    borderColor: Theme.colors.background,
    ...Platform.select({
      android: { elevation: 2 },
      ios: {
        shadowColor: Theme.colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
      },
    }),
  },
  configHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
  },
  configTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
  },
  configTitle: {
    ...Theme.typography.bodyMd,
    color: Theme.colors.text,
  },
  savedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.xs,
    backgroundColor: '#dcfce7',
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.sm,
  },
  savedBadgeText: {
    ...Theme.typography.label,
    color: '#15803d',
    textTransform: 'uppercase',
  },
  configForm: {
    gap: Theme.spacing.md,
  },
  configRow: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
  },
  configInputGroup: {
    flex: 1,
    gap: 6,
  },
  configLabel: {
    ...Theme.typography.caption,
    color: Theme.colors.textSec,
  },
  configInput: {
    height: 48,
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.background,
    paddingHorizontal: 14,
    ...Theme.typography.bodyMd,
    color: Theme.colors.text,
  },
  configDisplay: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  configItem: {
    flex: 1,
    backgroundColor: Theme.colors.background,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.lg,
    borderWidth: 1.5,
    borderColor: Theme.colors.background,
  },
  configItemLabel: {
    fontSize: Theme.typography.label.fontSize,
    color: Theme.colors.textMuted,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  configItemValue: {
    fontSize: Theme.typography.h3.fontSize,
    color: Theme.colors.primary,
  },
  editConfigBtn: {
    width: 44,
    height: 44,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionBar: {
    marginHorizontal: 0,
    marginBottom: Theme.spacing.xl,
    gap: Theme.spacing.md,
  },
  statsRow: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
  },
  statChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
  },
  statSaved: {
    backgroundColor: '#f0fdf4',
    borderColor: '#bbf7d0',
  },
  statPending: {
    backgroundColor: '#fffbeb',
    borderColor: Theme.colors.amberLight,
  },
  statAbsent: {
    backgroundColor: '#fef2f2',
    borderColor: '#fecaca',
  },
  statText: {
    ...Theme.typography.label,
    color: Theme.colors.cardAlt,
  },
  buttonRow: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
  },
  autoSaveBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Theme.spacing.sm,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    backgroundColor: Theme.colors.background,
  },
  autoSaveBtnActive: {
    backgroundColor: Theme.colors.success,
    borderColor: Theme.colors.success,
  },
  autoSaveText: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textSec,
  },
  autoSaveTextActive: {
    color: Theme.colors.card,
  },
  secondaryActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: Theme.spacing.xs,
  },
  secondaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  secondaryBtnText: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.primary,
  },
  emptyCard: {
    marginHorizontal: 0,
    padding: Theme.spacing.xxl,
    alignItems: 'center',
    backgroundColor: Theme.colors.background,
    borderWidth: 1.5,
    borderColor: Theme.colors.background,
    marginTop: 10,
  },
  emptyTitle: {
    fontSize: Theme.typography.h2.fontSize,
    color: Theme.colors.text,
    marginTop: Theme.spacing.xl,
    marginBottom: Theme.spacing.sm,
  },
  emptyText: {
    ...Theme.typography.bodyMd,
    color: Theme.colors.textSec,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: Theme.spacing.lg,
  },
  emptyButton: {
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    paddingHorizontal: 36,
    paddingVertical: 14,
    borderRadius: Theme.radius.lg,
    backgroundColor: Theme.colors.background,
    marginTop: 10,
    ...Theme.shadow.sm,
  },
  emptyButtonText: {
    color: Theme.colors.text,
    ...Theme.typography.bodyMd,
    fontWeight: '700',
  },
  listWrapper: {
    marginHorizontal: 0,
    gap: Theme.spacing.md,
  },
  listTitle: {
    fontSize: Theme.typography.h4.fontSize,
    color: Theme.colors.text,
    marginBottom: Theme.spacing.xs,
    marginLeft: Theme.spacing.xs,
  },
  studentRow: {
    flexDirection: 'row',
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.xxl,
    padding: 18,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: Theme.colors.background,
    ...Platform.select({
      android: { elevation: 3 },
      ios: {
        shadowColor: Theme.colors.primary,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.06,
        shadowRadius: 12,
      },
    }),
    marginBottom: Theme.spacing.md,
  },
  studentRowAbsent: {
    backgroundColor: '#fef2f2',
    borderColor: '#fecaca',
  },
  studentRowSaved: {
    backgroundColor: '#f0fdf4',
    borderColor: '#bbf7d0',
  },
  studentInfoCol: {
    flex: 1,
    gap: Theme.spacing.xs,
  },
  studentMainInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
  },
  studentName: {
    flex: 1,
    ...Theme.typography.body,
    color: Theme.colors.text,
  },
  studentId: {
    ...Theme.typography.label,
    color: Theme.colors.textMuted,
    marginLeft: Theme.spacing.xs,
  },
  rollTag: {
    backgroundColor: Theme.colors.primary,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: Theme.radius.sm,
  },
  rollTagText: {
    fontSize: Theme.typography.label.fontSize,
    color: Theme.colors.card,
  },
  actionCol: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
  },
  attendanceToggle: {
    flexDirection: 'row',
    backgroundColor: Theme.colors.background,
    padding: 3,
    borderRadius: Theme.radius.md,
    gap: 2,
  },
  toggleBtn: {
    width: 32,
    height: 32,
    borderRadius: Theme.radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggleBtnActive: {
    backgroundColor: Theme.colors.success,
  },
  toggleBtnAbsentActive: {
    backgroundColor: Theme.colors.error,
  },
  toggleText: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textMuted,
  },
  toggleTextActive: {
    color: Theme.colors.card,
  },
  toggleTextAbsentActive: {
    color: Theme.colors.card,
  },
  marksContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  marksInput: {
    width: 48,
    height: 40,
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.background,
    textAlign: 'center',
    ...Theme.typography.bodyMd,
    color: Theme.colors.text,
  },
  marksInputDisabled: {
    backgroundColor: Theme.colors.background,
    borderColor: Theme.colors.textSec,
    color: Theme.colors.textMuted,
  },
  marksInputSaved: {
    borderColor: Theme.colors.success,
  },
  savedIndicator: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: Theme.colors.background,
    borderRadius: Theme.radius.md,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: Theme.colors.background,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    maxHeight: '90%',
    paddingBottom: 40,
    width: '100%',
  },
  configModalContent: {
    backgroundColor: Theme.colors.background,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingBottom: 40,
    width: '100%',
  },
  configModalBody: {
    padding: Theme.spacing.xl,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Theme.spacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.background,
  },
  modalTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: Theme.colors.text,
  },
  modalClose: {
    width: 36,
    height: 36,
    borderRadius: Theme.radius.lg,
    backgroundColor: Theme.colors.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBody: {
    padding: Theme.spacing.xl,
  },
  modalLabel: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textMuted,
    textTransform: 'uppercase',
    marginBottom: Theme.spacing.sm,
    letterSpacing: 0.5,
  },
  filterGroup: {
    marginBottom: Theme.spacing.md,
  },
  pickerSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Theme.colors.background,
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    paddingHorizontal: 14,
    height: 52,
  },
  pickerSelectorText: {
    ...Theme.typography.bodyMd,
    color: Theme.colors.text,
    fontWeight: '500',
  },
  modalFooter: {
    padding: Theme.spacing.xl,
    borderTopWidth: 1,
    borderTopColor: Theme.colors.background,
  },
});
