import { StyleSheet } from 'react-native';
import {Theme, colors} from '../../../theme/tokens';

export const renewalPaymentStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: Theme.colors.background,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  loaderWrap: {
    marginTop: 60,
    alignItems: 'center',
  },
  loaderMsg: {
    marginTop: Theme.spacing.md,
    color: Theme.colors.textMuted,
    fontSize: Theme.typography.caption.fontSize,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: Theme.spacing.lg,
  },
  errorMsg: {
    marginTop: Theme.spacing.md,
    color: Theme.colors.error,
    ...Theme.typography.body,
    textAlign: 'center',
  },
  retryBtn: {
    marginTop: Theme.spacing.md,
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.md,
    backgroundColor: Theme.colors.primary,
    borderRadius: Theme.radius.sm,
  },
  retryTxt: {
    color: Theme.colors.card,
    fontWeight: '600',
  },
  content: {
    paddingHorizontal: Theme.spacing.md,
    paddingTop: Theme.spacing.sm,
  },
  inlineError: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    backgroundColor: Theme.colors.errorBg,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
  },
  inlineErrorText: {
    flex: 1,
    color: Theme.colors.error,
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '600',
  },
  card: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.xl,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  statusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
    backgroundColor: Theme.colors.primaryDark,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
  },
  statusHeaderTitle: {
    color: Theme.colors.card,
    ...Theme.typography.bodyMd,
  },
  statusHeaderSub: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: Theme.typography.caption.fontSize,
    marginTop: 2,
  },
  statusBody: {
    padding: Theme.spacing.md,
  },
  label: {
    ...Theme.typography.caption,
    color: Theme.colors.textSec,
    marginTop: Theme.spacing.sm,
  },
  value: {
    ...Theme.typography.body,
    fontWeight: '600',
    color: Theme.colors.text,
  },
  sectionTitle: {
    fontSize: Theme.typography.h4.fontSize,
    fontWeight: '800',
    color: Theme.colors.text,
    marginBottom: Theme.spacing.md,
  },
  segmentedControl: {
    flexDirection: 'row',
    backgroundColor: '#eef2f6',
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.xs,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  segmentedTab: {
    flex: 1,
    paddingVertical: Theme.spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Theme.radius.md,
    flexDirection: 'row',
    gap: Theme.spacing.xs,
  },
  segmentedTabActive: {
    backgroundColor: Theme.colors.primary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  segmentedTabText: {
    ...Theme.typography.body,
    fontWeight: '700',
    color: Theme.colors.textSec,
  },
  segmentedTabTextActive: {
    color: Theme.colors.card,
  },
  badge: {
    backgroundColor: '#dcfce7',
    borderRadius: Theme.radius.md,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginLeft: Theme.spacing.xs,
  },
  badgeTxt: {
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '900',
    color: '#16a34a',
  },
  planCard: {
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.xl,
    marginBottom: Theme.spacing.xl,
    borderWidth: 1.5,
    borderColor: Theme.colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 10,
    elevation: 2,
  },
  planCardCurrent: {
    borderColor: Theme.colors.primary,
    backgroundColor: Theme.colors.background,
  },
  planCardPopular: {
    borderColor: Theme.colors.warning,
    borderWidth: 2,
  },
  planCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: Theme.spacing.md,
  },
  planCardTitle: {
    fontSize: Theme.typography.h3.fontSize,
    fontWeight: '800',
    color: Theme.colors.text,
  },
  planCardDesc: {
    ...Theme.typography.caption,
    color: Theme.colors.textSec,
    marginTop: Theme.spacing.xs,
  },
  currentPlanBadge: {
    backgroundColor: Theme.colors.blueLight,
    paddingHorizontal: 10,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.sm,
  },
  currentPlanBadgeTxt: {
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '800',
    color: Theme.colors.primary,
  },
  popularPlanBadge: {
    backgroundColor: Theme.colors.amberLight,
    paddingHorizontal: 10,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.sm,
  },
  popularPlanBadgeTxt: {
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '800',
    color: '#b45309',
  },
  planCardPricing: {
    marginBottom: Theme.spacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.background,
    paddingBottom: Theme.spacing.md,
  },
  planCardPriceRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  planCardPrice: {
    fontSize: Theme.typography.h1.fontSize,
    fontWeight: '900',
    color: Theme.colors.text,
  },
  planCardPeriod: {
    ...Theme.typography.body,
    color: Theme.colors.textSec,
    marginLeft: Theme.spacing.xs,
    fontWeight: '600',
  },
  planCardStrike: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textMuted,
    textDecorationLine: 'line-through',
    marginRight: Theme.spacing.sm,
  },
  planPriceBreakdown: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.primary,
    fontWeight: '700',
    marginTop: -12,
    marginBottom: 10,
  },
  planPerBranchMeta: {
    fontSize: Theme.typography.label.fontSize,
    color: Theme.colors.textSec,
    marginTop: -8,
    marginBottom: 10,
    fontWeight: '600',
  },
  branchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    marginTop: 14,
    paddingTop: Theme.spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Theme.colors.border,
  },
  branchRowLabel: {
    flex: 1,
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '700',
    color: Theme.colors.textSec,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  branchRowValue: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '800',
    color: Theme.colors.primary,
    backgroundColor: '#eff6ff',
    paddingHorizontal: 10,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.sm,
  },
  branchRowValueLimit: {
    color: '#92400e',
    backgroundColor: Theme.colors.amberLight,
  },
  branchHint: {
    fontSize: Theme.typography.label.fontSize,
    color: Theme.colors.textMuted,
    marginTop: Theme.spacing.sm,
    lineHeight: 16,
  },
  branchUpgradeCard: {
    marginTop: 14,
    backgroundColor: '#eff6ff',
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: '#bfdbfe',
    padding: 14,
  },
  branchUpgradeTitle: {
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '800',
    color: Theme.colors.blueLight,
    marginBottom: 6,
  },
  branchUpgradeBody: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textSec,
    lineHeight: 18,
  },
  planFeaturesList: {
    marginBottom: Theme.spacing.lg,
    gap: Theme.spacing.md,
  },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  featureIcon: {
    marginRight: 10,
  },
  featureText: {
    ...Theme.typography.body,
    color: Theme.colors.textSec,
    fontWeight: '500',
  },
  planCardBtn: {
    width: '100%',
    height: 48,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  planCardBtnCurrent: {
    backgroundColor: Theme.colors.border,
  },
  planCardBtnLoading: {
    backgroundColor: Theme.colors.textMuted,
  },
  planCardBtnDisabled: {
    backgroundColor: Theme.colors.background,
    borderWidth: 1.5,
    borderColor: Theme.colors.textSec,
  },
  planCardBtnTxt: {
    ...Theme.typography.bodyMd,
    fontWeight: '800',
    color: Theme.colors.card,
  },
  planCardBtnTxtCurrent: {
    color: Theme.colors.textSec,
  },
  emptyMsg: {
    textAlign: 'center',
    color: Theme.colors.textSec,
    fontWeight: '700',
    marginTop: Theme.spacing.xl,
  },
  successContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Theme.colors.background,
    padding: Theme.spacing.lg,
  },
  successBox: {
    backgroundColor: Theme.colors.background,
    borderRadius: 28,
    padding: 40,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  successTitle: {
    marginTop: Theme.spacing.md,
    fontSize: Theme.typography.h2.fontSize,
    fontWeight: '900',
    color: Theme.colors.text,
  },
  successMsg: {
    marginTop: Theme.spacing.sm,
    ...Theme.typography.body,
    color: Theme.colors.textSec,
    textAlign: 'center',
  },
  webViewHeader: {
    height: 56,
    backgroundColor: Theme.colors.background,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Theme.spacing.md,
  },
  webViewCloseBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
  },
  webViewCloseTxt: {
    ...Theme.typography.h4,
    color: Theme.colors.text,
  },
});
