import { StyleSheet, Platform } from 'react-native';
import { colors, Theme } from '../../../theme/tokens';

export const dashboardStyles = StyleSheet.create({
  alertBanner:{
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.warningSoft,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.md,
    gap: 10,
    borderWidth: 1,
    borderColor: colors.warningSoft,
  },
  alertText:{
    flex: 1,
    fontSize: Theme.typography.caption.fontSize,
    color: colors.warning,
    fontWeight: '600',
  },
  statsGrid:{
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: Theme.spacing.xl,
  },
  statCard:{
    width: '47%',
    flexGrow: 1,
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.lg,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  statValue:{
    fontSize: Theme.typography.h3.fontSize,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  skeletonValue:{
    height: 24,
    width: '60%',
    backgroundColor: colors.border,
    borderRadius: 4,
    marginBottom: Theme.spacing.xs,
  },
  statTitle:{
    fontSize: Theme.typography.label.fontSize,
    color: colors.textMuted,
    marginTop: 2,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  sectionTitle:{
    fontSize: Theme.typography.h4.fontSize,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: Theme.spacing.md,
  },
  filterBar:{
    marginBottom: Theme.spacing.md,
    gap: Theme.spacing.md,
  },
  filterChips:{
    flexDirection: 'row',
    gap: Theme.spacing.sm,
  },
  filterChip:{
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: 14,
    borderRadius: Theme.radius.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterChipActive:{
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  filterChipText:{
    ...Theme.typography.caption,
    fontWeight: '600',
    color: colors.textMuted,
  },
  filterChipTextActive:{
    color: Theme.colors.card,
  },
  searchContainer:{
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.md,
  },
  searchInput:{
    flex: 1,
    height: 48,
    ...Theme.typography.body,
    color: colors.textPrimary,
  },
  clearBtn:{
    padding: Theme.spacing.sm,
  },
  schoolCard:{
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
    backgroundColor: colors.surface,
    borderColor: colors.border,
  },
  cardHeader:{
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: Theme.spacing.md,
    gap: Theme.spacing.md,
  },
  schoolId:{
    ...Theme.typography.label,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    backgroundColor: Theme.colors.background,
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: 2,
    borderRadius: Theme.radius.sm,
    color: colors.accent,
    alignSelf: 'flex-start',
    marginBottom: Theme.spacing.xs,
    fontWeight: '700',
  },
  schoolName:{
    fontSize: Theme.typography.h4.fontSize,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  cardDetails:{
    marginBottom: Theme.spacing.md,
  },
  detailRow:{
    flexDirection: 'row',
    marginBottom: 6,
    alignItems: 'center',
  },
  detailLabel:{
    width: 90,
    fontSize: Theme.typography.caption.fontSize,
    color: colors.textMuted,
  },
  detailValue:{
    flex: 1,
    fontSize: Theme.typography.caption.fontSize,
    color: colors.textPrimary,
    fontWeight: '500',
  },
  cardActions:{
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Theme.spacing.sm,
    marginTop: Theme.spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: Theme.spacing.md,
  },
  actionBtn:{
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.sm,
    backgroundColor: Theme.colors.background,
    borderWidth: 1,
    borderColor: colors.border,
  },
  actionBtnText:{
    ...Theme.typography.caption,
    color: colors.textPrimary,
    fontWeight: '600',
  },
  pagination:{
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: Theme.spacing.md,
    marginTop: Theme.spacing.md,
  },
  pageBtn:{
    width: 40,
    height: 40,
    borderRadius: Theme.radius.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageBtnDisabled:{
    opacity: 0.5,
  },
  pageInfo:{
    fontSize: Theme.typography.caption.fontSize,
    color: colors.textMuted,
    fontWeight: '600',
  }
});
