import { StyleSheet, Platform } from 'react-native';
import { colors, Theme } from '../../../theme/tokens';

export const modalStyles = StyleSheet.create({
  modalOverlay:{
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: Theme.spacing.xl,
  },
  modalContent:{
    backgroundColor: colors.surface,
    borderRadius: Theme.radius.xxl,
    width: '100%',
    maxHeight: '90%',
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  subscriptionModal:{
    maxHeight: '95%',
  },
  modalHeader:{
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Theme.spacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalTitle:{
    fontSize: Theme.typography.h3.fontSize,
    fontWeight: '800',
    color: colors.textPrimary,
  },
  modalClose:{
    width: 32,
    height: 32,
    borderRadius: Theme.radius.lg,
    backgroundColor: Theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalBody:{
    padding: Theme.spacing.xl,
  },
  modalFooter:{
    flexDirection: 'row',
    gap: Theme.spacing.md,
    padding: Theme.spacing.xl,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  formGroup:{
    marginBottom: Theme.spacing.xl,
  },
  formLabel:{
    ...Theme.typography.label,
    fontWeight: '700',
    textTransform: 'uppercase',
    color: colors.textMuted,
    marginBottom: Theme.spacing.sm,
    letterSpacing: 0.5,
  },
  formInput:{
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    ...Theme.typography.bodyMd,
    backgroundColor: Theme.colors.background,
    color: colors.textPrimary,
  },
  formInputError:{
    borderColor: colors.error,
  },
  formError:{
    ...Theme.typography.caption,
    color: colors.error,
    marginTop: 6,
    fontWeight: '500',
  },
  textArea:{
    minHeight: 80,
    textAlignVertical: 'top',
  },
  switchRow:{
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Theme.colors.background,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  switchLabel:{
    ...Theme.typography.body,
    color: colors.textPrimary,
    fontWeight: '600',
  },
  tabBar:{
    flexDirection: 'row',
    paddingHorizontal: Theme.spacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  tabBtn:{
    paddingVertical: 14,
    marginRight: Theme.spacing.lg,
  },
  tabBtnActive:{
    borderBottomWidth: 2,
    borderBottomColor: colors.accent,
  },
  tabText:{
    ...Theme.typography.body,
    color: colors.textMuted,
    fontWeight: '600',
  },
  tabTextActive:{
    color: colors.accent,
  },
  infoGrid:{
    marginBottom: Theme.spacing.lg,
    gap: Theme.spacing.md,
    backgroundColor: Theme.colors.background,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  infoItem:{
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  infoLabel:{
    fontSize: Theme.typography.caption.fontSize,
    color: colors.textMuted,
  },
  infoValue:{
    ...Theme.typography.body,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  pickerContainer:{
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Theme.spacing.sm,
  },
  pickerOption:{
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.background,
    borderWidth: 1,
    borderColor: colors.border,
  },
  pickerOptionActive:{
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  pickerText:{
    fontSize: Theme.typography.caption.fontSize,
    color: colors.textMuted,
    fontWeight: '600',
  },
  pickerTextActive:{
    color: Theme.colors.card,
  },
  emptyPayments:{
    alignItems: 'center',
    padding: 40,
  },
  emptyText:{
    fontSize: Theme.typography.caption.fontSize,
    color: colors.textMuted,
    textAlign: 'center',
  },
  paymentItem:{
    backgroundColor: Theme.colors.background,
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.lg,
    marginBottom: Theme.spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  paymentHeader:{
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
  },
  paymentDate:{
    ...Theme.typography.caption,
    color: colors.textMuted,
    fontWeight: '600',
  },
  paymentAmount:{
    fontSize: Theme.typography.h3.fontSize,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: Theme.spacing.sm,
  },
  paymentPlan:{
    fontSize: Theme.typography.caption.fontSize,
    color: colors.textPrimary,
    marginBottom: Theme.spacing.xs,
    fontWeight: '600',
  },
  paymentMethod:{
    ...Theme.typography.caption,
    color: colors.textMuted,
    marginBottom: Theme.spacing.xs,
  },
  paymentTxId:{
    ...Theme.typography.label,
    color: colors.textMuted,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    marginTop: Theme.spacing.xs,
  },
  deleteModal:{
    backgroundColor: colors.surface,
    borderRadius: Theme.radius.xxl,
    padding: Theme.spacing.lg,
    width: '100%',
    maxWidth: 340,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  deleteIconWrap:{
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Theme.spacing.md,
  },
  deleteTitle:{
    fontSize: Theme.typography.h3.fontSize,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: Theme.spacing.sm,
  },
  deleteMessage:{
    ...Theme.typography.body,
    color: colors.textMuted,
    textAlign: 'center',
    marginBottom: Theme.spacing.md,
    lineHeight: 20,
  },
  deleteSchoolName:{
    backgroundColor: Theme.colors.background,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 10,
    borderRadius: Theme.radius.md,
    marginBottom: Theme.spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  deleteSchoolNameText:{
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '700',
    color: colors.error,
  },
  deleteActions:{
    flexDirection: 'row',
    gap: Theme.spacing.md,
    width: '100%',
  },
  modalContentLarge:{
    maxHeight: '95%',
  },
  modalTabBar:{
    flexDirection: 'row',
    paddingHorizontal: Theme.spacing.xl,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalTabBtn:{
    paddingVertical: 14,
    marginRight: Theme.spacing.lg,
  },
  modalTabBtnActive:{
    borderBottomWidth: 2,
    borderBottomColor: colors.accent,
  },
  modalTabText:{
    ...Theme.typography.body,
    color: colors.textMuted,
    fontWeight: '600',
  },
  modalTabTextActive:{
    color: colors.accent,
  },
  sectionHeader:{
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingBottom: 6,
  },
  sectionHeaderText:{
    ...Theme.typography.caption,
    fontWeight: '800',
    color: colors.accent,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  featureCard:{
    backgroundColor: Theme.colors.card,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    borderWidth: 1,
    borderColor: '#eef2f6',
    gap: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
  },
  featureRow:{
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  featureTextContainer:{
    flex: 1,
    marginRight: Theme.spacing.md,
  },
  featureTitle:{
    fontSize: Theme.typography.caption.fontSize,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  featureDesc:{
    ...Theme.typography.label,
    color: colors.textMuted,
    marginTop: 2,
  },
  inlineSelector:{
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: Theme.spacing.xs,
  },
  inlineSelectorOption:{
    paddingVertical: Theme.spacing.sm,
    paddingHorizontal: Theme.spacing.md,
    borderRadius: Theme.radius.sm,
    backgroundColor: Theme.colors.background,
    borderWidth: 1,
    borderColor: colors.border,
  },
  inlineSelectorOptionActive:{
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  inlineSelectorText:{
    ...Theme.typography.caption,
    color: colors.textMuted,
    fontWeight: '600',
  },
  inlineSelectorTextActive:{
    color: Theme.colors.card,
  },
  retentionCard:{
    padding: Theme.spacing.md,
    borderRadius: Theme.radius.md,
    borderWidth: 1.5,
    marginTop: Theme.spacing.md,
  },
  retentionHeader:{
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.sm,
  },
  retentionBadge:{
    fontSize: Theme.typography.label.fontSize,
    fontWeight: '700',
    color: colors.accent,
    backgroundColor: 'rgba(99, 102, 241, 0.1)',
    borderRadius: Theme.radius.md,
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: Theme.spacing.xs,
  },
  warningBanner:{
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.warningSoft,
    padding: 10,
    borderRadius: Theme.radius.sm,
    marginBottom: Theme.spacing.md,
    gap: Theme.spacing.sm,
    borderWidth: 1,
    borderColor: colors.warningSoft,
  },
  warningText:{
    ...Theme.typography.caption,
    fontWeight: '600',
    color: colors.warning,
  },
  statusBadge:{
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.sm,
    gap: 6,
  },
  statusDot:{
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  statusText:{
    ...Theme.typography.label,
    fontWeight: '700',
    textTransform: 'uppercase',
  }
});
