import { StyleSheet, Platform } from 'react-native';
import {Theme, colors} from '../../../theme/tokens';

export const homeworkStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.colors.background,
  },
  scrollContent: {
    paddingBottom: 60,
  },
  pageContent: {},
  createSection: {
    marginTop: 0,
  },
  createCard: {
    borderRadius: Theme.radius.xl,
    padding: Theme.spacing.md,
    backgroundColor: Theme.colors.card,
    marginBottom: Theme.spacing.lg,
    borderWidth: 1,
    borderColor: '#EEF2FF',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  createCardInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
  },
  createIconWrapper: {
    width: 56,
    height: 56,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.violetLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  createTitle: {
    fontSize: Theme.typography.h4.fontSize,
    color: Theme.colors.text,
    marginBottom: 2,
  },
  createSubtitle: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textSec,
  },
  createToggleTextWrap: {
    marginLeft: Theme.spacing.md,
  },
  formSectionTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: Theme.colors.text,
    marginBottom: Theme.spacing.md,
    letterSpacing: -0.5,
  },
  formGroup: {
    marginBottom: Theme.spacing.md,
  },
  formLabel: {
    fontSize: Theme.typography.caption.fontSize,
    color: Theme.colors.textSec,
    marginBottom: Theme.spacing.sm,
  },
  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Theme.colors.background,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.md,
  },
  disabledDropdown: {
    backgroundColor: Theme.colors.background,
    opacity: 0.6,
  },
  dropdownText: {
    ...Theme.typography.body,
    color: Theme.colors.textMuted,
    flex: 1,
  },
  dropdownValueText: {
    color: Theme.colors.text,
  },
  dropdownMenu: {
    backgroundColor: Theme.colors.card,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.sm,
    marginTop: Theme.spacing.sm,
    zIndex: 100,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    overflow: 'hidden',
  },
  dropdownItem: {
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.md,
    borderBottomWidth: 1,
  },
  dropdownItemText: {
    ...Theme.typography.body,
    color: Theme.colors.text,
  },
  textInput: {
    backgroundColor: Theme.colors.background,
    borderWidth: 1,
    borderColor: Theme.colors.border,
    borderRadius: Theme.radius.md,
    paddingVertical: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.md,
    ...Theme.typography.body,
    color: Theme.colors.text,
  },
  textArea: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  actionButtons: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
    marginTop: Theme.spacing.lg,
  },
  createButton: {
    flex: 1,
    height: 50,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.primaryLight,
  },
  cancelButton: {
    flex: 0.5,
    height: 50,
    borderRadius: Theme.radius.md,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: Theme.spacing.lg,
    marginBottom: Theme.spacing.md,
  },
  sectionTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: Theme.colors.text,
  },
  homeworkList: {
    gap: Theme.spacing.md,
  },
  homeworkCard: {
    padding: Theme.spacing.xl,
    borderRadius: 28,
    backgroundColor: Theme.colors.card,
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  homeworkCardEditing: {
    borderWidth: 2,
    borderColor: Theme.colors.blue,
    backgroundColor: '#F8FAFF',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
  },
  subjectContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    backgroundColor: Theme.colors.blueLight,
    paddingVertical: Theme.spacing.xs,
    paddingHorizontal: 10,
    borderRadius: Theme.radius.xl,
  },
  subjectIcon: {
    width: 24,
    height: 24,
    borderRadius: Theme.radius.md,
    backgroundColor: Theme.colors.card,
    justifyContent: 'center',
    alignItems: 'center',
  },
  subjectText: {
    ...Theme.typography.caption,
    color: Theme.colors.blue,
    textTransform: 'uppercase',
  },
  actionIcons: {
    flexDirection: 'row',
    gap: Theme.spacing.sm,
  },
  iconBtn: {
    padding: Theme.spacing.xs,
  },
  homeworkTitle: {
    fontSize: Theme.typography.h4.fontSize,
    color: Theme.colors.text,
    marginBottom: Theme.spacing.xs,
  },
  homeworkDesc: {
    ...Theme.typography.body,
    color: Theme.colors.textSec,
    lineHeight: 20,
    marginBottom: Theme.spacing.md,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: Theme.colors.background,
    paddingTop: Theme.spacing.md,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  metaText: {
    ...Theme.typography.caption,
    color: Theme.colors.textMuted,
  },
  loaderContainer: {
    padding: 40,
    alignItems: 'center',
  },
  emptyState: {
    padding: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyStateText: {
    marginTop: 10,
    color: Theme.colors.textMuted,
    ...Theme.typography.body,
    textAlign: 'center',
  },
});
