import { StyleSheet } from 'react-native';
import {Theme, C, colors} from '../../../theme/tokens';
import { HEADER_CONSTANTS } from '../../../constants/headerConstants';

export const feeManagementStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },
  contentOverlap: {
    flex: 1,
        backgroundColor: C.bg,
    borderTopLeftRadius: HEADER_CONSTANTS.BORDER_RADIUS,
    borderTopRightRadius: HEADER_CONSTANTS.BORDER_RADIUS,
    overflow: 'hidden',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  formSection: {
    backgroundColor: C.card,
    padding: Theme.spacing.xl,
    borderRadius: Theme.radius.lg,
    borderLeftWidth: 4,
    borderLeftColor: C.primary,
    marginBottom: Theme.spacing.lg,
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  formTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: C.text,
    marginBottom: Theme.spacing.md,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    marginBottom: Theme.spacing.md,
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  formGroup: {
    gap: Theme.spacing.md,
  },
  label: {
    color: C.text,
    ...Theme.typography.body,
  },
  selectedStudentBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: C.successSoft,
    borderWidth: 1,
    borderColor: C.success,
    borderRadius: Theme.radius.sm,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 10,
    marginTop: Theme.spacing.xs,
  },
  selectedStudentBadgeLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.sm,
    flex: 1,
  },
  selectedStudentText: {
    color: C.success,
    ...Theme.typography.body,
    flexShrink: 1,
  },
  clearSelectedStudentBtn: {
    padding: Theme.spacing.xs,
  },
  searchContainer: {
    position: 'relative',
    zIndex: 10,
  },
  suggestionsContainer: {
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: Theme.radius.sm,
    marginTop: Theme.spacing.xs,
    overflow: 'hidden',
  },
  suggestionItem: {
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  suggestionItemText: {
    ...Theme.typography.body,
    color: C.text,
  },
  suggestionItemSubtext: {
    ...Theme.typography.caption,
    color: C.textMuted,
  },
  noSuggestionItem: {
    padding: Theme.spacing.md,
    alignItems: 'center',
  },
  noSuggestionText: {
    ...Theme.typography.caption,
    color: C.textMuted,
    fontStyle: 'italic',
  },
  filterSection: {
    backgroundColor: C.card,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    marginBottom: Theme.spacing.md,
    borderWidth: 1,
    borderColor: C.border,
    gap: Theme.spacing.sm,
  },
  filterSearchInput: {
    padding: 10,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: Theme.radius.sm,
    ...Theme.typography.body,
    backgroundColor: C.bg,
    color: C.text,
  },
  statusFilterScroll: {
    marginTop: Theme.spacing.xs,
  },
  statusFilterContainer: {
    flexDirection: 'row',
    gap: 6,
  },
  statusFilterOption: {
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: 6,
    borderRadius: Theme.radius.sm,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.bg,
  },
  statusFilterOptionSelected: {
    backgroundColor: C.primary,
    borderColor: C.primary,
  },
  statusFilterOptionText: {
    ...Theme.typography.label,
    color: C.textMuted,
  },
  statusFilterOptionTextSelected: {
    color: Theme.colors.card,
  },
  input: {
    padding: Theme.spacing.md,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: Theme.radius.sm,
    ...Theme.typography.body,
    backgroundColor: C.bg,
    color: C.text,
  },
  dateInput: {
    padding: Theme.spacing.md,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: Theme.radius.sm,
    backgroundColor: C.bg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dateText: {
    ...Theme.typography.body,
    color: C.text,
  },
  submitButton: {
    backgroundColor: C.primary,
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: Theme.spacing.sm,
    marginTop: Theme.spacing.sm,
  },
  submitButtonText: {
    color: Theme.colors.card,
    fontSize: Theme.typography.h4.fontSize,
  },
  summaryContainer: {
    flexDirection: 'row',
    marginBottom: Theme.spacing.xl,
    gap: Theme.spacing.md,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: C.card,
    padding: Theme.spacing.md,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: C.border,
    borderLeftWidth: 4,
    borderLeftColor: C.primary,
    alignItems: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  summaryLabel: {
    ...Theme.typography.caption,
    color: C.textMuted,
    marginBottom: Theme.spacing.xs,
  },
  summaryValue: {
    fontSize: Theme.typography.h4.fontSize,
    color: C.text,
  },
  collectedValue: {
    color: C.success,
  },
  pendingValue: {
    color: C.error,
  },
  listSection: {
    marginHorizontal: Theme.spacing.md,
    marginTop: Theme.spacing.sm,
  },
  listTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: C.text,
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
    paddingHorizontal: Theme.spacing.xs,
  },
  countBadge: {
    backgroundColor: C.primarySoft,
    paddingHorizontal: 10,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.sm,
  },
  feeCount: {
    ...Theme.typography.caption,
    color: C.primary,
  },
  feesList: {
    backgroundColor: C.card,
    borderRadius: Theme.radius.lg,
    borderWidth: 1,
    borderColor: C.border,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  feeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  feeInfo: {
    flex: 1,
  },
  studentName: {
    fontSize: Theme.typography.h4.fontSize,
    color: C.text,
    marginBottom: Theme.spacing.sm,
  },
  feeDetails: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Theme.spacing.md,
    marginBottom: Theme.spacing.sm,
  },
  feeAmount: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.text,
  },
  paidAmount: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.success,
  },
  dueAmount: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.error,
  },
  feeMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Theme.spacing.md,
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.radius.md,
  },
  statusText: {
    ...Theme.typography.label,
  },
  dueDate: {
    ...Theme.typography.caption,
    color: C.textMuted,
  },
  paymentButtonContainer: {
    justifyContent: 'center',
  },
  paymentButton: {
    backgroundColor: C.primary,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.radius.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  paymentButtonText: {
    color: Theme.colors.card,
    fontSize: Theme.typography.caption.fontSize,
  },
  loadingContainer: {
    padding: Theme.spacing.xl,
    alignItems: 'center',
  },
  loadingText: {
    marginTop: Theme.spacing.md,
    color: C.textMuted,
  },
  emptyContainer: {
    padding: Theme.spacing.xxl,
    alignItems: 'center',
    backgroundColor: C.card,
    borderRadius: Theme.radius.md,
    borderWidth: 1,
    borderColor: C.border,
  },
  emptyText: {
    fontSize: Theme.typography.h4.fontSize,
    color: C.text,
    marginBottom: Theme.spacing.sm,
  },
  emptySubtext: {
    ...Theme.typography.body,
    color: C.textMuted,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: C.card,
    borderRadius: Theme.radius.lg,
    padding: Theme.spacing.lg,
    width: '90%',
    maxWidth: 400,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.xl,
  },
  modalTitle: {
    fontSize: Theme.typography.h3.fontSize,
    color: C.text,
  },
  modalInfo: {
    marginBottom: Theme.spacing.xl,
  },
  modalLabel: {
    ...Theme.typography.caption,
    color: C.textMuted,
    marginBottom: Theme.spacing.xs,
  },
  modalValue: {
    fontSize: Theme.typography.h4.fontSize,
    color: C.text,
    marginBottom: Theme.spacing.md,
  },
  modalInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  modalInfoCol: {
    flex: 1,
  },
  dueAmountValue: {
    color: C.error,
  },
  historySection: {
    marginVertical: 15,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: C.border,
  },
  historyTitle: {
    ...Theme.typography.body,
    color: C.text,
    marginBottom: 10,
  },
  historyList: {
    maxHeight: 150,
  },
  historyItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: Theme.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: C.bg,
  },
  historyAmount: {
    ...Theme.typography.body,
    color: C.text,
  },
  historyDate: {
    ...Theme.typography.label,
    color: C.textMuted,
  },
  historyMethodBadge: {
    backgroundColor: C.bg,
    paddingHorizontal: Theme.spacing.sm,
    paddingVertical: Theme.spacing.xs,
    borderRadius: 4,
  },
  historyMethodText: {
    fontSize: Theme.typography.label.fontSize,
    color: C.primary,
  },
  noHistoryText: {
    ...Theme.typography.caption,
    color: C.textMuted,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: 10,
  },
  modalForm: {
    marginBottom: Theme.spacing.xl,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: Theme.spacing.md,
  },
  modalButton: {
    flex: 1,
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.sm,
    alignItems: 'center',
  },
  cancelButton: {
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.border,
  },
  cancelButtonText: {
    color: C.textMuted,
  },
  payButton: {
    backgroundColor: C.primary,
  },
  payButtonText: {
    color: Theme.colors.card,
  },
  searchTriggerInput: {
    padding: Theme.spacing.md,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: Theme.radius.sm,
    backgroundColor: C.bg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: Theme.spacing.xs,
  },
  searchTriggerText: {
    ...Theme.typography.body,
    color: C.textMuted,
    flex: 1,
  },
  modalSearchContainer: {
    marginBottom: Theme.spacing.md,
  },
  modalSearchInput: {
    padding: Theme.spacing.md,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: Theme.radius.sm,
    ...Theme.typography.body,
    backgroundColor: C.bg,
    color: C.text,
  },
  modalStudentList: {
    maxHeight: 350,
  },
  studentSearchModal: {
    maxHeight: '80%',
    padding: Theme.spacing.xl,
  },
  suggestionRow: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  suggestionMain: {
    flex: 1,
    marginRight: Theme.spacing.sm,
  },
  detailModalContent: {
    maxWidth: 450,
  },
  detailScroll: {
    maxHeight: 500,
  },
  detailHero: {
    alignItems: 'center',
    marginBottom: Theme.spacing.lg,
    paddingVertical: 10,
  },
  detailHeroIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: C.successSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Theme.spacing.md,
  },
  detailHeroAmount: {
    fontSize: Theme.typography.h1.fontSize,
    color: C.text,
  },
  detailHeroStatus: {
    ...Theme.typography.body,
    color: C.success,
  },
  detailCard: {
    backgroundColor: C.bg,
    borderRadius: Theme.radius.md,
    padding: Theme.spacing.md,
    gap: Theme.spacing.md,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  detailLabel: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.textMuted,
  },
  detailValue: {
    fontSize: Theme.typography.caption.fontSize,
    color: C.text,
  },
  downloadReceiptBtn: {
    marginTop: Theme.spacing.lg,
    backgroundColor: C.bg,
    borderWidth: 1,
    borderColor: C.primary,
    paddingVertical: Theme.spacing.md,
    borderRadius: Theme.radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: Theme.spacing.sm,
  },
  downloadReceiptText: {
    color: C.primary,
  },
  detailBackBtn: {
    marginTop: Theme.spacing.md,
  },
});
